### ISSUE TITLE
Als teamlid/architect wil ik een samenhangend overzicht van relevante GEMMA 2 documenten 

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#100]
...zodat ik de architectuur voor ZDS 2.0 kan laten aansluiten op deze uitgangpunten.

**Definition of done**

- [x] Er is een overzicht van alle relevante documenten incl. status
- [x] Er is een beschrijving en visualisatie van de actuele RGBZ 2 
- [ ] Er is een beschrijving en visualisatie van de samenhang van relevante standaarden
- [ ] Er is een beschrijving en visualisatie van de gerelateerde referentiecomponenten
- [ ] Er is een beschrijving van wat SIMs en UGMs precies zijn

**Acceptatiecriteria**

- [ ] Samenhang tussen RGBZ2, ImZTC, RSGB, StUF-ZKN, ZDS, UGM GBZ etc is helder
- [ ] Relatie met de GEMMA Referentiecomponenten is duidelijk (i.i.g. ZTC, DRC, ZRC)

**Taken**
- [ ] Verzamelen documenten [@?]
- [ ] Opstellen overzicht [@?]

**Comment by ehotting** [comment]
@michielverhoef Is dit iets wat jij kunt doen? Heb vandaag uren gedwaald op gemmaonline.nl maar zonder gids kom ik er niet uit. Het is niet helder wat actueel is en wat niet, en actuele en niet actuele pagina's linken volop naar elkaar door. Terminologie loopt door elkaar heen. Een analyse is helaas nodig.

**Comment by jgortmaker1** [comment]
overzicht dan graag op één pagina op GEMMA online, zodat het voor iedereen duidelijk is en niet enkel voor dit Scrumteam.

Overigens kunnen de informatiemodellen volgens mij ook doorklikbaar gepubliceerd worden op GEMMA Online (net als de architectuurmodellen). Zou dat helpen? Dat heb ik eens in PoC gezien maar die link kan ik niet terugvinden.
@ArjanKloosterboer: werkt deze EA export naar GEMMAOnline al?

**Comment by ehotting** [comment]
Liever snel en niet doorklikbaar dan doorklikbaar en pas in sprint 2. Kan altijd daarna nog op gemmaonline worden gezet toch?

**Comment by TCIMEddy** [comment]
Helemaal eens

**Comment by ArjanKloosterboer** [comment]
De EA-export naar GEMMA Online werkt helaas nog niet voor nieuwe informatiemodellen. Daar wordt hard aan gewerkt. Voorlopig zullen we het moeten doen met EA- en MS-Word-versies. Die voor RGBZ 2 is net gepubliceerd, [alhier](https://www.gemmaonline.nl/index.php/Informatiemodel_RGBZ_2.0.1_-_specificaties_-_CONCEPT_20180605).

**Comment by ehotting** [comment]
Suggestie @ArjanKloosterboer volgend, de opzet voor een pagina waar het overzicht kan worden opgebouwd:  https://github.com/VNG-Realisatie/gemma-zaken/pull/115  - graag 'review / approve'

**Comment by TCIMEddy** [comment]
Volgens mij is deze idd ready for sprint 2. @michielverhoef is het voldoende duidelijk voor jou hoe dit opgepakt moet worden.
![schermafbeelding 2018-06-25 om 11 22 02](https://user-images.githubusercontent.com/39735549/41842466-29c360d0-786b-11e8-83c7-c8a9951996da.png)
