### ISSUE TITLE
Als ontwikkelaar wil ik weten wat er gebeurt op https://zaken-auth.vng.cloud

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#1035]
...zodat het minder magisch aanvoelt.

Er moet op elke pagina even een paragraafje komen met uitleg wat deze pagina doet onder de moterkap, want het is nu veel te beperkt waardoor het magisch aandoet, zelfs als je weet wat je aan het doen bent.

Zie: https://ref.tst.vng.cloud/tokens/

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Het is duidelijk wat de token-tool doet als je de pagina voor je hebt.

**Taken**
- [ ] Documentatie bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie

**Comment by joeribekker** [comment]
Michiel geeft aan dat het wel duidelijk is, aangezien ik het zelf op heb gegeven (en het mij wel duidelijk is) sluit ik het ticket. Als een leverancier extra uitleg nodig blijkt te hebben kan het via een nieuwe US weer worden aangekaart.
