### ISSUE TITLE
Als behandelaar van een melding openbare ruimte wil ik kunnen zoeken naar zaken en contacten die betrekking hebben op meldingen in hetzelfde gebied van dezelfde categorie of over hetzelfde probleem gaan ...

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#111]
... zodat ik dubbele meldingen kan afhandelen en meldingen kan plannen en routeren voor onze medewerkers in het veld (of voor een ketenpartner).

Dit impliceert het kunnen zoeken op basis van allerlei kenmerken van zaken en documenten, maar wel vanuit een bepaald proces (doelbinding).

Toepassingen van deze story: 
- direct zoeken vanuit een Zaakafhandelcomponent of KCS
- koppeling met enterprise search oplossingen die over meerdere bronnen indexeren.

~~Bij zoeken moet rekening gehouden worden met doelbinding volgens AVG..~~

Idee voor demonstratie: eenvoudig zoekscherm waarin je na invoer van een paar kenmerken de relevante zaken te zien krijgt (ev. op een kaartje).

Zie issue #184 voor de RGBZ-mapping.
Zie [hier](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Dimpact-MOR.md) voor de architectuurschets.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen architectuurschets [@Hugo-ter-Doest]
- [x] Opstellen welke velden bij een melding horen [@Hugo-ter-Doest]
- [ ] Aanleveren testdata [@Hugo-ter-Doest]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by jgortmaker1** [comment]
dit zal niet ongelimiteerd mogen volgens de AVG. moeten we hier nog rekening mee houden?

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat je dat met autorisatie (rollen/rechten) moet oplossen. Als je zoekt vanuit een bepaalde rol krijg je alleen die zaken, documenten en contacten te zien die je volgens je rol mag zien. En dat geldt ook voor het detailniveau van de zoekresultaten.

**Comment by jgortmaker1** [comment]
is de autorisatie zoals in het RGBZ zit hiervoor voldoende?
in ken in ieder geval "vertrouwlijkheids-aanduidding". Dat lijkt me hiervoor te beperkt. Zitten er nog meer mogelijkheden in? @ArjanKloosterboer?

In ieder geval iets om eerst een ontwerpje voor te maken door iemand die er verstand van heeft alvorens te beginnen met bouwen lijkt mij...wat doelbindingen op zaken, documenten en/of contacten konden wel eens ingewikkeld zijn...

**Comment by ArjanKloosterboer** [comment]
Het RGBZ regelt niets qua autorisatie, dat zal de software moeten doen. Maar, die moet zich wel ergens op kunnen baseren. En dat is die Vertrouwelijkheidaanduiding. Wat er m.i. geanalyseerd moet worden is wat de mogelijkheden mogen zijn per combinatie van rol (de generieke rolomschrijvingen en wellicht meer) en vertrouwelijkheidniveau.

**Comment by TCIMEddy** [comment]
Uiteraard moet dit goed geregeld worden. Lijkt me zinvol om de user story te specificeren voor zaaktype of iets dergelijks zodat deze kleiner wordt en behapbaar.

**Comment by Hugo-ter-Doest** [comment]
Architectuurschets is [hier](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Dimpact-MOR.md) te vinden.

**Comment by joeribekker** [comment]
> Bij zoeken moet rekening gehouden worden met doelbinding volgens AVG.

Dit wellicht er uit halen en apart behandelen.

**Comment by Hugo-ter-Doest** [comment]
Het zoeken naar zaken in een gebied is inmiddels mogelijk. Hoe zou het zoeken op categorie in aanvulling op gebied eruit kunnen zien? Immers, categorie staat niet in de ZRC, maar in de ORC.

**Comment by ArjanKloosterboer** [comment]
Ik neem aan dat je met de ORC doelt op de Zaaktypespecifieke afhandelcomponent voor MORren (Melding Openbare Ruimte) ('(MOR) ZAC' in je architectuurplaatje)? Dan is dit een interessante case: zoeken over meer dan één registratiecomponent heen. Dat gaat natuurlijk veel vaker spelen, in allerlei combinaties. Vergt m.i. een generieke aanpak die per geval (zoekvraag) verbijzonderd wordt. Wellicht hiervan een apart issue maken, om die generieke aanpak te bepalen?

**Comment by joeribekker** [comment]
@Hugo-ter-Doest Lastige. Zie wel mogelijkheden voor me, maar allemaal niet echt optimaal.

> Dat gaat natuurlijk veel vaker spelen, in allerlei combinaties. Vergt m.i. een generieke aanpak die per geval (zoekvraag) verbijzonderd wordt. Wellicht hiervan een apart issue maken, om die generieke aanpak te bepalen?

Eens!

Denk dat er 2 relevante vragen zijn:

1) Waar slaan we relaties op? Discussie deels gevoerd in #166 en afgelopen maandag.
2) Hoe kunnen we over relaties, binnen en buiten componenten, heen zoeken?

**Comment by TCIMEddy** [comment]
@jgortmaker1 @ArjanKloosterboer Kunnen jullie akkoord geven op review (met eventueel opmerkingen/nieuwe issues uiteraard)

**Comment by ArjanKloosterboer** [comment]
Ik heb gereageerd op de rgbz-mapping. Als je daar nog naar kijkt dan kan ik akkoord geven.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Is het commentaar van Arjan verwerkt/beantwoord?

**Comment by Hugo-ter-Doest** [comment]
Yep heb ik verwerkt.

**Comment by jgortmaker1** [comment]
nog te bekijken in het licht van #396

**Comment by jgortmaker1** [comment]
in navolging op mijn vorige opm: in de RGBZ mapping is naast ZAAK netjes sprake van MELDING. lijkt me dus in orde.

**Comment by Hugo-ter-Doest** [comment]
Volgens mij is deze dan ready for sprint.

**Comment by TCIMEddy** [comment]
@joeribekker Kan dit? Zo ja close

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Wat te doen?

**Comment by sergei-maertens** [comment]
Zie #957

**Comment by Hugo-ter-Doest** [comment]
In het nieuwe gegevenslandschap moet je starten bij de meldingen. Die hebben immers locatie. Als je de meldingen hebt gevonden, kun je de zaken erbij zoeken en ook de contactmomenten.
