### ISSUE TITLE
Als gemeente wil ik automatisch relevante (zaak)informatie kunnen afnemen bij een ketenpartij (bijvoorbeeld DSO) en verwerken binnen de eigen zaakomgeving

### ISSUE THREAD

**Issue by RvdKlip** [VNG-Realisatie/gemma-zaken#120]
...zodat ik alle relevante zaken binnen de eigen zaakomgeving inzichtelijk heb, kan afhandelen en het resultaat automatisch kan terugkoppelen.

**Definition of done**
- [ ] er is een herbruikbaar aansluitpatroon (voor het actief ophalen en verwerken van gegevens bij ketenpartijen)
- [ ] er is een OAS 3.0 specificatie (? kan ik niet beoordelen of dit hier nodig is ?), afgestemd met leveranciers van ZRC/e-Suite
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie 
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
- [ ] Voldoet aan ZDS 2.0

Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_VNG_]
- [ ] Aanleveren testdata [_VNG_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by jgortmaker1** [comment]
kun je deze concreter maken, liefst met een niet DSO-voorbeeld (omdat daar alles complexer is)?

Deze gaat over zaakgericht samenwerken en daarmee op zich een waardevolle US. Maar "automatisch relevante (zaak)informatie kunnen afnemen bij een ketenpartij (bijvoorbeeld DSO) en verwerken binnen de eigen zaakomgeving" is te abstract voor mij.

**Comment by Hugo-ter-Doest** [comment]
Is buiten scope voor ZGW. Dit kan in de ZAC worden gerealiseerd door te koppelen met STAM.
