### ISSUE TITLE
Als beheerder van de standaard ZDS wil ik dat de opgeleverde API aan een openbare consultatie is onderworpen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#121]
...zodat de nieuwe standaard ook voldoet aan de eisen die door het Forum Standaardisatie gesteld worden.

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] er is functionele documentatie conform het DSO-patroon
- [ ] de DSO URI- en API-strategie worden gevolgd
- [ ] Er is aantoonbaar een openbare consultatie geweest waar iedereen (niet alleen de genodigden van de sprint demo's) op heeft kunnen reageren.

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Uitschrijven van een OC [_verantwoordelijke_]
- [ ] Verwerken reacties op OC [_verantwoordelijke_]
- [ ] Terugkoppelen verwerkte reacties op OC [_verantwoordelijke_]
- [ ] Wijzigingen implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Aanpassen van OAS 3.0 [@michielverhoef]
- [ ] Functionele documentatie [@michielverhoef]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [@michielverhoef]

**Comment by TCIMEddy** [comment]
@michielverhoef Wellicht voor iedereen duidelijk maar wat bedoel je met openbare consultatie

**Comment by michielverhoef** [comment]
Voordat de API een standaard kan worden moet aan een aantal eisen worden voldaan. Dingen als beheer, waar kan ik als gemeente of leverancier bij vragen of problemen terecht etc. moeten worden geregeld. Dit mag best in een community gebeuren maar hiervoor moet dan een omgeving zijn en dit moet bekend gemaakt zijn.

Daarnaast moet de standaard door belanghebbenden (gemeenten, leveranciers) in zijn geheel worden beoordeeld. Tijdens de sprint demo's kijken we naar wat er tijdens een specifieke sprint is opgeleverd maar niet of minder naar het grote geheel. Bij een openbare consultatie gebeurt dit wel.  Met de sprint demo's wordt elk deel van de standaard al beoordeeld dus een openbare consultatie zou geen verrassingen moeten opleveren. Eigenlijk zou je de openbare consultatie als een soort super-sprint demo kunnen zien waarbij men het werk van het gehele project doorneemt.

**Comment by Hugo-ter-Doest** [comment]
Buiten scope van het project. Kan worden georganiseerd vanuit het beheerteam.

**Comment by michielverhoef** [comment]
Volgens mij is een openbare consultatie nou juist de laatste stap voordat een standaard naar beheer gaat? Overgaan van een standaard van ontwikkeling naar beheer is het moment waarop de standaard een release candidate wordt.

Misschien dat een openbare consultatie vervangen kan worden door een aantal proefimplementaties, dat zou kunnen. 
Weet iemand hoe dit gebeurt bij bijvoorbeeld het W3C?

**Comment by Hugo-ter-Doest** [comment]
Ja, dat is prima, maar wordt niet vanuit dit project georganiseerd.

**Comment by michielverhoef** [comment]
Daar moeten de respectievelijke PO's het maar eens onderling over hebben maar ik denk wel dat een bepaalde toetsing plaatsgevonden moet hebben voordat de standaard het niveau heeft dat we kunnen spreken van een release candidate  (is dat hetzelfde als een recommendation zoals W3C dat hanteert?) die in beheer genomen kan worden.

**Comment by melsk-r** [comment]
@Hugo-ter-Doest Hier moeten we het inderdaad wel even over hebben. Beheer neemt nl. alleen standaarden in beheer. De ZDS candidate standaard(en) zullen dus een stap moeten doorlopen waardoor ze verheven worden tot standaard. Als jullie die stap niet opnemen in jullie proces dan vallen deze 'standaarden' tussen wal en schip. Voor jullie zijn ze afgehandeld maar wij kunnen ze nog niet in beheer nemen.

Afgelopen maandag gaf je al aan dat je een overleg wil met alle PO's. Dit lijkt me een heel mooi onderwerp daarvoor.
Ik zou zeggen heropen tot die tijd nog even dit issue en geef het even een andere status.

**Comment by TCIMEddy** [comment]
En prio (desnoods L of M)

**Comment by Hugo-ter-Doest** [comment]
Geef nog geen prio omdat ik niet weet of team iets moet doen. Wacht het PO-overleg even af.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest volgens mij is hier al een beslissing over genomen (impliciet wellicht). Zo ja close

**Comment by TCIMEddy** [comment]
In overleg met Hugo close -> openbare consultatie doen we niet in oude vorm maar in API-Lab
