### ISSUE TITLE
Als gemeente wil ik klantcontacten kunnen registreren die niet of nog niet aan een zaak zijn gekoppeld

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1223]
...zodat ik ook niet zaakgerichte contacten kan registreren.

Toelichting:
Dit betekent dat het zaak attribuut niet verplicht moet zijn.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by adgerrits** [comment]
Moet 'Dit betekent dat het zaak attribuut niet verplicht moet zijn.' niet zijn: 'Dit betekent dat de foreign key die naar een gerelateerd systeem en 'zaak' verwijst niet verplicht is en verschillende vormen kan aannemen.'

**Comment by Hugo-ter-Doest** [comment]
nee, we hebben niet over databases. Het gaat gewoon om het attribuut zaak.

**Comment by adgerrits** [comment]
"..zodat ik ook niet zaakgerichte contacten kan registreren" kan toch betekenen dat er van een andere registratie dan een ZRC gebruik wordt gemaakt? Wel zo handig als dan ook sleutelgegevens zijn op te nemen het beherende systeem niet zelf een index van opgeslagen klantcontacten hoeft bij te houden.

**Comment by Hugo-ter-Doest** [comment]
> Sleutelgegevens van het beherende systeem

Het contact heeft zelf een URI waarmee duidelijk is waar het contact leeft.

**Comment by joeribekker** [comment]
> "..zodat ik ook niet zaakgerichte contacten kan registreren" kan toch betekenen dat er van een andere registratie dan een ZRC gebruik wordt gemaakt?

Hierover ben ik het wel eens met @adgerrits Ik wil niet dat het ZRC ad-hoc wordt gebruikt als Contacten API. Die opening geven we hiermee wel.

Is dit niet de reden van #1225 ? Of haal ik zaken door elkaar?

**Comment by Hugo-ter-Doest** [comment]
> Ik wil niet dat het ZRC ad-hoc wordt gebruikt als Contacten API. Die opening geven we hiermee wel.

@Joeri Hier ben ik het mee eens. Dat betekent dat we deze user story niet moeten realiseren. En dat als we klantcontacten buiten ZGW willen ondersteunen, er een separate API moet komen.
