### ISSUE TITLE
Als  gemeente wil ik een bestaand klantcontact kunnen koppelen aan een zaak

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#1224]
...zodat een reeds bestaand contact aan de relevante zaak kan worden gekoppeld.

Toelichting:
De relatie met de zaak is in #1223 optioneel geworden. Met de onderhavige user story wordt het vervolgens mogelijk om de relatie met een zaak later te leggen.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by adgerrits** [comment]
Wordt, gelet op '..zodat contactregistratie niet meer onderdeel is van de Zaken API en contactregistratie onafhankelijk van de Zaken API kan worden gebouwd en uitgerold', het koppelen aan 'een zaak' die niet via de Zaken API is vastgelegd (ook) ondersteund? Bijv. 'zaken' die alleen in een taakgerichte applicatie zijn vastgelegd? - Betekent o.a. dat de contactregistratie dan 'sleutel-neutraal' moet worden.

**Comment by sergei-maertens** [comment]
Lees ik dit goed als: ik moet het klantcontact kunnen bijwerken om de zaakverwijzing toe te voegen?

**Comment by Hugo-ter-Doest** [comment]
Ja

**Comment by joeribekker** [comment]
Wordt klantcontact hiermee geen ad-hoc informatie bij een Zaak maar een "echt" object die naar meerdere zaken kan verwijzen?

**Comment by michielverhoef** [comment]
Dat wordt dan een ZaakKlantcontact relatieklasse? Vergelijkbaar met een ZaakInformatieobject of BesluitInformatieobject.

**Comment by adgerrits** [comment]
Zie ook #1225 waar dit m.i. een onderdeel van is (en er een M:N relatie tussen Contactmoment en Zaak zou moeten zijn...).

**Comment by Hugo-ter-Doest** [comment]
Dit moet onderdeel worden van een separate Contacten API. Het is niet handig om de contacten resource die in de ZRC zit generiek bruikbaar te maken.
