### ISSUE TITLE
Als VNG Realisatie wil ik bepalen hoe we verder kunnen met ZGW API's vanaf 2020

### ISSUE THREAD

**Issue by PDG65** [VNG-Realisatie/gemma-zaken#1452]
**zodat** gebruik van de standaard door markt maximaal is en kosten voor VNG Realisatie minimaal
**met aandacht voor** Agile werkwijze, rol & organisatie VNG Realisatie, Gebruikers Community

**Comment by PDG65** [comment]
Verslag van de eerste sessie (11-11-2019):
### **In beheer name**
•	_Op welke wijze moeten we dit in beheer nemen?_ 

- [ ] Voldoet de ‘ouderwetse’ wijze van in beheer nemen? 
- [ ] Voldoet het huidige organisatiemodel van VNG daarvoor? 
- [ ] Zou het niet op een DevOps wijze in beheer moeten worden genomen met het bijbehorende budget?

•	_Andere vragen die spelen_

- [ ] Wat is de rol van de club ‘Toepassen en bevorderen gebruik’?
- [ ] Als je de doorontwikkeling niet Agile inricht, levert dat niet het risico op dat je bepaalde capaciteit niet kunt krijgen op het moment dat je het nodig hebt?
- [ ] Is ‘in beheer nemen’ voldoende om eventuele adoptie uit de markt te stimuleren?
- [ ] Is ‘in beheer nemen’ voldoende om eventuele adoptie uit de markt te ondersteunen?
- [ ] Hoe kunnen we adoptie van de standaarden bij de leveranciers bevorderen?
- [ ] Is het een idee om daarvoor de dialoog met de business managers te zoeken?

### **Doorontwikkeling**
•	De standaard is voor en door gemeenten. Hoe zijn gemeenten betrokken in het beheer na 1 januari? Hoe gaan we borgen dat gemeenten actief betrokken zijn bij de standaard en hoe gaan we hen actief betrekken bij het bepalen van de oplossingsrichtingen?
•	Als het meer gaat leven (dus partijen gaan zelf pull requests indienen) ben je dan in staat om dat te ondersteunen. Kunnen we snel genoeg inspelen op de vraag?
•	Wat wordt de rol van de VNG als er door andere partijen/communities standaarden worden opgeleverd?
•	Welke lessen hebben wij het afgelopen jaar geleerd;
•	Inzetten op Common Ground betekent dat er meer API standaarden ontwikkeld moeten worden voor het gemeentelijk gegevenslandschap. Deze kunnen onmogelijk vanuit VNG-R gerealiseerd worden. Hoe kunnen deze wel gerealiseerd worden?
•	_Welke scenario’s zijn er?_

- [ ] Scrum team in huidige vorm handhaven;
- [ ] Alleen bug fixing;
- [ ] Beperkt doorontwikkelen; risico is dan dat andere trajecten (bijv. GemeenteZaak) voor gaat lopen op de standaard en de VNG de standaard gaat doorontwikkelen op basis van PR’s vanuit die trajecten.
- [ ] Doorontwikkelen op basis van adoptie;
- [ ] Community rondom GemeenteZaak gaat de doorontwikkeling van de standaarden faciliteren.
- [ ] Gaat dan buiten de VNG om;
- [ ] Ontwikkelen standaarden door andere partijen waarna VNG er alleen maar een stempel op hoeft te zetten.

**Comment by PDG65** [comment]
Beknopt verslag van Sessie 18-11-2019:

**Algemeen**
We bespreken 3 onderwerpen met de volgende prio:
1. Doorontwikkeling
2. Toepassing en gebruik
3. Governance
De tot nu toe gehanteerde term In Beheer Name is geen goede term. Het team heet Bevorderen Toepassing en Gebruik. Dat vergt een meer proactieve houding. 

**Doorontwikkeling**
Doorontwikkeling vergt betrokkenheid van de gemeenten (en in het verlengde daarvan leveranciers). Daarbij zijn transparantie en voorspelbaarheid (roadmapping) key elementen.
Invulling vergt een productowner en een DevOps team (voor alle API's). Daar zijn middelen voor nodig en die zijn er nu (nog) niet. 
API-labs zijn een goed middel om de doorontwikkeling van de APIs’  met de markt te toetsen.

**Toepassing en gebruik**
De vraagkant moet geregeld worden (gebruikerscommunity met ambassadeurs) vanuit een afgestemde visie (productowner), waarbij kwaliteit wordt bewaakt middels architectuur. 
Het toepassen en het gebruik van de API's door de markt vervolgens meetbaar maken, zodat daar op gestuurd kan worden.  
Voor het gebruik is 1e lijns support nodig. Het beschikbaar stellen van documentatie is een issue (op VNG site) en brengt de tegenstellingen tussen de nieuwe manier van werken en de huidige organisatie van VNG aan het licht.

**Volgende sessie** 
25-11 om 10:30. Focus op invulling 2020 (hoe verder in januari)

**Comment by PDG65** [comment]
Verslag sessie 25-11 

**Doorontwikkeling**
Er is een gesprek geweest met Theo, Hugo, Jeffrey, Rita, Constantijn. 
Resultaat is dat er en afspraak ligt om  een aantal scenario’s uit te werken m.b.t invulling 2020. Doorontwikkeling is onderdeel van 2020. Aantal opties:
•	Team gaat door als DevOps
•	Team wordt weer opgebouwd zodra er voldoende backlog is en bijbehorende financiering. Nadeel: waste omdat team weer in flow moet komen (paar sprints nodig)
•	“Haal Centraal” variant (API’s los van Referentie-implementatie). Nadeel: blijkt geen optimale situatie in praktijk omdat je dan niet aan DoD voldoet en niet direct waarde levert.
•	Synthese van huidige werkwijze en “Haal Centraal” variant. Impact onbekend.
•	…?

**Governance**
Aanpassing van  de organisatie van VNG Realisatie om deze Agile te laten werken maakt geen onderdeel uit van de scope van deze reeks gesprekken. Wel ZGW en hoe nu verder.

**Invulling 2020**
Er komt een in 2020 Q1 (feb/mrt) fieldlab om inzichtelijk te krijgen waar de behoeften van de gemeenten m.b.t. het gegevenslandschap. Op basis daarvan kan mogelijk aanvullende financiering plaatsvinden. 

Wat is er 2 januari nodig:

_Uitgangspunten_
-	Overdracht hangt af van scenario wat gekozen wordt; we gaan er van uit dat deze keuze per 2 jan nog niet operationeel is
-	Er komt een strippenkaart voor inzet Maykin Media aangevuld met inzet Hugo als PO

_Lijstje van Robert_
-	Uit welke componenten bestaat het totaalplaatje
-	Kennisvragen (hoe werkt iets en wat moeten we zelf kunnen)
o	Generatie versie
o	Verwijderen versie
o	Genereren docker containers
o	Creatie changelog
o	Uitrol naar vng.cloud
-	Hoe verhoudt zich dit naar het beheer van de andere API’s (uniformiteit)

_Acties_
-	Kennisoverdracht vanuit Maykin Media naar Beheer: Meenemen in laatste sprint 2019
-	Invulling rol Edwin vanuit VNG Realisatie (informatiemodel onderhouden): Afspraak tussen Edwin en Paul Fisscher om dit te bespreken
-	Oplossen issue beschikbaar stellen documentatie op VNG site (hoeft niet perse per 2 jan, maar zou wel mooi zijn ): Bepalen welke acties we moeten doen om een minimaal acceptabel resultaat te bieden (afstemming tussen Ivo, Robert en Communicatie nodig)
-	Communicatie richting en met stakeholders (m.n. gemeenten) inregelen. Er is behoefte aan een bredere groep ambassadeurs (nu Utrecht en Delft). Middelen om deze groep te vergroten:
o	Regelmatig een webinar richting Gemeenten (niet zo technisch als nu)
o	Ervoor zorgen dat meer gemeenten gebruik gaan maken van de API’s (b.v. via Gemeentezaak, gemeenten die zelf API’s hebben gemaakt)
o	De juiste implementatiestrategieën toepassen (dwingend, educatief, faciliterend, stimulerend etc)

**Volgende sessie** 
Datum/tijd: 2 dec 11:00-11:30. 
Onderwerp: voortgang/backlog en indien mogelijk scenario’s

**Comment by PDG65** [comment]
nog 1 sessie van een half uur op 2 dec met mogelijk wat nazorgacties

**Comment by PDG65** [comment]
Verslag sessie: 2 dec
Onderwerpen: voortgang/backlog en scenario’s

**Voortgang/backlog**
Huidige sprint richt zich op Verzoeken. In sprint is het MWP voor Verzoeken opgenomen.
Het volgende staat nog open:
- klantcontacten: 10 open
- verzoeken: 10 open
- archiefbeheer: 26 open
- notificaties: 3 open (er is volgende week nog een gesprek met Den Bosch gepland)
- zoeken: 4 open
- documentatie: 19 open
- convenience: 8 open (doorontwikkeling vanuit praktijk)
zie verder bord Voorbereiding mn prio H en ZH.
De backlog vergt een herprioritering omdat er veel zaken op staan die we bewust nog niet hebben opgepakt vanwege prioriteit voor andere zaken.

De huidige 1.0 versie is een werkbare sessie. Dit betekent niet dat het af is. Met deze versie kunnen leveranciers wel aan de slag.

**Scenario's**
Zijn nog niet vastgesteld. Dit loopt nog. Moet voor eind 2019 klaar zijn. Doel om dit volgende week te bespreken. Constatijn wil graag bijdragen aan de scenario's. 
Migratie-ondersteuning hierbij ook meenemen.

**Communicatie stakeholders**
Communicatie naar stakeholders is in gang gezet.
Interview met SudWest Friesland is in de maak. Strekking: we zijn blij, gemeenten ga er mee aan slag.

**Community**
Insteek: groep gemeenten in de lead voor de prioritering ondersteund door PO. Geen Leveranciers.
Standaard moet voor en door gemeenten blijven. De vraag moet daar vandaan komen. Per Epic organiseren.
_Wie moeten daar in zittten?_
Gemeenten die er concreet mee aan de slag zijn/gaan (dit kan dus wisselen per thema) en zowel grote als middelgrote als kleine gemeenten. Belangrijk is dat ze constant betrokken zijn. Aspect wat daarbij speelt is dat Gemeenten zich vaak laten leiden door hun leveranciers. Dus ook gemeenten met verschillende leveranciers.
Start met kerngroep (5/6 gemeenten). Kandidaten: Utrecht, Delft, Sudwest Friesland, aangevuld met Dimpact gemeente, ....
Laten zien dat we gemeenten betrekken en zorg dat ze gezamenlijke relevante onderwerpen kunnen bespreken. Dat vraagt effort.

**Volgende sessie**
9 december van 13:00 tot 14:00
Onderwerp: Scenario's, community, integraliteit

**Comment by PDG65** [comment]
Verslag sessie 9 dec

Jeffrey neemt met het team een presentatie door over de doelen en invulling team in 2020. **Uitgangspunten**:
- focus in 2020 richt zich op implementatie en adoptie van de standaard door gemeenten en leveranciers. Daar zijn KPI's voor opgesteld
- team gaat in een wat gewijzigde opstelling door en zodat de doorontwikkeling van ZGW API's wordt veiliggesteld. 

**Belangrijkste aanpassingen in team**:
- toevoeging communitymanager/implementatieondersteuner aan het team
- expliciete aandacht voor communicatie richting doelgroepen (m.n. documentatie)
- overgang van Scrum naar een vorm van "DevOps"

**Aandachtspunten**
- invulling rol informatieanalist/architect/"documentalist"
- behoud van teamflow
- behoud van agility

**Comment by Hugo-ter-Doest** [comment]
Dit zijn oude achterhaalde "gesprekken" over de werkwijze en aanpak van de API's. Er wordt nu door VNG een plan ontwikkeld voor API's in brede zin.
