### ISSUE TITLE
Als ontwikkelaar wil ik weten hoe ik met ZDS 2.0 kan starten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#187]
...zodat ik er mee aan de slag kan.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _~~Userstory is ingevuld op template architectuurschets~~_
- [x] _~~Userstory is voorzien van veldmapping naar RGBZ2~~_
- [ ] _~~Userstory past op wenselijk gebruik ZGW volgens GEMMA 2~~_
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Acceptatiecriteria**
- [x] Een developer buiten ons scrum team moet het werkbaar vinden
- [x] Disclaimer erbij.

**DoD**
- [x] Documentatie is gepubliceerd
- [x] Het resultaat is actief gecommuniceerd

**Taken**
- [x] Documentatie hub opzetten met verwijzingen naar verschillende componenten
- [x] Een link naar uitleg over REST
- [x] Generieke informatie over globale opzet (specificatie, referentie component, testen, en downloaden)

**Taken per component**:
- [ ] Uitleg over het component

**Comment by joeribekker** [comment]
@RvdKlip Kan jij deze nog aanvullen aangezien jij dit ticket aandroeg?

**Comment by michielverhoef** [comment]
Is dit vanuit de vakapplicatie (client) gezien of vanuit het implementeren/inbouwen in een ZRC?
Dat zijn 2 verschillende soorten "aan de slag gaan".

**Comment by joeribekker** [comment]
Beide :)

Ik heb er 2 kopjes over opgenomen:

* Communiceren met dit component (client)
* Zelf dit component implementeren (server)

Zie: https://ref.tst.vng.cloud/developers/zrc/
Bron: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/developers/zrc.md

**Comment by TCIMEddy** [comment]
@HenriKorver Graag ready maken
