### ISSUE TITLE
Als projectlid wil ik functionele documentatie per API

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#188]
...zodat duidelijk is welke functionaliteit ondersteund wordt door de API

**Definition of done**

- [x] er is een framework-pagina voor het beschrijven van functionele documentatie (gereed, zie PR #439)
- [ ] van elke API is er functionele documentatie tot deze sprint (deels gereed, zie PR #430)

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [x] Opstellen documentatie "frameworkpagina" [@michielverhoef]
- [ ] Opstellen functionele documentatie per API [@michielverhoef]

**Comment by michielverhoef** [comment]
Er zijn verschillende doelgroepen voor functionele documentatie. Bijvoorbeeld:
* gemeentemedewerkers die moeten kunnen beoordelen of een standaard van toepassing is en wat eventueel in een aanbesteding opgenomen moet worden, hoe dit gecontroleerd kan worden etc.
* Productmanagers die moeten kunnen bepalen of een standaard van toepassing op hun product en aan welke eisen de implementatie moet voldoen
* Ontwikkelaars die een beknopt overzicht willen van wat de API doet.

De eerste twee zullen vergelijkbare functionele documentatie willen, de ontwikkelaars kunnen waarschijnlijk met dezelfde documentatie uit de voeten (en wat ze niet nodig hebben lezen ze gewoon niet).

**Comment by michielverhoef** [comment]
Zoals net aangegeven bij de standup, ik ben nog steeds op zoek naar een bruikbaar formaat hoe functionele documentatie te schrijven voor de doelgroepen:

1. Architecten van gemeenten die moeten beoordelen of en zo ja welke standaarden van toepassing zijn en welke eisen in een aanbesteding etc. gesteld moeten worden, hoe gecontroleerd kan worden of een systeem aan een standaard voldoet etc.
2. Productmanagers van leveranciers die moeten beoordelen of en zo ja welke standaarden van toepassing zijn op hun product(en) en waar de informatie te vinden is hoe deze correct ingebouwd kan worden, welk toetsingsinstrument er is etc.
3. Ontwikkelaars die moeten weten waar een bepaalde functionaliteit voor dient, hoe deze gebruikt moet worden enz.

Bijgevoegd de nog niet helemaal-af versie van de nieuwe pagina voor GEMMA Online waarin de huidige ZDS 1.2 standaard beschreven wordt voor bovenstaande doelgroepen. 

Nu zoek ik dus naar een manier om zo'n soort beschrijving te maken voor de API's.  

[voorstel_nieuwe_paginaGEMMAONLINE.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2213141/voorstel_nieuwe_paginaGEMMAONLINE.docx)

**Comment by ArjanKloosterboer** [comment]
Puur als documentatie van een API denk ik aan de volgende tabel.

**API: [naam]**

_Aspect_ | _Beschrijving_
-- | --
Doel | [het doel van de API; waarin voorziet het, wat maakt het   mogelijk]
Client | [naam of soort van de component die de API aanroept of de   situatie waarin componenten deze API gebruiken]
Aanleiding | [wat is de reden of gebeurtenis dat een component (client)   van deze API gebruik wil maken]
Voorwaarde | [aan welke voorwaarden dient de client voldaan te hebben alvorens   de API te kunnen aanroepen; welke gegevens dienen beschikbaar te zijn]
Provider | [naam van de component die voorziet in de API]
Gevolg | [wat gebeurt er als gevolg van het aanroepen van de API]
Gegevens | [de objecten waarvan gegevens in de API betrokken zijn;   bij voorkeur een plaatje van het desbetreffende deel van het (domein)informatiemodel]
Specificaties | [link naar de plek waar de technische specificaties van de   API zijn te vinden]
Samenhang | [beschrijving van de samenhang met andere API’s,   bijvoorbeeld dat een andere API eerst uitgevoerd moet worden om gegevens te   verkrijgen waarmee deze API aangeroepen kan worden]
Bijzonderheden | [alles wat relevant kan zijn voor het duiden en toepassen   van de API]

**Comment by ArjanKloosterboer** [comment]
Wat er ook nog bijhoort is:
Domein: de benaming van het (sub)domein waarvoor de API bedoeld is (zoals 'Zaakgericht werken')].
Direct onder doel.

**Comment by ArjanKloosterboer** [comment]
Als ik het document bij #254 lees, dan zou het bovenstaande de documentatie per service moeten zijn. Het onderscheid API en service, daar ben ik (nog) niet bekend mee.

**Comment by michielverhoef** [comment]
Omdat dit nog geen pull request is heb ik even de mensen die naar bovenstaand zouden moeten kijken als assignee opgevoerd.

**Comment by joeribekker** [comment]
Prima opzetje. 2 puntjes:

> Om de API's gedetailleerder te beschrijven moet per resource een tabel als onderstaande ingevuld worden. Bij voorkeur zou ik dat laten doen door de ontwikkelaars van de referentie-implementatie, als onderdeel van de referentie-implementatie. Onderstaand voorbeeld is niet compleet of af maar ook hier op graag jullie commentaar.

Arjan's tabel was op basis van een API end dat leek mij prima. Ik denk dat het niet nodig is om het op basis van resources zo'n tabel op te stellen. Dat wordt dan heel veel copy/paste werk zonder echte meerwaarde (alleen het Objecttype is elke keer anders).

Denk dat op dit vlak de [API documentatie](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/introduction/documentatie.md#api-documentatie) voldoet: https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_create

> Om de acceptatie van een voorstel tot verbetering te versnellen is het belangrijk een zo compleet mogelijk voorstel in te dienen. Dit houdt in naast een functionele en/of technische beschrijving ook waar nodig een aangepaste OAS3 specificatie (.yaml bestand) en een refrerentie implementatie. 
> \- _[Word document](https://github.com/VNG-Realisatie/gemma-zaken/files/2315645/ZDS2.-.Koppelvlakbeschrijving.-.in.bewerking_188.docx)_

In theorie is dit inderdaad het beste. Maar, zoals je zelf al aangaf, denk ik ook dat dit in de praktijk niet wenselijk is. In welke taal een referentie implementatie ook geschreven wordt, je sluit altijd groepen uit die een andere taal gebruiken.

Ik denk dat we wel OAS3 aanpassingen mogen verwachten (programmeertaal onafhankelijk). Deze zouden we wel kunnen checken op conflicten of backwards incompatible changes, als eerste stap. Als zowel de OAS en de achterliggende gedachte door VNG wordt goedgekeurd kunnen ook de referentie implementaties aangepast worden.

**Comment by fsamwel** [comment]
Michiel noemde m.i. terecht de doelgroepen van de functionele specificaties:
- gemeentemedewerkers die moeten kunnen beoordelen of een standaard van toepassing is en wat eventueel in een aanbesteding opgenomen moet worden, hoe dit gecontroleerd kan worden etc.
- Productmanagers die moeten kunnen bepalen of een standaard van toepassing op hun product en aan welke eisen de implementatie moet voldoen
- Ontwikkelaars die een beknopt overzicht willen van wat de API doet.

Ik zie in de tabel met onderwerpen en in de documenten veel informatie staan die ik niet zo direct kan verbinden aan deze doelgroepen en hun behoeften aan informatie. De details van de API moeten m.i. dus niet in deze functionele documentatie, maar in de OAS3 specificaties.

Ik zou het tot 5 hoofdstukken beperken, en dit alles op koppelvlakniveau:
1. Architectuurvisie (of noem het inleiding, o.i.d.): doel, aanleiding, kaders
2. Bedrijfsarchitectuur: hoofdlijnen van de functionaliteit, bedrijfsprocessen, enz.
3. Informatie architectuur: referentie-componenten, inbedding in GEMMA, verwijzing naar technische specs (GitHub), enz. 
4. Technische architectuur: eisen m.b.t. beveiliging, autorisatie, NLX, overige non-functionals, enz.
5. Implementatie: beheer, implementatie-ondersteuning, verwijzing naar software catalogus, compliancy, enz.

Overige informatie over de API is denk ik alleen/vooral interessant voor developers en zou ik dus op GitHub publiceren, primair in de OAS3 specificaties. Zo nodig in OAS3 hyperlinks opnemen naar verdere functionele of technische API-specs op GitHub.

**Comment by ArjanKloosterboer** [comment]
De discussie is inmiddels uitgelopen op een impediment: #399, met een verwijzing naar een [voorstel voor documentatie](https://ref.tst.vng.cloud/introduction/documentatie/). Dit voorstel dekt m.i. een deel van de vijf punten in het voorgaande comment. Daar mogen anderen naar kijken, waar het mij in eerste instantie om gaat is zodanige documentatie van een API en  de bijbehorende Resources dat (mij) duidelijk is wat ze te bieden hebben. In reactie op dat voorstel en n.a.v. het voorafgaande de volgende opmerkingen.

Wat mij betreft prima indeling in soorten documentatie. Ik behoor alleen tot de doelgroep van de functionele documentatie dus kan over de andere soorten niet oordelen.

> De functionele documentatie van de API is bedoeld voor business developers, architecten, ontwerpers en ontwikkelaars

M.i. 'informatie-architecten' i.p.v 'architecten' en verder ook informatiemanagers, informatie-adviseurs, functioneel beheerders en technisch applicatiebeheerders. 

> wat de service doet

M..i. 'biedt' i.p.v. 'doet'. 

> Welke functionaliteit en/of welke data biedt de API?

Dit is m.i. de kern. En dan graag niet 'en/of' maar 'en'! En dan in twee bullets. En het niveau API is me te hoog, graag op resource-niveau. En dan bij voorkeur iets in de vorm van bovenstaande tabel. Wsl. dan op twee niveau's: dat wat voor alle API's hetzelfde is op API-niveau, wat specifiek is op resourceniveau per resource (bijvoorbeeld de einddatumZaak die wel raadpleegbaar maar niet muteerbaar is). Gaan we hier per resource specificeren welke gegevens er in zitten? Lijkt me kans op fouten geven. Kan per resource de link vermeld worden naar de desbetreffende resource in de API-documentatie? En is die API-documentatie dan zo inzichtelijk dat dat nog net functioneel leesbaar is? Zoiets valt wsl. nog net te begrijpen. Verwarrend is dan dan weer dat er niet één resource is maar een specificatie per operatie op een resource. Wat zijn de verschillen? Die zouden in de functionele documentatie geduid moeten worden. Is dan de 'get' maatgevend voor de gegevens van de resource? Fuctioneel zou dan volstaan kunnen worden met het benoemen van het objecttype en eventuele relaties. 

Het genoemde voorbeeld vond ik niet zo sterk, voorzichtig uitgedrukt. Mij geeft dat niet de gewenste informatie.

**Comment by joeribekker** [comment]
>> Welke functionaliteit en/of welke data biedt de API?

> Dit is m.i. de kern. En dan graag niet 'en/of' maar 'en'!

Als ik Arjan's comment zo lees, is functionele documentatie in zijn ogen vooral **hetzelfde** als de (API-specificatie](https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_read) maar dan leesbaar voor niet-techneuten.

> Gaan we hier per resource specificeren welke gegevens er in zitten? Lijkt me kans op fouten geven. Kan per resource de link vermeld worden naar de desbetreffende resource in de API-documentatie? En is die API-documentatie dan zo inzichtelijk dat dat nog net functioneel leesbaar is? [Zoiets](https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/zaak_read) valt wsl. nog net te begrijpen. Verwarrend is dan weer dat er niet één resource is maar een specificatie per operatie op een resource. Wat zijn de verschillen? Die zouden in de functionele documentatie geduid moeten worden.

Wellicht kunnen we een OAS converteren naar tabellen in de vorm van:

Attribuut|Omschrijving|Type|Verplicht|CRUD *
---|---|---|---|---
eindDatum|De datum waarop de uitvoering van de zaak afgerond is.|string <date>|nee|CRU~~D~~

\* Create, Read, Update, Delete

> Is dan de 'get' maatgevend voor de gegevens van de resource?

Yes.

>> De functionele documentatie van de API is bedoeld voor business developers, architecten, ontwerpers en ontwikkelaars

> M.i. 'informatie-architecten' i.p.v 'architecten' en verder ook informatiemanagers, informatie-adviseurs, functioneel beheerders en technisch applicatiebeheerders.

Laten we ontwikkelaars dan maar weg halen. Die hebben echt niets aan deze documentatie :)
Wat ik overigens prima vind! Ontwikkelaars hebben genoeg aan een OAS en Implementatie guide.

**Comment by joeribekker** [comment]
*Aantekeningen uit sessie met Arjan waar we een concrete API en resource hebben gepakt:*
We houden even het template aan van Michiel/Arjan. De doelgroep is vooral voor niet technische mensen.

**API: ZRC**
Doel: Het kunnen aanspreken van een voorziening voor het onderhouden en raadplegen van zaken en bijbehorende statussen.
Provider: ZRC-link naar Gemma
Client wordt consumer en komt hier te staan (ipv bij resource): De mogelijkheid tot onderhouden wordt vooral gebruikt door ZAC, diverse componenten zullen vooral raadplegen.
Specificaties: ZRC-link naar API ReDoc

Deze API bevat de volgende resources.
Elke resource hieronder biedt de mogelijkheid om de objecten toe te voegen, verwijderen, wijzigen en raadplegen, tenzij anders vermeld.

(tabel van Sergei)

**Resource: zaken**
Doel: vervalt
Aanleiding: Is dit nuttig? Nader te bepalen
Voorwaarden: 
* Een geldig Zaaktype is nodig (technisch afgedwongen middels validatie)
* Er moet minimaal 1 betrokkene zijn (maar dat kan niet technisch, dus hier moeten we wat mee – scenario’s beschrijven en/of )
Operaties: POST/PUT/GET/DELETE
POST: identificatie is optioneel. Wordt zelf aangemaakt als je hem niet mee geeft. Moet wel uniek zijn.
Zaaktype is verplicht. Het resultaat is een Zaak met een Zaaktype.
Gegevens: Tabelletje van Sergei

Bijzonderheden:

Scenario:
* Zaak aanmaken
* Zaak afsluiten
* Status zetten
* Zaaktype wijzigen: Zaak afsluiten nieuwe zaak openen, en relatie leggen

**Comment by ArjanKloosterboer** [comment]
Ik heb een en ander uitgewerkt in een documentje, vooralsnog als [GoogleDocs-document](https://docs.google.com/document/d/1iRy3wKbkgSdxVsuRuGqGTgxFIXDf9_NsEnR2PGfyMFk/edit#) (gaat me makkelijker af). Als we het daarover eens zijn, dan kan zowel het sjabloon als de documentatie per API als md-documenten vastgelegd worden.  
Wat ik niet weet is of hetgeen ik daarin beschrijf wellicht al ergens anders beschreven wordt. Ik ben benieuwd naar de reacties.

**Comment by HenriKorver** [comment]
> Wat ik niet weet is of hetgeen ik daarin beschrijf wellicht al ergens anders beschreven wordt. 

Ik zie wat overlap met document [standaard.md](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/standaard.md).

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer @joeribekker Dank voor jullie initiatief. A.s. maandag wellicht f-t-f aftikken!

**Comment by ArjanKloosterboer** [comment]
@HenriKorver, waar zit die overlap dan? Ik zie 'm niet. Ik ben op zoek naar wat resources kunnen en doen en dat tref ik in het door jou aangehaalde document niet aan. 
@TCIMEddy en anderen, voordat we dit kunnen aftikken zie ik graag reactie van deze en gene of we met dit voorstel op de goede weg zitten.  
Nb. wat is f-t-f? Ik ken wel w-t-f.

**Comment by HenriKorver** [comment]
@ArjanKloosterboer: in standaard.md zag ik zinnen staan zoals:
>Bij het aanmaken (zaak_create) en bijwerken (zaak_update en zaak_partial_update) MOET de URL-referentie naar het zaaktype gevalideerd worden op het bestaan. Indien het ophalen van het zaaktype niet (uiteindelijk) resulteert in een HTTP 200 status code, MOET het ZRC antwoorden met een HTTP 400 foutbericht.

Dit lijken een soort van extra functionele eisen voor de ZRC API die blijkbaar niet op het niveau van de OAS-specificatie afgedwongen kunnen worden.

**Comment by michielverhoef** [comment]
f-t-f is denk ik face-to-face. Oftewel irl (in real life) ;-)

**Comment by ArjanKloosterboer** [comment]
Verrassend, van die tekst in een  document getiteld standaard.md. Komt wat mij betreft hier volledig uit de lucht vallen. Wat is het doel van dit document?
Meer algemeen: waar specificeren en documenteren we wat? Hoe is onze documentatie opgebouwd? 
In het document [readme.md](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/README.md) staat een paragraaf over documentatie met als eerste zin "De volgende documenten beschrijven dit project". Het document standaard.md wordt hierin niet genoemd. Evenmin wordt gesproken over documentatie voor niet-techneuten. 
En dan is er nog een [readme.md](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/README.md), in de map docs. Eerste zin van dit document luidt "De documentatie website is het startpunt voor iedereen die iets wil gaan doen met GEMMA Zaken." Waar is die documentatiewebsite dan? En die documentatie? 
In de map [docs/content/developers](https://github.com/VNG-Realisatie/gemma-zaken/tree/master/docs/content/developers) bevinden zich oa. de documenten zrc.md, ztc.md en drc.md. Deze verwijzen ieder voor zich door naar de desbetreffende api-specificaties en referentie-implementatie. Geen documentatie dus, wel de specificaties. In mijn ogen vreemd dat dit per referentiecomponent gespecificeerd wordt terwijl we API's ontwikkelen. Waarom geen indeling naar API's? In dezelfde map lijkt het document API-specificaties overigens dezelfde inhoud te bevatten als die drie genoemde documenten, m.u.v. de doorverwijzing naar de referentie-implementatie. Hoe dan ook, dit is de 'developers'-map dus wellicht mag ik daar geen niet-techneuten-documentatie verwachten. 
In de map [docs/content/introduction](https://github.com/VNG-Realisatie/gemma-zaken/tree/master/docs/content/introduction) staat het document [documentatie.md](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/introduction/documentatie.md) dat evenwel (nog) geen API-documentatie bevat. En er staat een document _index.md dat dezelfde bedoeling lijkt te hebben als readme-documenten in andere mappen. Het bevat geen (functionele) documentatie. 
En dan hebben we nog de onvolprezen site https://ref.tst.vng.cloud/ met een, vermoed ik, samenstelling van meerdere - maar niet alle - hiervoor genoemde documenten. Met in het hoofdstuk 'Documentatie' onder de kop 'Functionele documentatie' ... (nog) geen functionele documentatie.
De vraag is dus niet alleen wat we functioneel willen beschrijven maar ook hoe de structuur van onze documentatie er uit ziet en hoe we die toegankelijk maken. M.i. zou de laatstgenoemde site hiervoor leidend moeten zijn. En van alle documenten op Github die niet in deze site voorkomen moeten we ons afvragen of die nog zin hebben. Zo komt de aanleiding voor deze comment, het document standaard.md daarin niet voor ...

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Ik mag me er inhoudelijk niet mee bemoeien maar het document op Google Docs geeft kort en bondig (ook voor de leek) weer wat de API' doet + belangrijke informatie

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer je raakt wel een aantal punten, maar m.i. zijn deze off-topic voor deze issue. Het document `standaard.md` is via pull-request toegevoegd en het is de bedoeling dat dit de 'papieren standaard' wordt. Omdat het nog erg work-in-progress is, wordt hier nog niet te veel ruchtbaarheid aan gegeven. Ik heb een aanzet gedaan hiervoor, het is aan de rest van het team om verbeteringen aan te dragen...

Je kan ook zien dat er een pull-request is die bedoeld is om de documentatie-infrastructuur te verbeteren door van Hugo naar Jekyll over te schakelen (andere tooling). Dat zou ons moeten helpen om de structuur beter te beheren.

Waar ik wel wat kriegelig van wordt, is dat er geschoten wordt op de slechte structuur (de structuur is slecht), maar er vervolgens geen user story komt om iemand dat te laten verbeteren, OF concrete bijdrages om verbeteringen door te voeren. Als iedereen allemaal ja zit te knikken dat er wat moet veranderen, maar niemand de verandering doorvoert, dan schiet het ook niet op.

**Comment by ArjanKloosterboer** [comment]
> Je kan ook zien dat er een pull-request is die bedoeld is om de documentatie-infrastructuur te verbeteren door van Hugo naar Jekyll over te schakelen (andere tooling).

Voor mij is dit abacadabra, kan ik - met alle respect - helemaal niets mee. Evenmin met de aangehaalde #360. Ik zoek naar een functionele insteek en dito documentatie.

> Waar ik wel wat kriegelig van wordt, is dat er geschoten wordt op de slechte structuur (de structuur is slecht), maar er vervolgens geen user story komt om iemand dat te laten verbeteren, OF concrete bijdrages om verbeteringen door te voeren. Als iedereen allemaal ja zit te knikken dat er wat moet veranderen, maar niemand de verandering doorvoert, dan schiet het ook niet op.

M.i. is deze userstory er op gericht verbetering te brengen. En heb ik al een concreet voorstel gedaan. Maar wie ben ik? We zullen wel eerst met z'n allen (of in ieder geval meer dan ik alleen) een opzet (van de structuur van de documentatie) moeten bepalen. Daarna kan iemand dat gaan doorvoeren. Dus @sergei-maertens, graag een reactie op mijn voorstel in genoemd Google-doc en wellicht heb je ook ideeen voor een betere structuur van functionele en technische documentatie en specificaties.

**Comment by michielverhoef** [comment]
Als ik het goed zie is de google-doc het document waar Joeri en Arjan twee weken terug aan gewerkt hebben. 

Wat zou kunnen is de resource per operatie (POST, GET, PUT, DELETE)  beschrijven. Dan kunnen de aanleiding, voorwaarden en gevolgen ook specifiek gemaakt worden voor elke operatie. 

Helemaal voor de verschillende zoekopdrachten zoals die in de ZTC api staan lijkt het me goed om deze apart te beschrijven. Dan weet degene die ze toe moet passen precies op welke manier elke opdracht gebruikt moet worden en waarvoor deze bedoeld is.

**Comment by HenriKorver** [comment]
Eens met Michiel, ik zou zelfs de functionaliteit nog specifieker beschrijven, namelijk per combinatie operatie en pad (wellicht bedoelt Michiel het ook zo):
![image](https://user-images.githubusercontent.com/37145898/46130033-90e9d200-c238-11e8-8a00-98d226af58c1.png)

In dat geval kunnen de aspecten `aanleiding`, `voorwaarde`, `gevolg`, `samenhang` en `bijzonderheden` worden vervangen door één stuk lopende tekst waarin de functionaliteit van de operatie beschreven wordt. Bijvoorbeeld bij GET-operaties zal veelal geen voorwaarde van toepassing zijn.
Dergelijke functionele beschrijvingen van de operaties kunnen volgens mij prima in de description-velden van de OAS-specificatie opgenomen worden. De aspecten `gegevens` en `specificaties` zijn dan niet meer nodig want die worden al beschreven in de OAS-specificatie.

**Comment by michielverhoef** [comment]
Inderdaad, dat was wat ik bedoelde en alvast een versie van aan het uitwerken ben voor de ZTC api.
Ik zou wel aanleiding, voorwaarde, gevolg, samenhang en bijzonderheden apart benoemen. Dat zoekt en vergelijkt makkelijker (wanneer gebruik je nou welke operatie/pad combinatie?)

**Comment by HenriKorver** [comment]
Nu ziet de functionele beschrijvingen van een zaak er zo uit:
![image](https://user-images.githubusercontent.com/37145898/46131522-29358600-c23c-11e8-94c7-b646d6adb318.png)

Je zou dat kunnen opsplitsen in aspecten als volgt:
![image](https://user-images.githubusercontent.com/37145898/46133621-40c33d80-c241-11e8-9878-d9d48f8d3753.png)
Persoonlijk vind ik een dergelijk formaat te veel keurslijf.

**Comment by michielverhoef** [comment]
Die beschrijving zou ik niet in de API opnemen maar in een "papieren standaard" bedoeld voor GEMMA Online ed.
NB. een standaard is een keurslijf, hoe strakker hoe beter ;-)

**Comment by HenriKorver** [comment]
Ik vind dat de functionele beschrijving van de operatie juist wel in de OAS-specificatie moet staan. OAS is de internationale standaard voor het documenteren van de functionaliteit van je API. Developers zullen alleen naar de OAS-specificatie kijken. En volgens REST geldt het principe developers first!

Er zijn allerlei gratis viewers en html-generatoren waardoor OAS prima leesbaar is voor niet-developers (architecten of informatiemodelleurs zoals Arjan).

**Comment by michielverhoef** [comment]
Dan gaan wij uit van verschillende doelgroepen. Wat mij betreft is de functionele documentatie met name bedoeld voor niet-techneuten, het gemiddelde functionele publiek van GEMMA Online (denk aan informatiemanagers/architecten van gemeenten, accountmanagers van leveranciers die willen weten welke standaard relevant is voor hun product etc.).  De ontwikkelaar redt zich prima met een OAS specificatie maar iemand die dit soort dingen niets zegt snapt daar weinig van, of die OAS specificatie nou opgeleukt is met een viewer of niet.

Developer first leidt mijns inziens niet tot het compleet uitsluiten van niet-ontwikkelaars in een API. Dat zou complete onzin zijn. Naast specificaties en documentatie zodanig vormgegeven dat leven van de ontwikkelaar zo makkelijk mogelijk gemaakt wordt (lees: geen standaard in PDF en een ingewikkelde zipfile met schema's die niet scherp zijn) is documentatie voor de niet-techneut minstens zo belangrijk en in ieder geval niet verboden.

**Comment by HenriKorver** [comment]
Het is prima dat andere doelgroepen naast de developers ook bediend worden. Heel goed zelfs. Dus daar zijn we het over eens. Alleen pleit ik ervoor om ook alle tekstuele functionele beschrijvingen (aanleiding, voorwaarde, gevolg, etc) opgenomen worden in de OAS-specificatie, liefst als lopende tekst, maar als jet het wilt opsplitsen in de genoemde aspecten kan ik daar meeleven. Dit is dan de complete normatieve specificatie waar alles op één plek is samengebracht in het formaat van een internationale standaard. Dat je vervolgens op basis van deze normatieve specificatie afgeleide documenten gaat maken voor verschillende doelgroepen is prima.

**Comment by michielverhoef** [comment]
Wat mij betreft is het geen probleem om functionele documentatie op te nemen in de OAS sepcificatie. Lopende tekst blijft toch moeilijker om te vergelijken, denk ik. Tenzij we daar een bepaald format voor aanhouden maar dan kun je net zo goed aspecten in een tabelvorm opnemen.

**Comment by ArjanKloosterboer** [comment]
We lijken het er over eens te zijn dat er functionele documentatie moet zijn. Dat is alvast winst. Punt van discussie is blijkbaar nog **hoe** en **waar** we die opschrijven. Voor mij als non-developer-therefore-second but nevertheless-primary-stakeholder is het van belang dat het leesbaar en begrijpelijk is, een structuur heeft waarin het gezochte eenvoudig te vinden is en dat de documentatie an sich eenvoudig te vinden is. 'OAS-specificatie' zegt me helemaal niets. Als dat voor non-developers toegankelijk gemaakt kan worden, dan zijn we alweer een stap verder. Vanuit oogpunt van lees- en begrijpbaarheid heb ik een voorkeur voor een tabelachtige opsomming en niet 'een lap tekst'.

**Comment by ArjanKloosterboer** [comment]
Ik zit nog even te kijken naar [dit comment](https://github.com/VNG-Realisatie/gemma-zaken/issues/188#issuecomment-425009448). Dat geeft potentieel weer een probleem. De documentatie is hier op technisch niveau verwoord ('de url naar het zaaktype moet geldig zijn'). Vanuit functioneel oogpunt denk ik dan 'huh? hoezo?' Functioneel omschrijven we dit als 'Het zaaktype van de zaak moet aanwezig en geldig zijn (resource: zaaktypen in API: ZTC).' Da's nogal een verschil.
Hebben we het wel over dezelfde soort documentatie?

**Comment by joeribekker** [comment]
Uff, dit duurt maar voort.

zullen we afspreken dat Sergei en ik ons ontfermen over technische documentatie (=OAS en API guide) ? Dit betekent dat wij dit schrijven, opleveren EN het laatste woord er over hebben.

Dan laten we Arjan en Michiel dit doen voor de niet-technische doelgroep (=functionele docs als RGBZ  oud en Gemmaonline docs oid) met dezelfde voorwaarden (schrijven, opleveren en laatste woord).

We zitten te veel in elkaars vaarwater en er komt niets. Laten we beginnen! Jammer als er overlap is maar dan kunnen we later combineren als dat nodig is. Als er technische versie conflicteert met functionele versie, dan moeten we over die punten in discussie en meer niet.

Ik ga me voorlopig niet meer bezig houden met functionele docs tenzij iemand er om vraagt.

Let's go.

**Comment by sergei-maertens** [comment]
Ik denk dat je nog steeds niet helemaal comfortabel met het REST-api concept bent. Je moet het meer zien als bouwblokken, en de functionele documentatie beschrijft dan in welke volgorde je die blokken op elkaar stapelt.

Ik denk dat we het tot nu best aardig gedaan hebben om userstories om te zetten naar API calls, omdat je ook daar een logische volgorde hebt i.v.m. databaserelaties en referenties - iets moet bestaan voor je ernaar kan refereren.

Technisch doen we inputvalidatie, en daarmee maken we ook garanties op wat 'illegale volgordes' zouden zijn.

Verder wat betreft functionele documentatie - wij stellen vragen aan de deskundigen als we meer context nodig hebben van architectuur of RGBZ, ik denk dat dit prima in omgekeerde richting kan. Mensen die functionele documentatie schrijven kunnen prima de techniek vragen of iets wel klopt of zinvol is bekeken vanuit de techniek.

Het blijft zo dat wij niet weten wat je verwacht van de functionele docs, en we komen er maar niet uit, dus om ons een aanzet te laten doen hierop lijkt mij gezien de drukte met techniek niet wenselijk.

**Comment by ehotting** [comment]
![screen shot 2018-10-02 at 11 34 29](https://user-images.githubusercontent.com/20684884/46340938-3b963200-c637-11e8-91d1-12b0f64d3fd9.png)

Deze voorzet van @ArjanKloosterboer is precies wat we nodig hebben als functionele context bij een API. Daarmee kan iedereen die niet-developer is duiden of hij/zij een developer op het spoor van deze standaard moet zetten. Voor het overige is de doelgroep van deze standaard de ontwikkelaar.

Dus, deze user story kunnen we afronden door het tabelletje zoals @ArjanKloosterboer dat op 2 augustus voorstelde in te vullen.

Eventuele dubbelingen in documentatie pakken we later op, we hebben nog geen versie 1 opgeleverd.

**Comment by ehotting** [comment]
Hier geen nieuwe discussies over starten.

**Comment by ArjanKloosterboer** [comment]
@michielverhoef Even overleggen hoe we documentatie completeren voor de tot en met sprint 4 gerealiseerde resources.

**Comment by michielverhoef** [comment]
De functionele documentatie van wat er tot nog toe gerealiseerd is (in de verschillende referentiecomponenten) staat open ter review. Als het goed is staan ook de laatste wijzigingen nav opmerkingen van Arjan in de laatste versies van de pullrequests, mocht dat niet zo zijn, hoe krijg ik dat dan wel in orde?

**Comment by sergei-maertens** [comment]
Ik zie netjes verschillende commits, dus lijkt me prima te gaan :+1:

**Comment by michielverhoef** [comment]
Dit issue kan inderdaad gesloten worden
