### ISSUE TITLE
Als gemeente wil ik dat burgers alleen hun eigen documenten, zaken en gegevens kunnen zien

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#261]
...zodat ze nooit "per ongeluk" door anderen opgevraagd *kunnen* worden.

Dit is een verdieping van #153 en #154 waar de focus "filteren" op BSN door de consumer betreft. Deze user story betreft een stuk authenticatie/authorisatie, bijv. dat een burger zich identificeerd bij de ZRC API en dat het onmogelijk is om andere zaken te zien dan die van hem/haar/het zelf.

Belangrijkste hierbij is de vraag: Willen we bovenstaande uberhaupt?

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Hoe verhoudt dit zich tot een concept als DigiD Machtigen, waarmee je iemand kunt machtigen om voor jou bepaalde zaken af te handelen?

Kan het niet een optioneel filter zijn?

**Comment by ehotting** [comment]
Wat mij betreft geen autorisatie van burger rechtstreeks naar de API, daarvoor is delegation etc. nodig. Burgern krijgt autorisatie van de dienst waarmee wordt gecommuniceerd, bijv. MijnGemeente portaal. Deze portaal communiceert met autorisatie gemeente met achterliggende API, en geeft filters mee gedefinieerd door de functionaliteit van het portaal.

Los daarvan kan deze user story wel uitgevoerd worden. Verandert hiermee bedoeling van user story, @joeribekker ?

**Comment by joeribekker** [comment]
Filteren op BSN kan overigens via https://ref.tst.vng.cloud/zrc/api/v1/schema/#operation/rol_list

Zaken filteren op rollen, waarbij betrokkene=url, type=nps en roltype=initiator
waarbij de betrokkene url een url is van een persoon die gevonden is door te filteren op bsn.

**Comment by joeribekker** [comment]
Enige punt(je) is dat er nog geen BRP API is waar we naar kunnen verwijzen :)
