### ISSUE TITLE
checklist maken voor demo

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#271]
op basis van feedback team.

In de onderstaande checklist zijn alle zaken opgenomen die 'ooit' een keer voorbij zijn gekomen. Opnemen in iedere user story die betrekking heeft op demo.

**Checklist Demo**
- [ ] alle stakeholders uitgenodigd
- [ ] juiste stakeholders uitgenodigd
- [ ] lunch geregeld
- [ ] voldoende stoelen in zaal
- [ ] geen geluidoverlast
- [ ] 2 schermen
- [ ] 1 powerpoint/presentatie (samengevoegd)
- [ ] beamer aanwezig
- [ ] flipover aanwezig
- [ ] kabels aanwezig om laptops (ook Apple!) aan te sluiten
- [ ] wie schrijft mee (met name feedback en acties)
- [ ] bevat demo mix van kennisoverdracht en daadwerkelijk demonstreren
- [ ] context geschetst
- [ ] 'show and shine'-element
- [ ] is demo goede weergave wat er in de sprints is gedaan (of niet gedaan)

**Comment by TCIMEddy** [comment]
Checklist toegevoegd en dus done
