### ISSUE TITLE
Als deskundige wil ik mijn bevindingen die ik heb toegevoegd aan het inzageverzoek kunnen inzien en bewerken

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#307]
...zodat ik kan waarborgen dat de uiteindelijk beschikking de juiste informatie bevat.

Medewerkers hebben ieder hun eigen document.

Bevindingen zijn mogelijk gevat in een document wat gewijzigd moet kunnen worden.

Architectuurschets (origineel): [Delft AVG](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/Delft%20AVG.md)
RGBZ Mapping: #462 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigingen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] Voldoet aan AVG

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by EdwinCoster** [comment]
Dit kan alleen zolang Zaak.Zaakstatus 'In behandeling genomen' is. Zodra de Zaakstatus wijzigt in 'Advies ingewonnen' kan de behandelaar bezig zijn met het samenstellen van het besluit/de beschikking.
Informatieobject: 'Advies intern'

**Comment by TCIMEddy** [comment]
@joeribekker Kunnen we dit?

**Comment by joeribekker** [comment]
Na uitleg van @EdwinCoster gaat dit om rechten "object"-niveau autoriseren. Want, maar 1 iemand (de deskundige uit de US) mag bij dit specifieke document, en andere deskundigen mogen er **niet bij**.

Eindproduct van deze US is een uitspraak over wat hier mee gaan doen.

**Comment by Hugo-ter-Doest** [comment]
We maken ontwerpbeslissing dat autorisatie op objectniveau (bijv. op het niveau van ind. zaken of documenten) buiten de scope van de ZGW API's is.
