### ISSUE TITLE
Als leverancier wil ik weten hoe tekstvelden eruit zien

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#327]
...zodat ik deze correct kan weergeven.

Net besproken met @ArjanKloosterboer - de AN1000 limitaties slaan eigenlijk op niet zo veel meer, belangrijker is weergeven hoe de tekst eruit ziet - dit kan plain text zijn, maar bijvoorbeeld ook markdown of html (door een WYSIWYG editor bijvoorbeeld). Dit kan incompatibiliteit opleveren tussen leveranciers, en hier moet misschien ook in gestandardiseerd worden.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ArjanKloosterboer** [comment]
Ik heb een discussie hierover op het [RGBZ-discussieplatform](https://discussie.kinggemeenten.nl/discussie/gemma/rgbz/formaat-van-tekstvelden) gestart.

**Comment by sergei-maertens** [comment]
Ik blok hem dan tot er daar een uitkomst is

**Comment by ArjanKloosterboer** [comment]
@sergei-maertens, wat mij betreft is er een uitkomst, zie genoemde discussie.
Oplossing aldaar: 
Beperken tot alle tekens die op een voor Nederland bedoeld toetsenbord voor komen ('Engels (Verenigde Staten)"). Dus inclusief de alinea-einde-markering.
Wat ik niet weet is of dit te specificeren is met een deelverzameling van UTF-8.
