### ISSUE TITLE
Als archiefbeheerder wil ik alle zaken met een bepaalde vernietigingsdatum of ouder opvragen

### ISSUE THREAD

**Issue by MarcoKlerks** [VNG-Realisatie/gemma-zaken#347]
...zodat ik een concept-vernietigingslijst kan opstellen. Deze lijst controleer ik samen met de proces-eigenaren en de archivaris. Zijn er zaken die we (onderbouwd) langer willen bewaren? Zo ja, dan pas ik daar de vernietigings- en/of overbrengingsdatum aan (zie use case #346).

Nadat er diverse wijzigingen zijn doorgevoerd, wil ik waarschijnlijk weer een nieuwe concept-vernietigingslijst gaan opstellen.

Zie ook use case #348.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@MarcoKlerks Dank! Ik heb de user story op naam van de product owner Eelco Hotting gezet. We houden je op de hoogte

**Comment by joeribekker** [comment]
Dit komt neer op een filter op vernietingsdatum (met groter/kleiner dan)

**Comment by joeribekker** [comment]
Mogelijk via #348.

**Comment by Hugo-ter-Doest** [comment]
Lijkt me goed.

**Comment by TCIMEddy** [comment]
@joeribekker kan dit op close dan?
