### ISSUE TITLE
Epic: Als medewerker IB wil ik dat het DMS voldoet aan de NEN norm 2082, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#364]
...zodat het systeem voldoet aan de geformuleerde verzameling eisen voor functionaliteiten van informatie- en archiefmanagement in programmatuur.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Ik ga de backlog vullen met mogelijke user stories. Zet ze even op jouw naam zodat jij kan beoordelen of dit zinvol is of niet.

**Comment by MarcoKlerks** [comment]
Succes! Als je hulp nodig hebt, laat gerust even iets weten. Misschien kan ik helpen.

**Comment by ehotting** [comment]
@MarcoKlerks Is deze zinvol? ;)

**Comment by MarcoKlerks** [comment]
@ehotting In de NEN 2082 staan diverse functionele eisen waaraan een systeem moet voldoen willen we het informatie- en archiefbeheer goed uit kunnen voeren. Sommige eisen zijn open deuren. Sommige eisen zijn essentieel. En bij sommige eisen kun je je inderdaad afvragen in hoeverre deze relevant zijn voor een zaaksysteem. De meningen daarover kunnen verschillen. @TCIMEddy heeft volgens mij voor iedere eis al een afzonderlijke user story aangemaakt, zodat we af kunnen stemmen wat wel relevant is en wat niet. Ik heb echter zijn werk niet gecontroleerd (was ik ook niet van plan) en ik weet ook niet of hij al klaar is.

@TCIMEddy Ben jij al klaar met het vertalen van de NEN 2082 in individuele user stories? Kan deze algemene, alomvattende user story dus beëindigd worden?

**Comment by TCIMEddy** [comment]
@MarcoKlerks dank voor je snelle reacties. Ik ben helaas (of gelukkig) geen materiedeskundige. Ik heb in Haarlem een aantal workshops gedaan mbt DIV/IB en daar zijn deze user stories uitgekomen. Ik kijk mijn aantekeningen nog na of ik toelichting kan geven. Vertaling van NEN zal hoogstwaarschijnlijk niet zijn gebeurd. (Zou wel moeten maar...)

**Comment by Hugo-ter-Doest** [comment]
In feite is dit een epic. 
De formulering is ongelukkig omdat we geen DMS realiseren, maar een aantal API's die gezamenlijk RMA functionaliteit mogelijk moeten maken. De gerefereerde user story #674 is een preciezere formulering van de behoefte.

**Comment by Hugo-ter-Doest** [comment]
Er worden user stories aangemaakt per paragraaf van functionele eisen.
