### ISSUE TITLE
Als behandelaar wil ik betrokkenen binnen en buiten mijn eigen organisatie veilig toegang kunnen geven tot zaakdocumentatie of een relevant deel daarvan om te voorkomen dat gegevens in verkeerde handen vallen.

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#366]
...zodat we voorkomen dat gegevens in verkeerde handen vallen.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by hdksi** [comment]
Achtergrond hierbij: zaakdocumentatie wordt (binnen eigen organisatie of in de keten) vaak gedeeld via e-mail. Dit is niet veilig en privacy van betrokkenen is niet gewaarborgd.

**Comment by hdksi** [comment]
Deze user story gepost naar aanleiding van discussie tijdens Adviesgroep Informatievoorziening met Ellen van der Steen (Gemeente Apeldoorn). Dit omdat we nog weinig stories konden vinden met betrekking op (keten)samenwerking binnen ZGW.

**Comment by TCIMEddy** [comment]
@joeribekker @sergei-maertens Deze kwam binnen en is dit een US die past binnen de autorisatie-werkzaamheden

**Comment by ehotting** [comment]
Het aspect "buiten mijn organisatie" is een mogelijk interessante uitbreiding

**Comment by ehotting** [comment]
Is de oplosing functioneel niet anders, namelijk dat organisatie X een document moet kunnen wegschrijven bij organisatie Y? In het kader van doorgeleiden van zaken naar het juiste bevoegd gezag etc? Dan is het technisch een kwestie van juiste autorisatie / scopes

**Comment by joeribekker** [comment]
Hoe jij het verwoord lijkt het meer op een kopie maken :) Of als je echt alleen bedoeld wegschrijven bij externe partij, en je wil deze bevragen bij de bron vanuit de organisatie dan heb je het probleem verschoven naar de externe partij wat betreft autorisaties.

Wellicht kan @hdksi dit toelichten, of wellicht zoekt hij een oplossing voor het probleem in functionele zin.

**Comment by hdksi** [comment]
Zo te zien staat zelfs dat eerste vinkje ter discussie :)

De vraag om de in de story genoemde functionaliteit is niet van mijzelf afkomstig; ik heb hem slechts opgeschreven naar aanleiding van een discussie tijdens een bijeenkomst van voornoemde werkgroep. 

Waar het hier om ging is de mogelijkheid een persoon/organisatie te autoriseren om specifieke zaakdocumententatie (en/of andere kenmerken van die zaak) te kunnen inzien en/of aanpassen. In feite is hier dus sprake van een variant op #66 en gewenste (maar wellicht onmogelijke) functionaliteit bij #424.

**Comment by TCIMEddy** [comment]
@hdksi :-) denk dat ik dat vinkje heb gezet. Ben ik goed in.... Wat mij betreft mag je de user story zelf ook wijzigen met jouw opmerkingen. Het is mij duidelijk :-)

**Comment by Hugo-ter-Doest** [comment]
Zaken kunnen al worden geraadpleegd door andere organisaties middels de juiste scopes. Autoriseren op attribuutniveau gaan we niet ondersteunen.
