### ISSUE TITLE
Als behandelaar wil ik zaakdocumentatie of een deel daarvan traceerbaar en (privacy)veilig kunnen overdragen aan een andere organisatie om dubbele registratie te voorkomen.

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#367]
...zodat [vul aan].

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by hdksi** [comment]
Deze user story gepost naar aanleiding van discussie tijdens Adviesgroep Informatievoorziening met Ellen van der Steen (Gemeente Apeldoorn). Dit omdat we nog weinig stories konden vinden met betrekking op (keten)samenwerking binnen ZGW.

**Comment by MarcoKlerks** [comment]
Overdragen van archiefbeshceiden van de ene organisatie naar de andere mag slechts met toestemming van de minister van OCW (Archiefwet, art. 8, lid 2).

Je kunt beter vooraf regelen welke organisatie in de keten als zorgdrager optreedt, het dossier daaronder registreren en de diverse ketenpartners autoriseren.

**Comment by hdksi** [comment]
@MarcoKlerks: goed punt. Tijdens de bijeenkomst van de adviesgroep werd (als ik het goed onthouden heb door @IvovanZitteren1, maar ik kan hem hier niet mentionen) een case genoemd waarbij zaakdocumentatie wordt overgedragen tussen gemeenten. In dit geval omdat een grote gemeente diensten verleent aan inwoners van kleinere collega-gemeente. Of hier daadwerkelijk sprake is van overdracht van zaakdocumentatie, en hoe dit proces zich verhoudt tot de verplichtingen in de archiefwet durf ik niet te zeggen.

Overigens zie ik dat deze story inhoudelijk sterk overeenkomt met issue #10 .

**Comment by IvovanZitteren1** [comment]
Hiervoor bestaat o.a. de gemeentecode. Een zaak heeft altijd betrekking op een bepaalde gemeente. 
Een persoon kan medewerker zijn van gemeente A, maar ook geautoriseerd zijn op zaken af te handelen voor gemeente B en C. Het autorisatiemodel moet hier inderdaad in voorzien.

**Comment by MarcoKlerks** [comment]
Ik begrijp dat er een attribuut "gemeentecode" is. Het is belangrijk dat in de documentatie duidelijk is dat het attribuut niet alleen betekent op welke gemeente de zaak **betrekking** heeft, maar ook dat de gemeente **eigenaar** is van de zaak en dus ook **zorgdrager** i.h.k.v. de Archiefwet. Het attribuut is dus niet alleen informatief, maar heeft ook juridische consequenties.

**Comment by ehotting** [comment]
Klopt mijn interpretatie dat voorgestelde user story illegaal is? :)

**Comment by IvovanZitteren1** [comment]
Ik denk van niet. Denk aan de overbrenging of overdracht van (delen) zaakdossiers naar E-Depots van (regionale) archieforganisaties. In de praktijk komt dit nog niet zo veel voor, maar in de toekomst gaan we dit mogelijk vaker zien.

**Comment by MarcoKlerks** [comment]
@IvovanZitteren1 In dat geval heeft het College B&W het desbetreffende e-depot conform de Archiefwet, art. 31, aangewezen als archiefbewaarplaats. Het College blijft echter **eigenaar** van die dossiers en dus ook **zorgdrager** i.h.k.v. de Archiefwet.

De user story is echter niet opgesteld met het oog op archiefwettelijke overbrenging van digitale archiefstukken naar een digitale archiefbewaarplaats. Zie de eerste reactie. De user story is opgesteld in het kader van ketensamenwerking oftewel het "overdragen" van een dossier aan een andere organisatie ter verdere afhandeling.

Voor het overdragen van dossiers naar andere organisaties (en daarmee de overdracht van eigenaarschap en archiefverantwoordelijkheid) geldt de Archiefwet, art. 8, waarbij geldt dat er toestemming nodig is van de minister van OCW.

@ehotting De user story is dus niet illegaal, maar een zeer ongebruikelijke want bureaucratisch intensieve oplossing voor ketensamenwerking. Een beter alternatief is dat (een deel van) een zaak ontsloten kan worden voor een andere organisatie. Het dossier blijft dan staan waar hij staat, maar kan geraadpleegd of zelfs gemuteerd worden door de samenwerkende partij.

P.S. Er kan nog een derde motief zijn om archief over te dragen aan een andere organisatie, namelijk bij opheffing, samenvoeging of splitsing van de eigen organisatie. Denk daarbij aan gemeentelijke herindelingen. In dat geval geldt de Archiefwet, art. 4 en is er geen toestemming nodig van de minister. Maar goed, dat is weer een hele andere user story....

**Comment by MarcoKlerks** [comment]
In het kader van ketensamenwerking komt deze user story inderdaad niet of zelden voor.

In het kader van gemeentelijke herindelingen en andere organisatieoverstijgende reorganisaties komt dit per gemeente slechts incidenteel voor.

**Comment by Hugo-ter-Doest** [comment]
Moet m.i. opgelost kunnen worden met autorisatie.

**Comment by Hugo-ter-Doest** [comment]
Dit komt bijna niet voor.
