### ISSUE TITLE
Als ZTC-beheerder wil ik een zaaktype kunnen maken en beheren, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#369]
...zodat er gestructureerd informatiebeheer kan plaatsvinden conform geldende wet- en regelgeving (NEN ISO 15489).

Tevens:
...zodat een zaak, waarop de userstory's #39, #153, #154, #161, #169 e.a. betrekking hebben, behandeld kan worden op basis van een zaaktype met desbetreffende parameters. 

Vanuit genoemde userstory's zijn resources in de Zaaktypen-API (ZTC) ontwikkeld met enkele lees-operaties. Maar, als je geen gegevens kunt registreren, dan valt er ook niets te lezen. Doel van deze userstory is om create- en update-operaties te ontwikkelen voor alle nu in ZTC-lees-operaties aanwezige gegevens.  

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] De Zaaktypen-API maakt het mogelijk om alle, met de bestaande Zaakypen-API, te raadplegen gegevens vast te leggen en te wijzigen
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0 i.c. ImZTC 2.2 (incl. de daarin gespecificeerde businesslogica)
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Bepalen om welke velden het gaat [_verantwoordelijke_]
- [ ] Bepalen benodigde operaties op resources van de Zaaktypen-API [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ArjanKloosterboer** [comment]
Ik kom allemaal issues tegen met de 'medewerker IB'? Wie is dat toch? Wat is zijn/haar rol en taakveld in de gemeente? En kloppen dan die userstory's wel (zijn het inderdaad userstory's van die medewerker)?

**Comment by MarcoKlerks** [comment]
@ArjanKloosterboer 
De afkorting "IB" staat voor InformatieBeheer. Het is de medewerker DIV (Documentaire Informatie Voorziening), maar dan in een hedendaags jasje. De medewerker IB is belast met het beleid over, advisering op, regie over en (deels) uitvoering van het informatie- en archiefbeheer bij de gemeente, voor zover de bescheiden nog niet zijn overgebracht naar een archiefbewaarplaats c.q. e-depot.

Een aantal functionaliteiten die in de userstories gevraagd worden zijn inderdaad niet alleen relevant voor dit type medewerker, maar ook voor andere medewerkers / gebruikers.

Als medewerkers IB hun ondersteunende processen goed kunnen uitvoeren, dan hebben de medewerkers van het primaire proces daar profijt van.

**Comment by ArjanKloosterboer** [comment]
Dat dacht ik wel. Ik vind het verwarrend om een medewerker DIV als informatiebeheerder te bestempelen. Informatiebeheer is veel breder dan het taakveld van de DIVver (zie [hier](https://nl.wikipedia.org/wiki/Functioneel_beheer)). Het lijkt er op dat de DIV-wereld de term 'informatiebeheer' gekaapt heeft, m.i. ten onrechte. 
I.r.t. deze userstory, de DIVver draagt hooguit bij aan het zaaktype (vanuit duurzame toegankelijkheid). Het zaaktype is van de proceseigenaar. Die wil een zaaktype kunnen maken en beheren.

**Comment by MarcoKlerks** [comment]
Ik ben een DIV-er (of Informatiebeheerder) en ik heb helemaal niets gekaapt. Mijn collega's en vakgenoten bij andere organisaties evenmin. 

Bij de implementatie en uitvoering van het zaakgericht werken zijn er tal van taken die verdeeld moeten worden. Niet zelden wordt het ZTC-beheer belegd bij de DIV- of IB-afdeling of hoe ze die club ook noemen.

In mijn ervaring zijn er bovendien weinig tot geen proces-eigenaren (meestal afdelingshoofden o.i.d.) die zin hebben om zelf aan de knoppen te gaan zitten van de ZTC-functionaliteit. Meestal werkt een IB-medewerker in samenwerking met enkele mensen van de werkvloer een voorstel uit en legt deze voor aan de proces-eigenaar. Wanneer de proces-eigenaar instemt wordt het zaaktype geactiveerd (bijvoorbeeld de datum start geldigheid wordt ingevuld).

Eventueel zou dat nog een interessante user story kunnen zijn: "Als medewerker IB wil ik een nieuw of gewijzigd zaaktype ter goedkeuring voor kunnen leggen aan een proces-eigenaar, waarna deze bij goedkeuring geactiveerd wordt."

Als je "medewerker IB" wilt vervangen door "beheerder ZTC", dan lig ik daar niet wakker van. What's in an name?

**Comment by MarcoKlerks** [comment]
Overigens erken ik wel dat de "zodat" in de bovenstaande user story enige aandacht behoeft. Compliancy is weliswaar een van de motieven bij het inrichten van een zaaktype, maar er spelen ook andere motieven mee. Ik zuig even uit mijn duim:
- zodat medewerkers op een eenduidige wijze het proces kunnen uitvoeren en vastleggen,
- zodat burgers op een eenduidige manier geïnformeerd kunnen worden over de voortgang van het proces,
- zodat (afhankelijk van de applicatie) de juiste sjablonen en functionaliteiten beschikbaar worden gesteld.
- Et cetera.

**Comment by ArjanKloosterboer** [comment]
> Als je "medewerker IB" wilt vervangen door "beheerder ZTC", dan lig ik daar niet wakker van. What's in a name?

Zoals je zelf al aangeeft is het beheren van een zaaktype een rol. En die moeten we hier m.i. benoemen. Wie binnen een gemeente die rol uitvoert en in het kader van welke functie(benaming) is niet relevant. Dus laten we in dit kader spreken over een beheerder van een zaaktype. De zaaktypen in een ZTC kunnen best door meerdere mensen beheerd worden, eenieder een groep zaaktypen.

> Overigens erken ik wel dat de "zodat" in de bovenstaande user story enige aandacht behoeft. 

Welke 'zodat' is hier relevant? Vanuit de context DIV zou dat dan vooral duurzame toegankelijkheid zijn, toch?

**Comment by TCIMEddy** [comment]
Mooi dat er discussie ontstaat over de items op de backlog dan voorkomen we discussies in de sprint. Geef wel concreet aan wat ik moet wijzigen zodat user story duidelijk en scherp is. 

1. Kan ik medewerker met de toevoegingen laten staan?
2. Moet ik zodat aanpassen met duurzaam toegankelijk?

Deze discussie is wel openbaar dus let op aub op tone of voice, maar volgens mij zijn jullie het eens.

**Comment by MarcoKlerks** [comment]
Welnee, duurzame toegankelijkheid is meer iets van het archiefwezen, al speelt DIV in dat verhaal ook een rol. Maar zowel DIV als het archiefwezen houden zich ook met tal van andere zaken bezig! Maar laat ik niet een in lange monoloog verzanden over deze - overigens zeer boeiende en veelzijdige - vakgebieden... ;-)

Alle "zodat's" zijn hier relevant, maar het verschilt per organisatie welke 'zodat' de meeste prioriteit heeft. Een organisatie die het ZGW invoert om de bedrijfsvoering te verbeteren, zal vooral waarde hechten aan de eerste bullet. Een organisatie die het ZGW invoert om de dienstverlening te verbeteren zal vooral de tweede bullet prioriteit geven. Archivering is m.i. ook vooral een bedrijfsvoeringsdingetje.

Ter illustratie, op dit moment werk ik bij gemeente Rotterdam. Die vliegt het ZGW-vraagstuk vooral aan vanuit het dienstverleningsbelang. Hiervoor heb ik bij gemeente 's-Hertogenbosch gewerkt. Zij hebben vooral de bedrijfsvoering als vertrekpunt genomen bij de implementatie van het ZGW. Daardoor ontstaan verschillen in hoe zij het ZTC-beheer hebben ingericht.

Linksom of rechtsom komt het erop neer dat zaaktypen ingericht moeten kunnen worden. Het huidige ImZTC houdt al heel aardig rekening met de verschillende belangen, dus laten we die als uitgangspunt nemen. De vraag is dan nog wel of we één mutatie-service willen hebben voor zaaktypen, of dat we verschillende mutatie-services willen hebben. Bijvoorbeeld, een service voor proces-analisten, een service voor DIV-ers, een service voor proces-eigenaren, etc.

Ik zie daar nu nog niet echt een noodzaak toe. Eén service voor het creëren van zaaktypen, één voor het raadplegen en één voor het muteren, lijkt mij vooralsnog voldoende. Ik twijfel nog of er ook een service moet komen voor het verwijderen van zaaktypen, maar ik laat me daarin graag overtuigen.

Overigens kan ik nog niet goed overzien of voor het aanmaken, raadplegen, muteren en verwijderen van documenttypen, resultaattypen, besluittypen, statustypen, etc. weer aparte services nodig zijn.

**Comment by MarcoKlerks** [comment]
@TCIMEddy 
Ik zou 'Medewerker IB' wijzigen in 'ZTC-beheerder' en ik zou de 'zodat' vervangen door (mijn inziens) de twee belangrijkste motieven:
- zodat medewerkers op een eenduidige wijze het proces kunnen uitvoeren en vastleggen, en
- zodat burgers op een eenduidige manier geïnformeerd kunnen worden over de voortgang van het proces.

**Comment by ehotting** [comment]
Volgens mij kan dit

**Comment by TCIMEddy** [comment]
Ja volgens mij ook! Kan @joeribekker of @sergei-maertens dit bevestigen?

**Comment by ArjanKloosterboer** [comment]
Volgens mij niet. Van het ImZTC zijn in de Zaaktypen-API slechts een beperkt aantal gegevens gerealiseerd. In deze userstory gaat het over 'informatiebeheer',  in zaaktype-termen het 'archiefregime'. De daarvoor benodigde gegevens vind ik niet in de Zaaktypen-API-resources.

**Comment by sergei-maertens** [comment]
Nog niet volledig ImZTC is afgedekt in de API, als dat de vraag is. De API is op dit moment ook read-only en moet je in referentie-implementatie inrichten via beheerdersomgeving.

**Comment by ArjanKloosterboer** [comment]
M.i. kan deze userstory een mooie slice worden.

**Comment by sergei-maertens** [comment]
Moet wel verder verfijnd worden want als developer heb ik nu geen idee waarmee ik concreet aan de slag moet :-)

**Comment by ArjanKloosterboer** [comment]
Aha, ik voel een analyse en functioneel ontwerp aankomen ;-)

**Comment by ehotting** [comment]
Dit is dan een behoorlijk groot stuk van de API wat nog mist en wel essentieel is. Moet worden gesliced idd

**Comment by TCIMEddy** [comment]
@MarcoKlerks Zou jij ajb een voorzet willen doen in de comments dan maak ik er aparte user stories van.

**Comment by ArjanKloosterboer** [comment]
Marco biedt m.i. al twee slices aan:

> - zodat medewerkers op een eenduidige wijze het proces kunnen uitvoeren en vastleggen, en
> - zodat burgers op een eenduidige manier geïnformeerd kunnen worden over de voortgang van het proces.

En verder:
- zodat bij afsluiten van een zaak duidelijk is wat het archiefregime van het zaakdossier is.
- zodat van een zaak bepaald kan worden hoe en door wie deze uitgevoerd gaat worden. 
- zodat bij het behandelen van een zaak duidelijk is welke informatie daarbij vastgelegd moet worden.

@MarcoKlerks, dekt dit bij elkaar jouw behoefte? Zo niet, vul aan met 'zodat's.

**Comment by MarcoKlerks** [comment]
@ArjanKloosterboer Ik vind het prima, maar is @sergei-maertens daarmee geholpen?

Hij heeft het ook over een beheerdersomgeving. Ik neem aan dat deze ook via de API's met de data-laag communiceert? 

Ik weet ook niet wat een "slice" is.

Het gaat mij erom dat ZTC-gegevens niet alleen geraadpleegd moeten kunnen worden, maar er ook ingestopt en beheerd kunnen worden. Als er geen ZTC-gegevens in gestopt kunnen worden, dan kunnen zij ook niet gebruikt worden bij het registreren van zaken, etc.

**Comment by sergei-maertens** [comment]
@MarcoKlerks nee, in de referentie-implementatie gaat dat niet via de API. Er is een admin-environment waar je met username + password inlogt en catalogi kan inrichten, that's it.

**Comment by ehotting** [comment]
User story aangevuld op basis van #513 - en #513 gesloten als dubbel

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest lijkt me goed als jij gezien de discussie hier je visie op geeft en nog relevant is

**Comment by Hugo-ter-Doest** [comment]
Catalogi API is schrijfbaar gemaakt.
