### ISSUE TITLE
Als medewerker IB wil ik dat zaken en bijbehorende metadata afzonderlijk en in samenhang te vernietigen zijn,

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#371]
...zodat de gemeente voldoet aan de Archiefwet 1995 en Selectielijst 2017.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Ik neem als uitgangspunt dat bewaartermijnen worden vastgelegd op zaken en dat bij archiefvernietiging de hele zaak inclusief daaraan gerelateerde informatie wordt vernietigd. Implicatie: documenten krijgen geen eigen bewaartermijn en worden dus ook niet afzonderlijk vernietigd.

Voor archiefvernietiging is nodig:
- Dat we per zaaktype vastleggen hoe lang dergelijke zaken bewaard moeten worden (#344)
- Dat op grond hiervan de vernietigingsdatum (of overbrengingsdatum) van een zaak wordt berekend (#345)
- Dat ik een lijst kan uitdraaien van alle zaken waarbij de vernietigingsdatum is verlopen (#347 en #384)
- Dat ik deze lijst (handmatig) kan controleren. Als ik een zaak zie die ik - om welke legitieme reden dan ook - langer wil bewaren, dan pas ik bij die zaak de vernietigingsdatum aan (#346)
- Als ik een actuele, gecorrigeerde lijst heb, dan wil ik deze zaken kunnen vernietigen (#349).
- Als output wil ik een bevestigingslijst met vernietigde zaken (#349).

Ter info, de definitieve vernietigingslijst moet permanent bewaard worden. Er zal dus ook een zaak aangemaakt moeten worden, waar de lijst aan toegevoegd wordt. Deze functionalitiet lijkt mij echter iets voor de applicatielaag.

**Comment by ehotting** [comment]
@MarcoKlerks klopt mijn indruk dat deze user story te generiek is en alle aspecten ervan reeds afgedekt worden door andere user stories, welke jij opsomt? Oftewel, kan deze worden gesloten & gemarkeerd als dubbel?

**Comment by MarcoKlerks** [comment]
@ehotting Ja, wat mij betreft wel.

Mijn user stories zijn gedetailleerder. Ze hebben wel als nadeel dat ze op elkaar inhaken, oftewel het realiseren van de ene user story is zinloos als de andere ook niet gerealiseerd wordt.

Zie overigens ook #384. Hier wordt wederom gevraagd om vernietigingsfunctionaliteit.

**Comment by Hugo-ter-Doest** [comment]
Plan is om hier een volledige sprint aan te wijden incl. voorbereiding met experts.

**Comment by Hugo-ter-Doest** [comment]
Je kunt informatieobjecten niet afzonderlijk van de zaak vernietigen.
