### ISSUE TITLE
Als medewerker IB wil ik dat er op basis van metadata gezocht kan worden, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#373]
zodat informatie ontsloten kan worden, vindbaar en toegankelijk is.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Zoeken gebeurt toch vrijwel alleen op basis van meta-data? Juist zoeken op inhoud documenten is een fancy feature. ;)

**Comment by TCIMEddy** [comment]
Dat neem ik ook aan, deze user story gaat idd over zoeken op meta-data. Ik kan niet goed beoordelen wat de consequenties zijn voor de API’s. Dus dit gaat niet over fancy feature. Nog extra toelichting nodig?

**Comment by MarcoKlerks** [comment]
Denk bij aan het zoeken op metadata ook aan de boolean operators (and/or) en aan het gebruik van wildcards.
