### ISSUE TITLE
Als medewerker IB wil dat het inzichtelijk is wanneer er meerdere versies zijn van een informatieobject waardoor versiebeheer mogelijk is,

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#375]
zodat wordt voldaan aan de wettelijke verantwoordings-/bewijsvoeringsplicht.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Heb je extra informatie nodig of is er voldoende info om puzzel op te lossen (ben geen specialist maar ga het navragen indien nodig)

**Comment by Hugo-ter-Doest** [comment]
Procesreconstructie aan de hand van versies van documenten lijkt me niet goed mogelijk. Haal ik uit de user story.

**Comment by Hugo-ter-Doest** [comment]
Zie ook #857

**Comment by TCIMEddy** [comment]
dus deze close
