### ISSUE TITLE
Als medewerker IB wil ik dat informatieobjecten toegankelijk zijn via autorisatie per gebruiker, per groep, per afdeling

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#378]
zodat wordt voldaan aan de wettelijk gestelde eisen rondom geheimhouding, vertrouwelijkheid en de wet bescherming persoonsgegevens.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by MarcoKlerks** [comment]
Ik raad aan om de autorisatiestructuur los te knippen van de organisatiestructuur (groepen, afdelingen, organisaties, etc). Bij middelgrote en grote gemeenten zijn reorganisaties aan de orde van de dag. Afdelingen komen en gaan. Je moet dan telkens de autorisatiestructuur aanpassen.

Ik zou aan een medewerker een of meerdere rollen willen toekennen. Een rol kan gerelateerd worden aan een zaak, waardoor de medewerker geautoriseerd wordt voor de zaak en daaraan gerelateerde informatie (incl. documenten).

Mogelijk willen we rollen ook aan functies koppelen. Als een nieuwe medewerker wordt aangenomen binnen een bepaalde functie, dan kunnen geautomatiseerd de juiste rollen aan hem toegewezen worden. Eventueel kunnen deze handmatig aangepast worden.

**Comment by ehotting** [comment]
Vooralsnog is het plan in de API met scopes te werken en het aan de client over te laten om de altijd organisatie-specifieke indeling van identiteiten correct te mappen naar een scope.

**Comment by TCIMEddy** [comment]
@ehotting Is deze user story dan niet nodig (en dus close)?

**Comment by Hugo-ter-Doest** [comment]
Opgelost met scopes. Daarnaast is er een user story voor autorisatie op informatieobjecten die niet aan een zaak zijn gekoppeld; zie #699.
