### ISSUE TITLE
Als medewerker IB wil ik dat informatieobjecten te publiceren zijn, 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#379]
zodat ze ook toegankelijk gemaakt kunnen worden op het publieke web.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
@TCIMEddy doel je hier op publiceren middels de API, of afdwingen dat ze publiceerbaar zijn via de API?

**Comment by TCIMEddy** [comment]
@ehotting Ik moet ook geen user stories gaan opvoeren :-) Diepgravend in mijn geheugen kan ik het volgende voorstellen er is informatie vastgelegd in een informatieobject, in dit geval bijvoorbeeld een pdf met een besluit daarin. Er moet de mogelijkheid zijn om dit te publiceren (mits compliant uiteraard) in gesloten of open website. Of dat middels of via moet zijn kan ik niet beoordelen. Is dit antwoord op je vraag?

**Comment by MarcoKlerks** [comment]
Wat gepubliceerd moet worden en waarheen verschilt nu nog per proces of informatieobjecttype. Zo worden bijvoorbeeld raadsbesluiten op een andere website gepubliceerd dan bouwvergunningen.

Er komt bovendien een nieuwe Wet open overheid (Woo) aan. Hier is echter nog het een en ander onduidelijk over.

Ik vermoed dat de timing nog niet goed is om dit hier op te pakken.

**Comment by Hugo-ter-Doest** [comment]
Een RIS bijv. kan als consumer gebruik maken van de DRC om bepaalde documenten op te halen en deze te publiceren zoals nodig. Ik sluit het issue.
