### ISSUE TITLE
Als teammanager wil ik een dashboard met managementinformatie over zaken

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/gemma-zaken#403]
...zodat ik kan sturen.

Aantal voorbeelden van managementrapportages om de user story inhoud/richting te geven:

- Aantal afgehandelde zaken
- Aantal binnengekomen zaken
- Aantal openstaande zaken
- Aantal overschrijdend op geplande einddatum
- Aantal overschrijdend op uiterlijke einddatum afdoening

Parameters van de rapportages:
- Kolom: Afdeling, Groep, Behandelaar, Kanaal, Status, Zaaktype, Doorlooptijd, Overschrijding, Resultaat, Maand, Week, Dag
- Rij: Afdeling, Groep, Medewerker, Kanaal, Status, Zaaktype, Doorlooptijd, Overschrijding, Resultaat, Maand, Week, Dag
- Startdatum
- Einddatum

RGBZ mapping is #464

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Ik kan niet overzien of hier iets voor moet worden gedaan in de standaard.

**Comment by jgortmaker1** [comment]
welke managementinfo wil de manager zien? pas dan kunnen we goed beoordelen of het kan en/of wenselijk is denk ik...

**Comment by Hugo-ter-Doest** [comment]
Ik kan een standaardsetje managementrapportages voor zaken aanleveren.

**Comment by ArjanKloosterboer** [comment]
Ik heb de RGBZ-mapping gereviewed. In de veronderstelling dat je (@EdwinCoster) de mapping daarop aanpast heb ik het vinkje alvast gezet.

**Comment by EdwinCoster** [comment]
@Hugo-ter-Doest: Gaarne aandacht voor de review van Arjan.

**Comment by Hugo-ter-Doest** [comment]
Heb de review verwerkt.

**Comment by Hugo-ter-Doest** [comment]
@jgortmaker1 Kun jij reviewen op conformiteit ZGW volgens Gemma 2?

**Comment by jgortmaker1** [comment]
ik zie geen probleem..

**Comment by Hugo-ter-Doest** [comment]
Ready gemaakt in zover ik dat kan zonder team. Nu moet de PO en het team er iets van vinden voordat deze naar de ready kolom mag.

**Comment by ehotting** [comment]
Wel belangrijk, maar of het tijdens planningssessie in sprint wordt opgenomen hangt af van hoe groot deze klus is.

**Comment by Hugo-ter-Doest** [comment]
Besproken door team op 6 november. Nog niet duidelijk geworden of dit in de huidige API moet worden ondersteund. Misschien is een aparte API of endpoint nodig voor managementinformatie, Hetzelfde geldt voor zoeken.

**Comment by michielverhoef** [comment]
Wat mij betreft is dit buiten scope voor de API's voor Zaakgericht werken.
