### ISSUE TITLE
Als projectlid wil ik weten welke scopes voor autorisatie we onderkennen in de API

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#424]
...zodat ik deze kan opnemen in de API specs en implementeren.

Er zijn enkele doelen om voor ogen te houden:

* scopes gebruiken om toegang tot resources (en de data daarbinnen) in te regelen
* beheer zo laag mogelijk houden, dit betekent dat we een minimale set aan scopes moeten bepalen

We hebben hier de input van @ArjanKloosterboer nodig - Arjan weet op basis van de informatiemodellen wat er samenhoort en binnen 1 scope zou kunnen passen. Arjan kan ook input geven wat velden zoals `vertrouwelijkheidAanduiding` betekenen gemapt op scopes.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een lijst van scopes opgesteld
- [ ] er is een architectuurschets van de context
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
- [ ] de scopes zorgen niet voor  beheersoverlast
- [ ] de scopes laten toe om gegevens te limiteren

**Taken**
- [ ] bepalen welke scopes nodig zijn [ @ArjanKloosterboer & @sergei-maertens ]
- [ ] Functionele documentatie [_verantwoordelijke_]

**Comment by jgortmaker1** [comment]
is dit ook geen oplossing voor #65 ?

**Comment by ArjanKloosterboer** [comment]
> bepalen welke scopes nodig zijn [ @ArjanKloosterboer ]

Ik ben niet bekend met het concept 'scope'. Kan deze taak dus nog niet uitvoeren. Vandaar "overleg nodig".

**Comment by sergei-maertens** [comment]
@ArjanKloosterboer is ook precies de bedoeling dat jij en ik samen dit invullen wanneer we samen zitten (komende maandag?)

**Comment by sergei-maertens** [comment]
@jgortmaker1 ik zie de link niet meteen?

**Comment by jgortmaker1** [comment]
zeker in het sociaal domein mag je niet zomaar alle lopende zaken van een persoon zien en zeker niet alle gegevens van een lopende zaak...enkel met doelbinding..volgens mij heb je daar fijnmazigere autorisatie voor nodig dan "vertrouwelijkheids-aanduiding"..ik dahct dat scopes dat kon bieden..

zo niet dan heb ik het verkeerd begrepen en sluit ik me aan bij Arjan :-)

**Comment by arnoudquanjer** [comment]
Verwerking van gegevens mag alleen als er voor de verwerkingen waarvoor een doel en een wettelijke grondslag is! Ik heb geen idee hoe scopes werken, maar een autorisatiemodel op (categorieën) van gegevens dient rekening te houden met het doel en wettelijke grondslag van de verwerking die uitgevoerd wordt.

**Comment by ehotting** [comment]
Het puzzeltje wat met name opgelost moet worden is de verdeling tussen autorisatie aan kant client en provider. Dit is de kern van waarom ik meen dat we bij een full-blown gegevenslandschap vrijwel niet om NLX heen zullen kunnen. 

Daarbij is relevant dat wanneer een client wel het technisch recht (=autorisatie) heeft om meer gegevens uit een API te raadplegen, maar dit zelf beperkt door bijv. 'field' query parameters, de bedoelde gegevens ook niet verwerkt worden.

**Comment by jgortmaker1** [comment]
> Het puzzeltje wat met name opgelost moet worden is de verdeling tussen autorisatie aan kant client en provider. Dit is de kern van waarom ik meen dat we bij een full-blown gegevenslandschap vrijwel niet om NLX heen zullen kunnen.

NLX kan alles een heel stuk makkelijker maken, maar ik handhaaf mijn standpunt dat de door ons ontwikkelde API's ook zonder NLX moeten kunnen werken. Dus we kunnen voor autorisatie niet volledig op de NLX vertrouwen..

**Comment by TCIMEddy** [comment]
@jgortmaker1 @ehotting Volgens mij is hier nog overleg nodig tussen jullie.
