### ISSUE TITLE
Als projectlid wil ik dat de referentieimplementaties de implementeerbaarheid van de scopes aantonen

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#425]
...zodat externen (leveranciers, gemeenten, ...) een voorbeeld hebben hoe access control in te richten.

Wat uit #424 komt moet geimplementeerd worden.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] de lijst van scopes is geimplementeerd en zichtbaar in de API spec
- [ ] er is een architectuurschets van de context
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
- [ ] de scopes zorgen niet voor  beheersoverlast
- [ ] de scopes laten toe om gegevens te limiteren

**Taken**
- [ ] scopes implementeren [ @sergei-maertens ]
- [ ] Schrijven (unit) test voor referentie-implementatie [@sergei-maertens]
- [ ] Implementeren in referentie-implementatie [@sergei-maertens]
- [ ] Genereren/opstellen van OAS 3.0 [@sergei-maertens]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [@sergei-maertens]

**Comment by TCIMEddy** [comment]
Sorry allen maar we moeten weer even wat strikter in scrumproces komen...
@ehotting wil jij vinkje zetten dat jij akkoord bent. 
@ArjanKloosterboer moet hier wat gebeuren ihkv RGBZ (zo niet vink af)
@jgortmaker1 moet hier een architectuurschets komen (zo niet vink af)
@sergei-maertens kun jij inschatten of dit in 1 sprint past (en zo ja graag afvinken)

**Comment by ArjanKloosterboer** [comment]
Ik zie geen relatie tot RGBZ dus akkoord.
