### ISSUE TITLE
Als projectlid wil ik weten wat de rol van NLX is rond authenticatie en autorisatie

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#426]
...zodat ik weet of NLx wel of niet verplicht is en wat nodig is indien NLx niet gebruikt wordt.

Dit houdt concreet in dat gedocumenteerd moet worden wat NLx oplost en duidelijk maken welke risico's volgen uit het niet-gebruiken van NLx.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] de rol van NLx is duidelijk gespecifieerd in de docs
 - [ ] ... met specifieke aandacht voor consequenties aan client kant bij wel/niet gebruik NLX
- [ ] de docs zijn gepubliceerd leesbaar
- [ ] er is een architectuurschets van de context
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
- [ ] de scopes zorgen niet voor  beheersoverlast
- [ ] de scopes laten toe om gegevens te limiteren

**Taken**
- [ ] documentatie schrijven [ @sergei-maertens ]
- [ ] architectuurschets opstellen [ @sergei-maertens ]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [@sergei-maertens]

**Comment by joeribekker** [comment]
@ehotting: @jgortmaker1 twijfelt of APIs alleen via NLX moeten werken.

**Comment by TCIMEddy** [comment]
@ehotting a.s. donderdag moeten wat mij betreft alle user stories autorisatie die nog niet ready zijn maar wel in sprint geplaatst definitief ready gemaakt worden

**Comment by jgortmaker1** [comment]
waar is het vink-vakje wenselijk gebruik binnen architectuur gebleven?

**Comment by TCIMEddy** [comment]
@ehotting zie opmerking Jeffrey

**Comment by ehotting** [comment]
Vooraf is geen architectuurschets nodig (geen uitleg van een user story), de architectuur rond authenticatie en autorisatie is wat binnen deze user story opgeleverd zal moeten worden. Betekent dat het ook bij DoD moet staan, zal ik doen.

**Comment by joeribekker** [comment]
@sergei-maertens gaat het gesprek aan met GJ op Slack om dit op te helderen.

**Comment by sergei-maertens** [comment]
In #890 NLX in het totaalplaatje opgenomen
