### ISSUE TITLE
Als gebruiker van de referentieimplementaties wil ik een voorbeeld van een rol-naar-scope mapper

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#427]
...zodat ik een duidelijk beeld heb van hoe dit eruit ziet.

De context is dat binnen een organisatie (gemeente) gesproken wordt over rollen (bijvoorbeeld vergunningsdeskundige). Deze rollen zijn organisatie-specifiek. Het is niet beheersbaar om binnen de API alle rollen van alle organisaties te onderkennen, maar we kunnen wel scopes bepalen. Binnen de organisatie moet dus een mapping van rol -> scopes gebeuren. Om deze extra infrastructuur makkelijk te faciliteren (en het praktisch gebruik te bewijzen), willen we een plugin maken voor de referentieimplementaties waar een dergelijke mapping in kan geconfigureerd worden. Dit wordt geen formeel onderdeel van de API spec.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] de mapper is als 3rd-party app installeerbaar (zoals `nlx-middleware`)
- [ ] de functionaliteit is gedocumenteerd
- [ ] er is een architectuurschets van de context
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
- [ ] de scopes zorgen niet voor  beheersoverlast
- [ ] de scopes laten toe om gegevens te limiteren
- [ ] de mapper is geen formeel onderdeel van de API spec

**Taken**
- [ ] implementeren mapper [ @sergei-maertens ]
- [ ] documentatie schrijven [ @sergei-maertens ]
- [ ] architectuurschets opstellen [ @sergei-maertens ]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [@sergei-maertens]

**Comment by TCIMEddy** [comment]
Sorry allen maar we moeten weer even wat strikter in scrumproces komen...
@ehotting wil jij vinkje zetten dat jij akkoord bent. 
@ArjanKloosterboer moet hier wat gebeuren ihkv RGBZ (zo niet vink af)
@jgortmaker1 moet hier een architectuurschets komen (zo niet vink af)
@sergei-maertens kun jij inschatten of dit in 1 sprint past (en zo ja graag afvinken)

**Comment by ArjanKloosterboer** [comment]
Van een mapping naar RGBZ is slechts beperkt sprake. Relevant zijn Rolomschrijving en Rolomschrijving generiek van betrokkenen bij zaken. De eerste lijkt overeen te komen met de rol in de userstory.
Ik zie geen vinkje met RGBZmapping dus hierbij akkoord.

**Comment by joeribekker** [comment]
![IMG_20190314_142808](https://user-images.githubusercontent.com/96970/54360819-ff471300-4665-11e9-94e5-2bd8300f27b8.jpg)
