### ISSUE TITLE
Als api-ontwikkelaar wil ik een standaardmechanisme om scopes te kennen van een app

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#428]
...zodat er een uniforme implementatie is.

Het moet bekend zijn welke scopes er bij de client/consumer van de API horen zodat de API hiermee rekening kan houden. We willen delegation vermijden en een mechanisme dat geen beheerslast meebrengt.

Inleiding scopes: https://geonovum.github.io/KP-APIs-OAuthNL/#scopes

**PRs**

* [gemma-zaken, designkeuzes + architectuur](https://github.com/VNG-Realisatie/gemma-zaken/pull/486)

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] ~~**_Userstory is voorzien van veldmapping naar RGBZ2_**~~
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [x] ~~er is een OAS 3.0 specificatie~~ n.v.t.
- [x] de specificatie is gepubliceerd leesbaar
- [x] ~~er is een referentieimplementatie~~ n.v.t. in deze US
- [x] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [x] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [x] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [x] ~~Voldoet aan RGBZ 2.0~~ n.v.t.
- [x] ~~Voldoet aan GEMMA 2.0~~ n.v.t.
- [x] Er is een mechanisme om scopes te documenteren en deze documentatie te raadplegen

**Taken**
- [x] Autorisatie-architectuurschets opstellen [ @sergei-maertens ]
- [x] Human Readable publiceren Open API Specificatie (v.3.0) [ @sergei-maertens ]

**Comment by TCIMEddy** [comment]
@ehotting wil jij vinkje zetten dat jij akkoord bent. 
@ArjanKloosterboer moet hier wat gebeuren ihkv RGBZ (zo niet vink af)
@jgortmaker1 moet hier een arhitectuurschets komen (zo niet vink af)

**Comment by ArjanKloosterboer** [comment]
Van een veldmapping naar RGBZ is hier niet echt sprake. Vooral relevant zijn de Vertrouwelijkaanduiding (bij Zaak en Informatieobject) en de Rolomschrijving generiek van betrokkenen bij zaken.

**Comment by sergei-maertens** [comment]
Idee: JWT die scopes meegeeft?
