### ISSUE TITLE
Als beheerder wil ik dat authenticatie/autorisatie voor alle koppelvlakken op dezelfde manier geregeld wordt

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#431]
...zodat authenticatie/autorisatie als onderliggend principe beschreven kan worden en niet voor elk koppelvlak opnieuw bedacht hoeft te worden.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
Sorry allen maar we moeten weer even wat strikter in scrumproces komen...
@ehotting wil jij vinkje zetten dat jij akkoord bent. 
@ArjanKloosterboer moet hier wat gebeuren ihkv RGBZ (zo niet vink af)
@jgortmaker1 moet hier een architectuurschets komen (zo niet vink af)
@sergei-maertens kun jij inschatten of dit in 1 sprint past (en zo ja graag afvinken)

**Comment by TCIMEddy** [comment]
@michielverhoef Ik neem aan dat je bedoelt dat designkeuzes niet alleen gelden voor dit team maar voor alle projecten en teams die API’s ontwikkelen?

**Comment by michielverhoef** [comment]
Dat is wel de bedoeling ja.  Sorry voor de ietwat chaotische user story maar het was nog vroeg vanochtend, eigenlijk mag het RGBZ in ieder geval komen te vervallen (denk ik). 

Het gaat mij er om dat alle API's/koppelvlakken op dezelfde manier authenticatie en autorisatie toepassen zodat leveranciers dit op een eenduidige manier kunnen inbouwen.

**Comment by joeribekker** [comment]
Een voorbeeldje om het verschil tussen autorisatie en authenticatie toe te lichten:

* Authenticatie is als een paspoort: Met een paspoort bewijs ik wie ik ben.
* Autorisatie is als een bioscoopkaartje: Een bioscoopkaartje geeft toegang tot de film op het kaartje. Het zegt niets over wie ik ben.
* Hybride oplossingen bestaan ook, zoals een rijbewijs: Een rijbewijs bewijst wie ik ben en geeft aan dat ik de auto klasse mag rijden die er op staat.

_Ik heb dit voorbeeld ook in #426 staan, maar het lijkt me goed als dit bij mensen in het achterhoofd zit op relevante plekken._

**Comment by michielverhoef** [comment]
Ik zie het altijd zo:
Authenticatie geeft aan wie ik ben
Autorisatie geeft aan wat ik mag

Komt redelijk overeen dus 👍

**Comment by michielverhoef** [comment]
In het verlengde van de discussie van gisteren, met authenticatie en autorisatie regel je geen encryptie van de gegevens die uitgewisseld worden. Moeten we daar ook een userstory over opnemen?

Bijvoorbeeld iets als: Als medewerker van een gemeente wil ik dat de gegevens de uitgewisseld worden beveiligd en versleuteld worden zodat onbevoegde personen geen inzage in de gegevens kunnen hebben

**Comment by sergei-maertens** [comment]
Het lijkt me common sense dat organisaties zelf ervoor zorgen dat ze (enkel) via TLS gegevens ontsluiten. In deze tijden kom je er echt niet meer mee weg als je geen HTTPS gebruikt.

**Comment by Hugo-ter-Doest** [comment]
Dit is projectoverstijgend. Ik zou dan kaders verwachten vanuit het architectuurteam.
