### ISSUE TITLE
Als afhandelaar bezwaarschriften wil ik de historie van zaken kunnen zien

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#448]
...zodat ik een oordeel kan vormen over de juistheid van een doorlopen proces.

gerelateerd aan: #459 #460 #472

Het gaat daarbij om het kunnen opvragen van:
- [ ] Wat was de toestand op datum x, zoals deze administratief was vastgelegd en zichtbaar?
- [x] Wat was de toestand op datum x, inclusief eventuele correcties?

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Hiervoor hebben we bezwaarspecialisten nodig. Relevant deel van wat mogelijk moet zijn met mogelijk wat design choices die je niet achteraf wilt moeten maken.

**Comment by joeribekker** [comment]
Even op basis van wat ik denk dat relevant is voor deze story:

Bijwerken, met prachtig tijdrijzen en zodat alle zaken naar het "juiste" (=versie waar je em aan koppelt) document verwijst is nu mogelijk met de simpele API zonder UPDATE functie.

```http
GET /drc/api/v1/enkelvoudiginformatieobject/<uuid>  # Haal bestaand document op
POST /drc/api/v1/enkelvoudiginformatieobject  # Maak nieuwe versie aan van document aan
POST /drc/api/v1/objectinformatieobjecten  # Leg relatie tussen nieuwe versie van document en zaak
```

*Tekstueel is dit dus prima mogelijk*

1. Maak DOC X versie 1 aan
2. Koppel ZAAK A aan DOC X versie 1
3. Koppel ZAAK B aan DOC X versie 1
4. Maak DOC X versie 2 aan
5. Koppel ZAAK A aan DOC X versie 2

Nu heb je keurig ZAAK A aan DOC X versie 2 gekoppelt, en ZAAK B is gekoppelt aan DOC X versie 1.

**Comment by TCIMEddy** [comment]
@ArjanKloosterboer Ik heb deze maar even gekozen voor jou om ready te maken. Belangrijkste reden is om het proces te doorlopen en niet gelijk oplossing e.d.

**Comment by TCIMEddy** [comment]
Voor bezwaarschriften -> uit document van Arjan moet je velden halen die nodig zijn voor deze user story @CMasselink 
Daarna review door @ArjanKloosterboer

**Comment by ArjanKloosterboer** [comment]
Ik zie een samenhang met #460 en #472 omdat het inzien van ooit doorgevoerde mutaties een rol kan spelen.

**Comment by Hugo-ter-Doest** [comment]
dubbel met #722
