### ISSUE TITLE
Als afhandelaar bezwaarschriften wil ik een specifieke versie van een document het onderwerp van mijn zaak laten zijn

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#460]
...zodat de bezwaarafhandeling niet wordt verstoord wanneer vanuit een andere zaak het document wordt gewijzigd.

Zie ook #448 #460 #472 

Heeft alles te maken met materiële en formele historie, maar zou nog meer concreet gemaakt kunnen worden.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Even op basis van wat ik denk dat relevant is voor deze story:

Bijwerken, met prachtig tijdrijzen en zodat alle zaken naar het "juiste" (=versie waar je em aan koppelt) document verwijst is nu mogelijk met de simpele API zonder UPDATE functie.

```http
GET /drc/api/v1/enkelvoudiginformatieobject/<uuid>  # Haal bestaand document op
POST /drc/api/v1/enkelvoudiginformatieobject  # Maak nieuwe versie aan van document aan
POST /drc/api/v1/objectinformatieobjecten  # Leg relatie tussen nieuwe versie van document en zaak
```

*Tekstueel bsechreven is dit dus prima mogelijk*

1. Maak DOC X versie 1 aan
2. Koppel ZAAK A aan DOC X versie 1
3. Koppel ZAAK B aan DOC X versie 1
4. Maak DOC X versie 2 aan
5. Koppel ZAAK A aan DOC X versie 2

Nu heb je keurig ZAAK A aan DOC X versie 2 gekoppelt, en ZAAK B is gekoppelt aan DOC X versie 1.

**Comment by ehotting** [comment]
15 oktober 's middags overleg hierover

**Comment by ehotting** [comment]
Overleg geweest, #467 en #472 zijn hiervoor geopend. Is mogelijkheid te koppelen aan specifiek tijdstip een oplossing? Of aan een revisie? Vooralsnog niet helder, in afwachting prototype.

**Comment by Hugo-ter-Doest** [comment]
#857 zie hiervoor noodzakelijk

**Comment by TCIMEddy** [comment]
2 opties in de nieuwe situatie na sprint 12:
- linkje leggen
- kopie maken
