### ISSUE TITLE
Als overheid wil ik weten voor welke resources formele en/of materiele historie gedefinieerd moet worden

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#467]
...zodat ik deze kan implementeren in de API.

Analyse: Van elke resource in alle API's nagaan of er in de RGBZ beschrijving ervan een attribuut voorkomt waarvoor formele en/of materiële history voorgeschreven is. Zo ja, dan geldt voor hele resource dat respectievelijk formele en/of materiële historie geïmplementeerd moet worden.

De output van deze analyse dient als input voor een nieuwe user story in laatste sprint mbt uitbreiden API's met formele en materiele history.
Gerelateerd aan: #459

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] <s>_**Userstory is ingevuld op template architectuurschets**_</s>
- [x] <s>**_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)</s>
- [x] <s>**_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)</s>
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] de analyse is gemaakt en kan worden gebruikt als input voor nieuwe userstory met opsomming aan te passen resources
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0
- [ ] vastlegging in md document

**Taken**
- [ ] Analyse van alle resources in de ZDS 2.0 API's volgens beschrijving user story

**Comment by ArjanKloosterboer** [comment]
@michielverhoef  Bijgaand het overzicht van historie in het RGBZ. 
[RGBZ Historie.docx](https://github.com/VNG-Realisatie/gemma-zaken/files/2559509/RGBZ.Historie.docx)

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest is deze ready for sprint

**Comment by EdwinCoster** [comment]
[RGBZ-ZGW-Historie.xlsx](https://github.com/VNG-Realisatie/gemma-zaken/files/3051838/RGBZ-ZGW-Historie.xlsx)
Ik heb even een vergelijking gemaakt tussen het eerdere bestand van Arjan en wat wij in de API hebben zitten. Ik wilde dit ook nog langs het laaghangend fruit leggen, maar de tijd ontbreekt.
Waarschijnlijk is het ook nog niet helemaal compleet.
Maar wellicht helpt het wel.

**Comment by CMasselink** [comment]
Waar we denk ik nog wel even naar moeten kijken: 
Als we in de oude standaard **geen** historie hoefden bij te houden, hoeft dat wellicht niet te betekenen dat dit in de huidige situatie met de nieuwe API's ook niet hoeft.
Reden waarom: in de oude situatie legden we informatie over een resource (bijvoorbeeld persoon) in de zaak vast, dat betekent dat de waarden echt in de zaak zichtbaar was. In de nieuwe situatie nemen we soms alleen maar een URL verwijzing op.  Er is dus helemaal geen informatie in de zaak beschikbaar, behalve de URL verwijzing.

**Comment by michielverhoef** [comment]
In de Zaak- Documentservices wordt wel gebruik gemaakt van historie, zowel materieel als formeel.

Maar ik denk dat in sommige gevallen er geen sprake kan zijn van historie. Bijvoorbeeld bij het aanmaken van een zaak is er nog geen sprake van historie. Bij het uitvragen van de zaak dan (mogelijk) weer wel. 

Ik heb geen idee of het onzin is wat ik nu zeg maar zou dat dan kunnen betekenen dat de resource zoals die gebruikt wordt in een opvraging (GET) anders kan zijn, meer kan bevatten, dan bij het aanmaken (POST)?

**Comment by hdksi** [comment]
@michielverhoef Constantijn zegt volgens mij niet dat er in ZDS geen historie wordt bijgehouden, maar dat het feit dat Zaken in de ZGW-API-situatie worden gevormd door een verzameling relaties (URLs) naar externe registraties  een verandering in het aantal objectattributen waarvoor historie moet worden bijgehouden tot gevolg kan hebben. Waar je in de ZDS-situtatie nog een specifieke staat van een resource opnam bij een zaak, is het straks immers mogelijk dat je via een URL verwijst naar een resource die sinds de link is aangelegd is gemuteerd.

Constantijn bedoelt volgens mij dat het hierdoor mogelijk is dat voor meer dan de in bovenstaand document benoemde objectenattributen historie moet worden bijgehouden. Ik kan dat niet zo snel overzien, maar conceptueel zou het volgens mij geen verschil moeten maken.

Wat ik hier wel uithaal is dat het belangrijk is te bepalen hoe we naar een resource verwijzen; wordt per wijziging daarop een nieuwe URL gegenereerd? Dan is iedere URL dus alleen geldig voor één specifieke staat. Of verwijs je naar de staat van een resource op een specifiek moment door een timestamp oid toe te voegen?

**Comment by JohnRooijakkers** [comment]
Het lijkt me niet wenselijk om voor een nieuwe "versie" van een object een nieuwe URL te genereren. Bij voorkeur wil ik met alleen kennis over het zaak-id (de actuele versie van) het zaak object kunnen benaderen. Hoe (materiële en formele) historie van dat object benaderd moet worden is een vraagstuk op zich.

**Comment by Hugo-ter-Doest** [comment]
@JohnRooijakkers dank voor je input. Nemen we morgen mee in de backlog refinement historie.

**Comment by TCIMEddy** [comment]
Dit is te algemeen gesteld, we maken user stories op functionele behoefte en dan beantwoorden we deze vraag.
