### ISSUE TITLE
Als Product Owner wil ik een prototype van materiële en formele historie op een resource

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#472]
...zodat we kunnen beoordelen of de besproken oplossing in de praktijk gaat werken.

Heeft relatie met: #459 #460 #459 

Besproken:
- aansluiten bij oplossing zoals voorgeschreven voor RGBZ, beter gezegd StUF
- query parameters:
  - parameter om "vertrekdatum" / "offset" / "viewpoint" voor request naar bepaald tijdstip te zetten (default: now() )
  - parameter om de situatie van bepaald tijdstip gezien vanaf datum viewpoint te bezien (default: now() )
  - parameter om aan te duiden of formele en/of materiële historie in antwoord wenselijk is (default: materiële situatie nu met begindatum)

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
@ArjanKloosterboer @sergei-maertens @CMasselink @michielverhoef Is deze user story correct beschreven?

**Comment by TCIMEddy** [comment]
Mooie user story, ik denk dat ik weet wat wordt bedoelt. Kun je als toelichting een voorbeeld uit de praktijk noemen?

**Comment by ArjanKloosterboer** [comment]
@TCIMEddy, Praktijkvoorbeelden:
- als zaakcoordinator wil ik weten of en wanneer de vertrouwelijkheidaanduiding van de zaak gewijzigd is zodat ik er achter kom hoe  het toch kan zijn dat alle informatie over de zaak met iedereen is gedeeld. 
- als zaakcoordinator wil ik weten wanneer document X aan de zaak gerelateerd is zodat ik kan achterhalen hoe het toch komt dat dat we, bij de behandeling van de zaak, niet tijdig rekening hielden met hetgeen in dat document gesteld is. 
- als klantcontacter wil ik weten of de geplande einddatum van de zaak gewijzigd is zodat ik de klant te woord kan staan die op grond van eerder ontvangen informatie meent dat de einddatum al lang verstreken is. 
Zoiets?

**Comment by michielverhoef** [comment]
> Gegevens over wat er met een object gebeurd is zijn toch een wezenlijk andere soort gegevens dan de objectgegevens zelf.

Dat klopt. Voor zover ik het begrepen heb is formele historie het moment waarop een wijziging vastgelegd is. Ik zou daarom jouw definitie iets aanpassen:

* formele historie: wat is er wanneer gewijzigd / _is_ een bepaalde wijziging _vastgelegd in het systeem_ - dit is meer 'meta'.

Eigenlijk is dit de commit date van de wijziging.

Nu ik dit schrijf bedenk ik me dat het dus kan zijn, verwacht ik, dat formele historie voor dezelfde materiële historie verschilt per systeem of organisatie. Hiermee bedoel ik dat een verhuizing (op 2 januari)  op 5 januari vastgelegd kan zijn in de gemeente waar ik naar toe verhuisd ben en op 6 januari bij de gemeente waar ik uit weg verhuisd ben.
Of kan dit niet?

**Comment by CMasselink** [comment]
Ik zie inderdaad ook 2 features: 

-Wat was de situatie op een bepaald moment in de tijd
-Op welk moment is een bepaald gegeven / informatieobject gewijzigd/ontstaan

De praktijkvoorbeelden van Arjan gaan volgens mij over het 2e punt. 
Userstory  #459 gaat over het eerste punt.

**Comment by sergei-maertens** [comment]
> Nu ik dit schrijf bedenk ik me dat het dus kan zijn, verwacht ik, dat formele historie voor dezelfde materiële historie verschilt per systeem of organisatie. Hiermee bedoel ik dat een verhuizing (op 2 januari) op 5 januari vastgelegd kan zijn in de gemeente waar ik naar toe verhuisd ben en op 6 januari bij de gemeente waar ik uit weg verhuisd ben.
Of kan dit niet?

Dat lijkt me geheel realistisch.

**Comment by ehotting** [comment]
Ik denk niet dat dit het geval is, volgens mij is (in dit voorbeeld) de _verhuizing_ geen object, alleen de melding ervan (alleen in gemeente waar je heen verhuist), de zaak (alleen in gemeente waar je heen verhuist, evt. een gerelateerde zaak met ander doel en dus andere historie in gemeente waar je vandaan komt, en de relatie 'woonadres' tussen een persoon en een adres (allebei levend in slechts 1 registratie tegelijk. Volgens mij is de essentie van "bevragen bij de bron" nu juist dat dit soort dingen niet meer fout gaat.

**Comment by joeribekker** [comment]
Bevragingen ingeschreven personen pakt dit als volgt op: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#opvragen-van-historie-kan-via-specifieke-endpoints

**Comment by Hugo-ter-Doest** [comment]
Als PO wil ik niet eerst een prototype (laten) maken, maar direct de stap van user stories voor medewerkers en burgers/bedrijven naar functionaliteiten in de ZGW API's maken.
