### ISSUE TITLE
Als zaak coördinator wil ik de behandelaar van een zaak kunnen aanpassen..

### ISSUE THREAD

**Issue by MarcelMoerman** [VNG-Realisatie/gemma-zaken#503]
...zodat ik bij een verkeerd toegewezen zaak deze opnieuw kan toewijzen. 
De routering van zaken naar de behandelaars gaat voor een groot deel geautomatiseerd op basis van Zaaktype en categorie. Bij een foute categorisering kan dit betekenen dat een zaak naar de verkeerde behandelaar wordt doorgezet, bij een wijziging wordt alleen de behandelaar gewijzigd. 
Categorie blijft ongewijzigd.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting Graag prioriteit aangeven

**Comment by TCIMEddy** [comment]
@sergei-maertens @joeribekker Is dit niet al mogelijk?

**Comment by ehotting** [comment]
Kan nu nog niet idd, zie https://ref.tst.vng.cloud/zrc/api/v1/schema/#tag/rollen 

Een update / delete is daar wel wenselijk, maar dan ook een begin en einddatum van de relatie tussen betrokkene en zaak (rol) ... Je moet achteraf (bijv in bezwaartraject) kunnen zien wie op welk moment de behandelaar was etc.

Wil wel prioriteren maar is volgens mij nog niet helemaal ready for sprint.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest is dit nodig voor Release candidate?

**Comment by sergei-maertens** [comment]
Het muteren van rollen/betrokkenen moet in de audit trail opgenomen worden #722

**Comment by joeribekker** [comment]
`rol_delete` is er overigens ook nog niet. Die moet worden toegevoegd.

We moeten documenteren dat je bij relaties niet de koppeling zelf mag aanpassen (dus bijv. persoon vervangen door ander persoon) maar WEL de toelichting bijvoorbeeld.

Sergei geeft ook aan dat validatie op aantal initiators e.d. ook nog gemaakt moet worden.

**Comment by joeribekker** [comment]
> Sergei geeft ook aan dat validatie op aantal initiators e.d. ook nog gemaakt moet worden.

Nieuw issue voor aangemaakt: #1190 

Rollen kunnen reeds verwijdert worden waarmee behandelaar kan worden aangepast.
