### ISSUE TITLE
Als gemeente Utrecht wil ik de documenten die opgeslagen worden via de DRC op kunnen slaan in ons gemeentelijk DMS

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#506]
zodat we als gemeente niet meerdere DMS'en hoeven te beheren en ondersteunen.

**Beschrijving**
Als gemeenten willen we functionaliteit 1 keer realiseren en vervolgens hergebruiken. Zo ook DMS functionaliteit. De documentregistratiecomponent moet daarom kunnen aansluiten op bestaande DMS oplossingen. Het aansluiten van de documentregistratiecomponent op een DMS kan via de open internationale standaard CMIS. Onder andere Alfresco (ook open source), wat veel gebruikt wordt bij gemeenten, ondersteunt de CMIS standaard.

**Gewenste aanvulling op de APi:**
Aanvullen van de OAS specificatie met attributen die nodig zijn om de vanuit de user story's gewenste CMIS calls te doen.

**Tabel met missende attributen in OAS**

Attribuut-RGBZ | CMIS attribuut
-- | --
Bestandsnaam | cmis:contentStreamFileName

Naast de verplichte CMIS attributen, moeten alle attributen voor metadatering zoals uit userstory #540 naar voren komen, geregistreerd kunnen worden.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] ~~er is een OAS 3.0 specificatie~~
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] ~~de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze~~
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0 / TMLO
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen velden metadataprofiel [Constantijn]
- [ ] Zorgen voor TMLO compliant metadataprofiel
- [ ] Schrijven (unit) test voor referentie-implementatie [Joeri/Sergei]
- [ ] Implementeren in referentie-implementatie [Joeri/Sergei]
- [ ] ~~Genereren/opstellen van OAS 3.0 
- [ ] Functionele documentatie [Constantijn]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [Joeri/Sergei]

**Comment by TCIMEddy** [comment]
@CMasselink en of @joeribekker  kun je ook globaal de oplossing beschrijven. Er is denk ik geen architectuurschets en mapping rgbz. Wat is de gewenste (aanvulling op de) functionaliteit van de API's ?

**Comment by CMasselink** [comment]
> 
> 
> @CMasselink en of @joeribekker kun je ook globaal de oplossing beschrijven. Er is denk ik geen architectuurschets en mapping rgbz. Wat is de gewenste (aanvulling op de) functionaliteit van de API's ?

Ik heb de userstory iets bijgewerkt. Mapping RGBZ kan wel relevant zijn voor het standaard metadataprofiel wat we in de DMS willen inrichten.

**Comment by TCIMEddy** [comment]
@CMasselink dank voor de toevoeging. Nog 1 vraagje als deze user story/api wordt gerealiseerd, gaan jullie hem dan implementeren..?

**Comment by CMasselink** [comment]
@TCIMEddy voor de volledigheid ook nog even hier: wij gaan deze API  dan inderdaad op korte termijn implementeren, sterker nog: we wachten met smart op dergelijke functionaliteit.

**Comment by ehotting** [comment]
Aangezien CMIS voor de huidige ZDS voorgeschreven is zouden de bestaande systemen het moeten ondersteunen, via SOAP/XML services. Wat dat betreft wenselijk. Heb er eerder naar gekeken, er is geen goede API beschreven bij de CMIS zelf.  Ik kan daarom niet overzien wat de conseqenties zouden zijn, technisch gezien. Om deze user story in te vullen is volgens mij slechts een heel klein deel van CMIS nodig, maar hoe het in de OAS terecht zou kunnen komen, ik heb geen idee. Iets om morgen tijdens back log refinement te bespreken?

Zaken die direct door een partij geïmplementeerd worden  (MOR Amsterdam, CMIS Utrecht) krijgen voorrang op de backlog, mits we ze ready voor sprint krijgen.

**Comment by joeribekker** [comment]
Middels een snelle scan kom ik op 2 verplichte attributen voor CMIS. Dit staat los van eventuele ZSDMS-attributen en TMLO-attributen:

```
cmis:path => '/Sites/archief/documentLibrary/998877/2017/08/14/123456789',
cmis:contentStreamFileName => 'document.pdf'
```

We hebben dus minimaal nodig:

zaakidentificatie, zaaktype, zaak aanmaak datum, bestandsnaam informatie object

Extra attribuut in het DMS zal het/een ID moeten worden die het DRC er aan geeft/kan gebruiken om een document kan identificeren.

**Comment by ArjanKloosterboer** [comment]
Ik heb slechts beperkte kennis van CMIS. Ik baseer me op hetgeen vermeld is in de '[Standaard Zaak
- en Documentservices 1.2](https://www.gemmaonline.nl/images/gemmaonline/0/0e/Specificatie_Zaak-_en_Documentservices_v1.2.pdf)'. @michielverhoef, lees en reageer jij ook, svp.?  
Ik zie twee aanknopingspunten: de 'Zaken DMS boom' (par. 5.1) en de 'Mapping RGBZ-attributen met CMIS-properties' (par. 5.3). 
In genoemde boom komen vier RGBZ2-gegevens voor: Zaaktype.Zaaktypeidentificatie, Zaak.Zaakidentificatie en Enkelvoudig_document.Bestandsnaam.Naam en .Extensie. Vreemd genoeg zouden er volgens het voorgaande comment meer gegevens van toepassing zijn. Het is mij onbekend hoe cmis:path zich verhoudt tot genoemde boom.
Dit is een RGBZ1-gebaseerde boom. In RGBZ2 is de unieke aanduiding van een zaak uitgesplitst naar Zaakidentificatie en Bronorganisatie. Aangezien iedere gemeente z'n eigen boom zal hebben zal de huidige boom voor één gemeente nog wel werken maar in een gegevenslandschap waar ook documenten van andere gemeenten benaderbaar zijn, lijkt mij die Bronorganisatie wel van belang. Verder, die boom is enkel opgesteld voor enkelvoudige informatieobjecten, geen rekening is gehouden met samengestelde informatieobjecten. M.i. moet er dan ook opnieuw nagedacht worden over de structuur van die boom. 
V.w.b. RGBZ-attributen vermoed ik dat het primair gaat om die attributen waarvoor een cmis-element bestaat. Het gaat dan om (zie par. 5.3): 
- cmis:name (Zaaktype) > Zaaktype.Zaaktypeidentificatie
- cmis:name (Zaakfolder) > Zaak.Zaakidentificatie en wellicht dus iets met Zaak.Bronorganisatie
- cmis:name (EDC) > Informatieobject.Titel; het is mij niet duidelijk waarom dit niet Informatieobject.Informatieobjectidentificatie zou moeten zijn.
- cmis:contentStreamFileName (EDC) > concatenatie van Enkelvoudig_document.bestandsnaam.naam, een '.' en Enkelvoudig_document.bestandsnaam.extensie
- cmis:contentStreamMimeType (EDC) > Enkelvoudig_document.formaat
- Content-stream (EDC) > Enkelvoudig_document.Inhoud
Verder staan er in de mapping (tabel 3) diverse andere RGBZ-attributen (zsdms:...). Of die alle of voor een deel in de CMIS-communicatie moeten zitten (meerdere attributen zijn als verplicht gekenmerkt), dat weer ik niet. Ik vermoed dat Michiel daar wat van kan zeggen.

**Comment by Hugo-ter-Doest** [comment]
Dit wordt in een separaat project gerealiseerd.

**Comment by TCIMEddy** [comment]
@CMasselink Wij hoeven niet meer te doen toch?

**Comment by CMasselink** [comment]
@Hugo-ter-Doest de adapter wordt in een ander project gerealiseerd. De velden die nodig zijn voor een geldig CMIS bericht, moeten wel aanwezig zijn in de API.  Kern van de userstory zit dus hier in:
Gewenste aanvulling op de APi:
Aanvullen van de OAS specificatie met attributen die nodig zijn om de vanuit de user story's gewenste CMIS calls te doen.

**Comment by Hugo-ter-Doest** [comment]
Heb je het dan over metadata uit het RGBZ die nog ontbreekt of over CMIS-specifieke attributen?

Zou je de user story kunnen omschrijven en benodigde attributen kunnen toevoegen?
