### ISSUE TITLE
Als Adviseur informatiebeheer wil ik dat bij een zaaktype archiveringsparameters uitgelezen kunnen worden

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#520]
... als ook de verwijzing naar het desbetreffende item in de Selectielijst Archiefbescheiden ...
...zodat ik kan sturen op het toekennen van het juiste archiefregime (bewaren of vernietigen en de overbrengings- resp. vernietigingstermijn) bij het afronden van zaken en daarmee op de duurzame toegankelijkheid van 'zaakdossiers'... 
... en zodat duidelijk is hoe dit ontleend is aan de Selectielijst.

Het sturen op het archiefregime vindt vooral plaats d.m.v. het resultaattype van een zaaktype. Vastlegging hiervan maakt het mogelijk om bij afronding van een zaak een voorgeparametriseerd resultaat van die zaak te bepalen (en vast te leggen) waarop het archiefregime geautomatiseerd 'berekend' kan worden a.d.h.v. de archiveringsparameters bij het zaaktype. Daarmee krijgt de Adviseur informatiebeheer grip op de duurzame toegankelijkheid van de informatie over afgeronde zaken. 

Er zijn API's nodig voor het kunnen vastleggen en updaten van de desbetreffende gegevens bij een Zaaktype (incl. Resultaattype en meer) en voor het opvragen van die gegevens. V.w.b. het Zaaktype sec is dat v.w.b. het opvragen een aanvulling op de reeds bestaande API (zie ook samenhang met #513).
Vanwege beperking tot een behapbare omvang ('is klein genoeg') worden adhv. deze userstory vooralsnog alleen de opvraagmogelijkheden gerealiseerd. 

**Gegevens ('mapping') ImZTC**:
- ZAAKTYPE: Selectielijst_procestype, Archiefclassificatie;
- RESULTAATTYPE: alle (groep)attributen, relatie naar ZAAKTYPE en relatie 'bepaalt afwijkende vernietigingstermijn van ZAAK-INFORMATIEOBJECT-TYPE';
- ZAAK-INFORMATIETOBJECT-TYPE ARCHIEFREGIME. 

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] De gewenste (aanvulling op de) functionaliteit van de API's is duidelijk en beschreven
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] API's cq. operations voorzien in de behoefte van de userstory
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0 i.c. ImZTC 2.2 (incl. de daarin gespecificeerde businesslogica)
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Bepalen benodigde operaties op resources van API's [_verantwoordelijke_]
- [ ] Opstellen welke velden bij de resources en operaties horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@ehotting graag visie en prioriteit

**Comment by ehotting** [comment]
Deze userstory zorgt voor zeer gewenste uitbreiding van de API met attributen die in RGBZ2 gespecificeerd zijn.

Aan de hand van deze user story zorgen we voor het uitbreiden van de ZTC specificatie met READ mogelijkheden voor gewenste attributen  (slice) een andere keer maken we de CREATE/UPDATE.

**Comment by Hugo-ter-Doest** [comment]
Lijkt ready te zijn, maar laten we maandag kijken of dat zo is.

**Comment by Hugo-ter-Doest** [comment]
Is gereed.
