### ISSUE TITLE
Als Adviseur informatiebeheer wil ik dat de behandelaar van een zaak het resultaat daarvan kan vastleggen

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#521]
...zodat m.b.v. desbetreffende zaaktypegegevens (zie #520) het 'archiefregime' van de zaak (geautomatiseerd) bepaald kan worden en ik daarmee grip krijg op de duurzame toegankelijkheid van informatie over door collega's behandelde zaken.

Het 'archiefregime' van een zaak bepaalt of de informatie over deze zaak (het 'zaakdossier') bewaard of vernietigd moet worden en na welke periode het dossier overgebracht (of uitgeplaatst) moet worden (naar een archiefbewaarplaats) resp. vernietigd moet worden. Het zaaktype van de zaak bevat de parameters hiervoor, per resultaattype. Door bij afronding van de zaak één van deze resultaattypen te kiezen, kan geautomatiseerd het 'archiefregime' bepaald worden. Het bepalen van het resultaat kan door één van de zaakbehandelaren bij afronding van de zaak gedaan worden. Door deze werkwijze i.c.m. de parameters bij het zaaktype wordt grip verkregen op de duurzame  toegankelijkheid van informatie zonder dat de verantwoordelijken daarvoor dat zelf per dossier moeten gaan bepalen en vastleggen. 'Archivering by design', zogezegd.  

Er zijn API's nodig voor het kunnen vastleggen van de desbetreffende gegevens bij een zaak en voor het opvragen van resultaattypen bij het desbetreffende zaaktype. Daarnaast is een ('proces- of experience-) API wenselijk om op basis van een resultaat (van een resultaattype) bij een zaak (van een zaaktype) en de einddatum van die zaak de archiveringsparameters van die zaak te laten berekenen (zie ook #345).
Let op: een en ander ook voor sommige Informatieobjecten bij de Zaak. 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] De gewenste (aanvulling op de) functionaliteit van de API's is duidelijk en beschreven
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigingen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
- [ ] API's cq. operations voorzien in de behoefte van de userstory
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0 (incl. daarin gespecificeerde businesslogica)
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Bepalen benodigde operaties op resources van API's [_verantwoordelijke_]
- [ ] Opstellen welke velden bij de resources en operaties horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Gegevens RGBZ**:
- ZAAK: Procesobject, Selectielijstklasse, Procesobjectaard, Resultaattoelichting, Archiefnominatie, Archiefstatus, Archiefactiedatum, Startdatum bewaartermijn en relaties 'is van versie van ZAAKTYPE', 'heeft bij afronding RESULTAATTYPE' en 'kent INFORMATIEOBJECT';
- ZAAK-INFORMATIEOBJECT: Vernietigingsdatum.

**Gegevens ImZTC**: 
- ZAAKTYPE: unieke aanduiding, datums begin- en einde geldigheid;
- RESULTAATTYPE: Resultaattype-omschrijving, Procesobjectaard, Indicatie specifiek, Archiefnominatie, Procestermijn, Archiefactietermijn, datums begin- en einde geldigheid en relatie naar ZAAKTYPE en relatie 'bepaalt afwijkende vernietigingstermijn van ZAAK-INFORMATIEOBJECT-TYPE'.
- ZAAK-INFORMATIEOBJECT-TYPE ARCHIEFREGIME: Vernietigingstermijn.

**Comment by Hugo-ter-Doest** [comment]
Zetten van het resultaat is noodzakelijk voor zaakgericht werken en archiveren. Prio Hoog.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Is dit gerealiseerd? zo niet is dit dan noodzakelijk voor rc

**Comment by Hugo-ter-Doest** [comment]
Zetten van resultaat kan reeds.
