### ISSUE TITLE
Als medewerker Informatiebeheer wil ik dat metadata overeenkomstig het TMLO bij zaken en documenten vastgelegd kan worden

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/gemma-zaken#540]
...zodat ik in staat ben om m.b.v. één en dezelfde set metadata archiefbescheiden, zoals zaakdossiers en documenten, te kunnen beheren, te kunnen (laten) raadplegen en, indien van toepassing, over te brengen naar een archiefbewaarplaats.

heeft (wellicht relatie) met #276 

**RGBZ-mapping**
De mapping op het TMLO is vermeld in [dit document op GEMMA Online](https://www.gemmaonline.nl/images/gemmaonline/6/6d/VNG_-_Vergelijking_TMLO_1_1_-_RGBZ_2_0_-_v1_0_20181129.zip).

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_ (n.v.t.)
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
Kan nadat mappen is toegevoegd naar ready for sprint (en dus in sprint 7 opgepakt worden)

**Comment by ArjanKloosterboer** [comment]
Deze userstory is randvoorwaardelijk voor userstory #376, toch, @MarcoKlerks ?

**Comment by MarcoKlerks** [comment]
Ja, conformiteit aan het TMLO is een van de eerste dingen die een archiefdienst vraagt wanneer je als archiefvormer (= de gemeente) archief wil gaan overbrengen.

**Comment by TCIMEddy** [comment]
@ehotting graag prioriteit en visie

**Comment by ehotting** [comment]
Yep, hoge prio, we moeten nagaan welke attributen voor TMLO relevant / nodig zijn en zorgen dat deze in de API verplicht zijn - niet per sé bij aanmaken van dingen maar wel bij bereiken eindstatus. Mogelijk dus ook validatie / business rules. Hier is specifieke kennis van TMLO voor nodig.

**Comment by wishalg** [comment]
De relatie TMLO-RGBZ en -ImZTC is uitgezocht en dat het TMLO geheel uit te drukken is in RGBZ+ImZTC. De mapping is [hier](https://www.gemmaonline.nl/index.php/Metadateren_van_zaakdossiers_conform_het_TMLO) vermeld. Met dien verstande dat hier nog sprake is van TMLO 1.1 terwijl TMLO 1.2 in bewerking is. In RGBZ 2 is al geanticipeerd op TMLO 1.2. En ook dat het RGBZ al businessrules bevat die afdwingen dat bepaalde TMLO-conforme gegevens van een waarde voorzien moeten zijn bij het afronden van de zaak.

**Comment by ehotting** [comment]
Idd zoals gezegd bij backlog refinement, @ArjanKloosterboer heeft dit al helemaal uitgezocht. Dat document moet idd gebruiktworden.

**Comment by ArjanKloosterboer** [comment]
Ik heb het TMLO-mapping-document geupdated naar RGBZ 2.0.2 en ImZTC 2.2 en de verwijzing naar deze mapping vermeld in de beschrijving van de user-story bovenaan. En het vinkje bij RGBZ-mapping gezet.
