### ISSUE TITLE
Als behandelaar van bezwaar zaken, wil ik zaken aan elkaar kunnen relateren

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#559]
zodat ik weet bij welke vergunningszaak/besluit de bezwaarzaak hoort en ik een compleet overzicht van het dossier heb.

**Toelichting / beschrijving functionaliteit**
De wens is om te kunnen aangeven dat een zaak aan een andere zaak gerelateerd is. Je wilt bijvoorbeeld kunnen aangeven op welke vergunningsaanvraagzaak een bezwaar betrekking heeft.
Naast het leggen van de relatie tussen zaken, moet het tevens mogelijk zijn om op te vragen of en aan welke zaken een zaak gerelateerd is.

**RGBZ mapping**
Relatiesoort: ZAAK heeft betrekking op andere ZAAKen
ZAKENRELATIE . Aard relatie: enumeratie: vervolg, onderwerp, bijdrage.

Toelichting op aard van de relatie:
Aard relatie: 'Omschrijving van de aard van de relatie van de andere ZAAK tot de (onderhanden) ZAAK'. Heeft de volgende enumeratie: vervolg (De andere zaak gaf aanleiding tot het starten van de onderhanden zaak), onderwerp (De andere zaak is relevant voor cq. is onderwerp van de onderhanden zaak), bijdrage (Aan het bereiken van de uitkomst van de andere zaak levert de onderhanden zaak een bijdrage).
De relatie van een deelzaak tot een zaak is een aparte relatie.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [x] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _~~**Userstory is ingevuld op template architectuurschets**~~_
- [x] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [x] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de functionele specificatie is gepubliceerd leesbaar
- [ ] de technische specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)
- [ ] review heeft plaatsgevonden (dus reviewers hebben voldoende en vindbare info om te kunnen reviewen (dus duidelijke verwijzing in issue/user story naar deze documentatie)
- [ ] wijzigigen als gevolg van user story zijn vindbaar en gedocumenteerd
- [ ] functionele documentatie is gereviewd door developers (lees is techniek in overeenstemming met functionele documentatie)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een gerelateerde zaak horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by CMasselink** [comment]
@ehotting zou je deze kunnen prioriteren?

**Comment by ehotting** [comment]
Waarom is het voor consumer software relevant om die 'aard relatie' te kennen? Het betreft toch gewoon een relatie naar een object, waarbij de inhoud vna het object bepaalt hoe de consument het moet tonen? Wel eens dat de relatie gelegd moet kunnen worden, maar de nadere duiding van de user story kan ik niet helemaal volgen

**Comment by CMasselink** [comment]
@Eelco: Het betreft een relatie tussen twee zaken. Enkel het feit dat er een relatie ligt tussen twee zaken, is niet altijd voldoende. An een bezwaarzaak kunnen bijvoorbeeld meerdere zaken gerelateerd zijn maar je wilt snel kunnen zien wat nou de vergunningszaak is waar het bezwaar betrekking op heeft.
Hetzelfde geldt eigenlijk voor bestuurlijke besluitvorming. Bestuurlijke besluitvorming bestaat vaak uit een aantal vervolgzaken.
Als je alleen de relatie vast legt, mist een behandelaar dus nuttige informatie en zal die in het geval er meerdere zaken aan een bezwaarzaak hangen, langer moeten zoeken naar de juiste informatie.

**Comment by ehotting** [comment]
De consumer kan toch het gerelateerde object bevragen, en wanneer dit een zaak betreft, hiervan alle relevante info ophalen en deze op een andere wijze in de client software tonen dan wanneer het een anderssoortig object is?

**Comment by CMasselink** [comment]
Hoe zou een client moeten kunnen weten/weergeven dat er een volgordelijkheid in zaken zit (bijvoorbeeld bij vervolgzaken) als dat niet expliciet is aangegeven? Ik betwijfel of je die informatie altijd op basis van informatie uit een zaak of zaaktype kan halen.

De functionele vraag is dat we zaken aan elkaar kunnen relateren en daarbij kunnen zien op welke manier de zaken zich tot elkaar verhouden (is het een vervolg, gaat de te behandelen zaak over een andere zaak, of wordt er een bijdrage geleverd aan een andere (externe) zaak)
Als dat op een andere manier kan dan via aardRelatie vind ik dat prima, maar op dit moment voorziet RGBZ dus met Aardrelatie in deze functionele behoefte.

**Comment by ehotting** [comment]
@CMasselink @TCIMEddy Nog geen prio gegeven omdat ik het nog niet voldoende begrijp.
Volgens mij trappen we met deze 'aardrelatie' in de valkuil van iets in de API op te willen lossen wat in feite proces-of domeininformatie is. Dit behoort in de client thuis en de informatie die daarvoor vastgelegd wordt, elders. Ik probeer me een beeld te vormen van hoe client software en API's zich tot elkaar verhouden. Door de user story te prioriteren en uit te voeren in huidige vorm, is er geen ruimte om na te denken over een betere oplossing.

**Comment by ehotting** [comment]
Wil het graag even irl bespreken met @CMasselink en @jgortmaker1

**Comment by CMasselink** [comment]
Prima, dan reageer ik inhoudelijk even niet meer via dit kanaal. Resultaat van de afstemming leggen we wel vast bij deze userstory.

**Comment by TCIMEddy** [comment]
@CMasselink Ik heb overleg nodig er afgehaald. Deze user story staat op de baaklog moet er nu iets mee gebeuren? @ehotting Prio?

**Comment by ArjanKloosterboer** [comment]
V.w.b. de RGBZ-mapping, de tweede regel moet zijn: ZAKENRELATIE . Aard relatie. 
Vooruitlopende op deze aanpassing heb ik het vinkje alvast gezet.

**Comment by CMasselink** [comment]
@Hugo-ter-Doest We hebben deze functionaliteit vanuit de huwelijksplanner nodig, daarom wil ik deze user story weer even onder jou aandacht brengen.

**Comment by Hugo-ter-Doest** [comment]
Wordt aangevuld met een toelichting veld voor de relatie.

**Comment by Hugo-ter-Doest** [comment]
Meenemen in sprint 12

**Comment by joeribekker** [comment]
RGBZ:

![image](https://user-images.githubusercontent.com/96970/57454031-2f76f080-7268-11e9-8a5f-656c94df3a12.png)

**Comment by Hugo-ter-Doest** [comment]
Dit kan al met attribuut `relevanteAndereZaken`

**Comment by joeribekker** [comment]
@stevenbal Graag help_text er in zetten.
