### ISSUE TITLE
Als beheerder ZTC ZRC etc wil ik bij een Roltype meerdere rollen kunnen opvoeren die dezelfde Omschrijving generiek hebben

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#592]
...zodat meerdere rollen Omschrijving generiek kunnen hebben.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Is een bug omdat uniciteit van omschrijving generiek wordt afgedwongen i.p.v. omschrijving. Ook met @joeribekker gechecked.

**Comment by sergei-maertens** [comment]
Hrm, in de code lijkt dit sinds augustus 2018 zo te zijn, moeten hier even verder verfijnen want waarschijnlijk begrijp ik het probleem niet.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest staat op Zeer Hoog + label Bug. In volgende sprint meenemen?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Bug en Zeer hoog moet deze dan niet in de sprint?
