### ISSUE TITLE
Als consumer wil ik als response op het aanmaken van een enkelvoudiginformatieobject een link terug krijgen

### ISSUE THREAD

**Issue by Waruzjan** [VNG-Realisatie/gemma-zaken#624]
...zodat deze link aan de gebruiker getoond kan worden. 

De link kan naar de pagina van de provider applicatie wijzen waar de net geregistreerde document te zien is. Of de link kan een interactief link zijn waarmee het document geopend en gewijzigd kan worden (bv webdav).

Huidige create van enkelvoudiginformatieobject bevat de mogelijkheid om een link mee te sturen, echter de consumer die enkelvoudiginformatieobject aanmaakt heeft het object natuurlijk nog niet opgeslagen, en wil juist van de provider de link terug krijgen die refereert naar het object opgeslagen bij de provider.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Eelco)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Na overleg is duidelijk dat het gaat om het link attribuut en om de flow gaat van ZAC naar documentcreatie naar DRC. De documentcreatie wil de link terugkrijgen naar de locatie vanuit het zaaksysteem (of client van de documentcreatie). De API weet niet van de ZAC, en er kunnen ook meerdere zijn. Kan dus op niveau van de API niet worden opgelost.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest wat moeten wij nog doen als het niet op het niveau van de API kan worden opgelost? Out of scope bord? close?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest wat moeten wij nog doen als het niet op het niveau van de API kan worden opgelost? Out of scope bord? close?
