### ISSUE TITLE
Als leverancier wil ik weten hoe de StUF ZDS standaard zich verhoudt tot de nieuwe API's

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#631]
...zodat ik de processen in mijn applicatie goed kan vertalen naar de nieuwe applicatie.

NB. Het idee is vergelijkingen te beschrijven tussen StUF en de nieuwe API's.

In eerste instantie heb ik Hugo en Robert geassigned, ik pak hem graag op.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Hugo)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest is de vergelijking die Joeri heeft gedaan antwoord op deze user story?

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat de vergelijk maar een deel van het verhaal is. We hebben gekeken of de functionaliteiten van de ZDS-operaties zijn te simuleren met ZGW API calls. En dat is grotendeels zo. Echter de vergelijking moet ook gaan over de architectuurcomponent. Immers ZGW API's hebben invloed op de architectuur van applicaties die eerst all-in-one waren.

**Comment by Hugo-ter-Doest** [comment]
De vergelijk staat hier: https://ref.tst.vng.cloud/overige/technisch/zds-vs-zgw

Met Michiel afgesproken dat hij dit stuk uitbreidt met het verschil wat betreft architectuur.

**Comment by michielverhoef** [comment]
De vergelijking in de repository: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/overige/technisch/zds-vs-zgw.md

**Comment by joeribekker** [comment]
@michielverhoef Volgens mij is dit ticket afgerond? Graag heropenen indien nodig.
