### ISSUE TITLE
Als developer wil ik een link naar API community Slack in de documentatie

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/gemma-zaken#633]
...zodat de community eenvoudig te vinden is.

Suggestie: Voeg Slack logo met link naar Slack invite toe naast Github logo in footer onder elke page in documentatie:
<img width="506" alt="screenshot 2018-12-05 at 21 32 21" src="https://user-images.githubusercontent.com/20684884/49542240-4e4a1300-f8d5-11e8-9161-ae58c7d408d9.png">

Slack invite: https://join.slack.com/t/vngapicommunity/shared_invite/enQtNDk1OTg5ODYwNjc1LTc0NTAxYWUzMGJmYjIxODQ2MGJmNDA4ZDk2YjNmNzI5NzU1MjAwMjllMTIwYjgxMjg1M2U0Zjg5N2QyOTkzZjI

& vermeld de relevante channels

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**

**Acceptatiecriteria**

**Taken**
- [ ] Slack logo toevoegen in footer documentatie met linkje naar Slack invite

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Graag prio

**Comment by Hugo-ter-Doest** [comment]
Prio hoog om input van levs te krijgen.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest dit zou toch eenvoudig moeten zijn?

**Comment by adgerrits** [comment]
Wou Ivo zijn aantekeningen ophalen die in Slack zijn geplaatst dus zou best handig zijn geweest als wat hier voorgesteld werd werkte.... ad-hoc invite voor nu?

**Comment by TCIMEddy** [comment]
PR gedaan met tekst op openingspagina + link en logo Slack. Structurele oplossing in #1051 (op de baaklog)
