### ISSUE TITLE
Als behandelaar in de TSA wil ik een melding krijgen dat er een document is toegevoegd aan de zaak

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#648]
...zodat ik de juiste actie kan ondernemen. 
Stel dat bijvoorbeeld een aanvrager een aanvullende tekening  op een WABO-zaak heeft aangeleverd en deze via het DMS is ingevoerd. Dan kan ik direct bepalen of ik voldoende stukken heb om de inhoudelijke toetsing te starten.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio?

**Comment by Hugo-ter-Doest** [comment]
Notificaties!

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Ik heb 1 label/epic notificatie gemaakt ongeacht klant of behandelaar

**Comment by joeribekker** [comment]
Scope hier wordt gedekt in https://github.com/VNG-Realisatie/gemma-zaken/pull/764 middels een POST/PUT op Documenten API resource ObjectInformatieObject en/of Zaak API resource ZaakInformatieObject.

**Comment by joeribekker** [comment]
Kapstok US #792 dekt dit af, minus de taak/afhandel-applicatie functies die out-of-scope zijn.

Let wel dat er niet eens een abonnement op de Documenten API hoeft worden genomen, omdat relaties ook op de Zaken API als event worden gepubliceerd.
