### ISSUE TITLE
Als applicatiebeheerder van de Taak Specifieke afhandelapplicatie wil ik een melding hebben dat de zaak vernietigd moet worden op basis van de vernietigingslijst 

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#651]
...zodat ik de zaak kan verwijderen

TSA = Taak Specifieke Afhandelapplicatie

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest prio en visie

**Comment by Hugo-ter-Doest** [comment]
Eerst als ophalen vernietigingslijst realiseren, later eventueel notificaties.

**Comment by TCIMEddy** [comment]
In meerdere applicaties

**Comment by TCIMEddy** [comment]
Opdelen in meerder user stories

**Comment by Hugo-ter-Doest** [comment]
Toevoeging t.a.v. TSA: de vernietiging van de zaak werkt door in de TSA. Daar zijn ook gegevens die aan de zaak gerelateerd.

**Comment by RitaBerghuis** [comment]
Deze userstory roept bij ons de vraag of vernietiging door de applicatiebeheerder van een taakapplicatie uitgevoerd zou moeten worden. Is de applicatie er tegen die tijd nog wel? En zal vernietiging geen automatisch proces zijn?

**Comment by johannesbattjes** [comment]
Het is waarschijnlijk dat er gegevens over de zaak aanwezig zijn in een afhandelcomponent ook al staan de zaakgegevens elders opgeslagen. Bijvoorbeeld (links naar) procesgegevens, (links naar) contactgegevens van aanvragers en adviseurs, zaakgegevens die niet in de zaakregistratie passen, .. Deze moeten ook in de afhandelapplicatie verwijderd worden als de zaak in de zaakregistratie verwijderd worden. Ook als dit automatisch gaat moet er een signaal komen naar de afhandelcomponent dat het tijd is de gegevens te verwijderen.

**Comment by CMasselink** [comment]
Ik vraag me wel af of dit soort taken vanuit de ZDS API's opgelost moeten worden. Ik zie meer een RM applicatie voor me die de vernietigingstermijnen van zaken in de gaten houdt en taakapplicaties op de hoogte stelt dat informatie behorende bij een zaak vernietigd moet worden.

**Comment by Hugo-ter-Doest** [comment]
Is de verantwoordelijkheid van de TSA dan wel RMA.

**Comment by Hugo-ter-Doest** [comment]
Dit kan inmiddels met #347 om een lijst met te vernietigen zaken op te halen en #349 om zaken daadwerkelijk te vernietigen. 

Voor de duidelijkheid: de TSA of RMA-applicatie krijgt dus geen melding, maar is zelf aan zet om een zaakdossier tijdig te vernietigen. De functionaliteit hiervoor is aanwezig in de API's.
