### ISSUE TITLE
Als behandelaar in de TSA wil ik zien op basis van welke product uit de PDC de zaak is aangemaakt en dit ook kunnen wijzigen

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#652]
...zodat ik weet op basis van welke afspraak met een ketenpartner ik de zaak moet afhandelen.
Voorbeeld: twee producten leiden tot een zaak van het zaaktype "advies leveren". Het ene product is "advies geluid" het andere is "advies geur". Op basis van het product kan ik zien wat ik moet doen. 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_** (mag alleen afgevinkt worden door Arjan)
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_** (mag alleen afgevinkt worden door Jeffrey)
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.
- [ ] Er zijn geen bekende RGBZ tegenstrijdigheden of afwijkingen zijn vastgelegd

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest visie en prio

**Comment by Hugo-ter-Doest** [comment]
Om dit mogelijk te maken moeten we de relatie met de PDC goed neerzetten. Zaaktypen kunnen naar meerdere producten/diensten wijzen, op moment van creeren van een zaak van bepaald zaaktype kies je dan één van deze producten/diensten.

Daarnaast is het zo dat naar een product/dienst ook als uri moet worden verwezen.

**Comment by johannesbattjes** [comment]
@johannesbattjes sluit dit aan?
=> Ja. Als het mogelijk is een een verwijzing naar een product/dienst toe te voegen aan een zaak is dat voldoende denk ik. Dit hoeft alleen niet per se op het moment van creeren van de zaak maar kan ook later.

**Comment by Hugo-ter-Doest** [comment]
Duidelijk. Is een mooie user story en gaan we een oplossing voor bedenken.

**Comment by Hugo-ter-Doest** [comment]
Zie ook #925

**Comment by sergei-maertens** [comment]
Zaken en Zaaktypen hebben een lijst van `productenOfDiensten`, er is validatie in ZRC dat `Zaak.productenOfDiensten` een subset is van `Zaak.ZaakType.productenOfDiensten`
