### ISSUE TITLE
als externe wil ik een zaak kunnen updaten zonder alle details van de zaak te kunnen zien

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/gemma-zaken#66]
...zodat ik de privacy van mensen niet schendt.

In het sociaal domein zitten mensen aan keukentafels (wijkverpleegkundigen) die geen ambtenaren zijn maar wel ketenpartner.

Dit is een concreet voorbeeld van #26 

[Architectuurschets](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/processen/rotterdam-samenloop.md)

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Acceptatiecriteria**
Uit de algemene uitgangspunten:

- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Definition of done**

- [ ] er is een OAS 3.0 specificatie, afgestemd met leveranciers van ZRC/e-Suite
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd

**Taken**
- [x] Opstellen architectuurschets [@RvdKlip]
- [x] Opstellen welke velden bij een melding horen [@RvdKlip]
- [ ] Taak toegevoegd: Initiele levering mappen op RGBZ [@michielverhoef]
- [ ] Aanleveren testdata [@RvdKlip]
- [ ] Schrijven (unit) test voor referentie-implementatie [@joeribekker]
- [ ] Implementeren in referentie-implementatie [@joeribekker]
- [ ] Genereren/opstellen van OAS 3.0 [@joeribekker]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [?]

**Comment by ArjanKloosterboer** [comment]
Ik neem aan dat bedoeld is "als medewerker van een door de gemeente gemandateerde (uitvoerings-)organisatie wil ik een lopende zaak rechtstreeks bij de gemeente kunnen updaten".
M.i. is dit een oplossing voor een generieker geformuleerde user-story: hoe werken we samen als gemandateerde en opdrachtgever? I.h.k.v. de uitvoering van de Omgevingswet is dit onderzocht onder de noemer 'zaakgericht samenwerken', Zie de [rapportage](https://aandeslagmetdeomgevingswet.nl/publish/pages/129842/bijlage_4d_-_samenwerkings-infoarchitectuur_-_v1_0_5_2017-11-14.pdf) hierover. Daarin staat een andere oplossing voor de achterliggende vraagstelling cq. user-story: elke organisatie voert zijn eigen zaken uit en 'zaken communiceren met elkaar'.

**Comment by jgortmaker1** [comment]
eens. zie ook: https://www.gemmaonline.nl/index.php/Zaakgericht_werken_in_de_keten

Voorstel: afvoeren

**Comment by RvdKlip** [comment]
Dank Arjan, dit is inderdaad hoe de US bedoeld is. Ik denk bijvoorbeeld aan medewerkers bij gecontracteerde zorgpartijen, of consultatie van brandweer in een bouw/vergunningproces, e.d. Neem je suggestie dus over in de US beschrijving. 

M.i. zal in de uitwerking de nadruk daarom vooral liggen op de wijze van autoriseren van medewerkers van ketenpartijen en de methode waarop ketenpartijen de interface/api kunnen benaderen.

De US is niet specifiek voor DSO en ik merk dat het label DSO telkenmale een bepaalde reactie op roept. In sprint 0 hebben we dit label ter herkenning gehangen aan bepaalde US's, maar (dacht ik) niet met de bedoeling een US uitsluitend voor DSO ten uitvoer te brengen. 
 
Voorstel: US behouden en DSO label er af halen.

**Comment by TCIMEddy** [comment]
@RvdKlip @ehotting ik begrijp je opmerking maar als je label er af haalt wordt de us wellicht te groot. Het is juist de bedoeling om de us zo specifiek mogelijk te maken om het in 1 sprint te kunnen maken. Ik ben geen deskundige maar als je deze us algemeen maakt wordt het veel te groot.

**Comment by ehotting** [comment]
Dit is een interessante user story om design choices uit de https://github.com/VNG-Realisatie/gemma-zaken/projects/1?card_filter_query=label%3Aautorisatie user stories aan te toetsen. Vermoedelijk leidt autorisatie op dit niveau vrij snel tot explosie van aantal scopes. 

Wat mij betreft deze user story betrekken / overwegen bij uitvoering #424  - afhankelijk van wenselijkheid consequenties daadwerkelijk realiseren.

**Comment by Hugo-ter-Doest** [comment]
Ik sluit deze US omdat organisaties niet samen aan dezelfde zaak gaan werken. Zoals Arjen aangeeft hebben organisaties hun eigen zaken en leggen we relaties tussen deze zaken.
