### ISSUE TITLE
Als (potentieel) teamlid wil ik de productvisie kennen

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#70]
... zodat voor mij helder is aan welk product wordt gewerkt en wat hiermee wordt bereikt - en ik kan besluiten om hier aan mee te werken.

**Definition of done**
- [x] Er is een productvisie
- [ ] Het scrumteam heeft de productvisie goedgekeurd
- [x] De productvisie is gepubliceerd

**Acceptatiecriteria**
Productvisie beschrijft helder:
- [x] Welke probleem lost het product op?
- [x] Welke voordelen levert het op voor de doelgroep?
- [x] Wie zijn de belangrijkste gebruikers van het product?
- [x] Waarom maken we het product?
- [x] Hoe ziet het ideale eindproduct eruit? Wanneer is het een succes?
- [x] Wat zijn de belangrijkste (onderscheidende) eigenschappen van het product?
- [x] Wat draagt het product bij aan de doelstellingen van de Common Ground visie?

**Taken**
- [x] Aanleveren input [**allen**]
- [x] Opstellen productvisie [@ehotting]
- [x] Vaststellen productvisie [@ehotting]
- [x] Productvisie prominent in README.md plaatsen [@ehotting]

**Comment by ehotting** [comment]
**Feedback nog te verwerken:**
- stukje over transitie
- eerst nieuwe wereld
- produvtvisie toegevoegde waarde en huidige wijzigen in ramdvwd
- combinatie zaak en documentservices splitsen
- definitie referentie-implementatie
- verdor Looking
- score wat we opleveren nog onduidelijk
- Government inregenen
- beheer inregenen
- DSO alleen oplossing aanbieden

**Comment by ehotting** [comment]
Overigens is doel van de productvisie vooral om het team te richten. Mag geen onduidelijkheid zijn over het probleem wat opgelost wordt.

**Comment by ehotting** [comment]
Work in Progress: https://github.com/VNG-Realisatie/gemma-zaken/pull/96
Graag reviews.

In meer leesbare vorm, het document zoals voorgesteld in Pull Request #96 :
https://github.com/VNG-Realisatie/gemma-zaken/blob/2709d257f855c1e4f2bf6fd3a0a7e3946f47ebdc/docs/content/introduction/productvisie.md

**Comment by ehotting** [comment]
Heb een Definition of Done, acceptatiecriteria en taken toegevoegd. 
Uitgaande van deze acceptatiecriteria valt er nog wel e.e.a. te verbeteren. :)

**Comment by TCIMEddy** [comment]
@ehotting wat mij betreft heeft iedereen ruim de tijd gehad om te reviewen. Blijft uiteraard altijd mogelijk via Github. Kan wat mij betreft op done (close)

**Comment by ehotting** [comment]
Klinkt goed, neem ik mee
