### ISSUE TITLE
Als projectgroeplid wil ik graag duidelijke afspraken over de governance en aanpak

### ISSUE THREAD

**Issue by BoerBas** [VNG-Realisatie/gemma-zaken#72]
Zodat ik weet wat er van mij verwacht 

**Definition of done**
- [x] Er is een beschrijving van de taken en rollen
- [x] De product owner is akkoord
- [x] De governance is gedeeld in Slack

**Acceptatiecriteria**
Punten die dienen te zijn beschreven in de governance:
- [x] Beschrijving van de rollen
- [x] Beschrijving van de rollen en taken
- [x] Beschrijving van de (globale) scope van de opdracht
- [x] Minimaal benodigde uren per rol
- [ ] Overzicht van relevante stakeholder
- [x] Overzicht van de geplande afspraken
- [x] Wie heeft waar rechten toe (Slack en Github)
- [ ] Issue #84 is expliciet geadresseerd
- [x] Iedereen in het scrumteam weet wat er van hem/haar verwacht wordt

**Taken**
- [x] Aanleveren input [**allen**]
- [x] Opstellen Governance [@WouterBRu]
- [x] Governance plaatsen in Slack[@WouterBRu]

**Comment by BoerBas** [comment]
ideeën:
- uren besteding
- wat doen wij en wat niet
- hoe andere te betrekken, leveranciers en gemeenten
- rollen en verantwoordelijkheden
- frequenties van afspraken
-...

**Comment by ehotting** [comment]
Issue #84 moet hier ook worden geaddresseerd

**Comment by ehotting** [comment]
Waar is het stuk wat we kunnen reviewen?

**Comment by EdwinCoster** [comment]
(dit is Eddy op account Edwin) Het stuk heb ik hier niet toegevoegd. Wist niet hoe dit moest maar staat op slack in thread SCRUM. Ik zal het nog een keer proberen hier

**Comment by TCIMEddy** [comment]
[rolverdeling en governance 22062018.pptx](https://github.com/VNG-Realisatie/gemma-zaken/files/2130817/rolverdeling.en.governance.22062018.pptx)
