### ISSUE TITLE
Als medewerker Informatie beheer wil ik een audit trail kunnen aanleggen op wijzigingen op zaken en bijbehorende API's (ZRC, DRC).

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#722]
zodat ik me kan verantwoorden over wat er met de zaak gebeurd is. Zie ook eventgeschiedenis.

Gevraagde functionaliteit:
Er moet zichtbaar zijn, wie, wat en wanneer gewijzigd heeft bij een zaak.

Vooralsnog: audittrail maken we opvraagbaar bij ZRC + DRC. De gebruiker/medewerker die de wijziging gedaan heeft, moet in de auditinformatie zichtbaar zijn.

Aanpak [hier](https://github.com/VNG-Realisatie/gemma-zaken/issues/722#issuecomment-486699664) te vinden.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by Hugo-ter-Doest** [comment]
Audit trail/event log pakken we op bij historie.

**Comment by joeribekker** [comment]
Aantal implementatie keuzes zijn te maken:

1. Audit trail centraal vastleggen in nieuw component
2. Audit trail centraal vastleggen door aanvulling NC (die veel/alle events al krijgt)
3. Audit trail per component opslaan
4. Audit trail buiten scope plaatsen en NLx verplichten
5. Audit trail buiten scope plaatsen en verantwoording bij clients leggen

Optie 3 heeft voor nu de voorkeur. Taakapplicaties kunnen dan evt. een volledige audit trail "samen stellen" door verschillende audit trails bij de componenten op te vragen en samen te voegen. Datum en tijd moeten dan wel goed worden opgeslagen in elk component :)

**Comment by hdksi** [comment]
Te langen leste mijn reactie op de vraag van Hugo om een toelichting op het document ‘Gemeentelijk Gegevenslandschap - Logging van verwerking van gegevens’ (verder handreiking logging) naar aanleiding van de discussie over logging, audit trails en historie tijdens de laatste backlogrefinementsessie.

**Logging in Gegevenslandschap vs. wensen voor audit trail**
Uit de handreiking logging: “De gemeente voert een register van verwerkingen waarin wordt vastgelegd welke (persoons)gegevens door de gemeente worden verwerkt, met welke doelbinding en welke grondslag. Dit register bevat minimaal de doelbindingen en grondslagen van de verwerkingen van persoonsgegevens maar is niet gelimiteerd tot slechts persoonsgegevens”.

Uit het definitieoverzicht van Hugo rondom historie/audit trail:
“De audit trail van een zaak is een overzicht van alle gebeurtenissen die m.b.t. 
een zaak hebben plaatsgevonden zodat duidelijk is hoe het proces van 
zaakafhandeling is verlopen en wie (welke medewerkers) welke acties heeft 
uitgevoerd. Wordt ook wel eens zaakhistorie genoemd.”

Volgens bovenstaande definitie geldt dat de hierboven bedoelde Audit trail ≠ het (minimale) register van verwerkingen de handreiking logging. De daarin bedoelde logs omvatten immers niet noodzakelijkerwijs alle gebeurtenissen, maar (minimaal) de gegevens die in het kader van de verwerking van persoonsgegevens relevant zijn. Of andersom uit een overzicht van _alle_ gebeurtenissen _altijd_ voor iedere verwerking van persoonsgegevens doelbinding en grondslag kunnen worden bepaald (bijvoorbeeld door ZTC-statussen via processtappen te matchen) is de vraag. En als dat zo is, is de volgende vraag zo’n afleiding wenselijk is, of dat bij API-calls expliciet de mogelijkheid moet bestaan om een doelbinding en grondslag mee te geven vanuit een verwerkingsregister.

**Verantwoordelijkheid voor logs**
In de handreiking logging wordt de verantwoordelijkheid voor het loggen van persoonsgegevens gelegd bij cliensystemen: “Ieder informatiesysteem is verplicht verwerkingen van persoonsgegevens te loggen.”

Om aan deze voorwaarde te kunnen voldoen moet ieder informatiesysteem uiteraard in ieder geval de verplichte doelbinding en grondslag kennen. Die moet dus met een API-call meegeleverd worden of van de inhoud daarvan afgeleid kunnen worden. Zie ook hierboven.

In de handreiking logging worden diverse inrichtingsvarianten besproken voor opslag en ontsluiten van loggegevens, uiteenlopend van één centrale (overheids-)loggingregistratie, tot aan een lokale en gefedeerde (iedere applicatie zijn eigen) loggingregistraties, en met en zonder NLx. In alle gevallen is sprake van één of meerdere registraties gespecialiseerd in het opslaan van loggegevens, en ligt de verantwoordelijkheid voor het genereren van die loggegevens bij de clientapplicaties.

Joeri schetst hierboven een aantal mogelijkheden voor het vastleggen van audit trails.

1. Audit trail centraal vastleggen in nieuw component
2. Audit trail centraal vastleggen door aanvulling NC (die veel/alle events al krijgt)
3. Audit trail per component opslaan
4. Audit trail buiten scope plaatsen en NLx verplichten
5. Audit trail buiten scope plaatsen en verantwoording bij clients leggen

De handreiking logging kiest dus voor een (mogelijke) combinatie van 1, 3 en 5. Logs kunnen ofwel centraal, ofwel decentraal worden vastgelegd, terwijl het genereren van loggegevens de verantwoordelijkheid van clientapplicaties is. In alle gevallen zal inderdaad gebruik gemaakt moeten worden van een centrale of voldoende frequent gesynchroniseerde tijdsserver.

Hoewel doel en de te loggen gegevensset tussen logregistrat(ies) zoals beschreven in de handreiking logging en de in deze US gevraagde audit trail niet overeenkomen (zie wederom hierboven), dragen zowel deze user story als het volgen van de uitgangspunten uit de handreiking logging bij aan het ontstaan van een complete audit trail. Ik kan me daarom voorstellen dat het een goed is om voor de implementatie daarvan te kijken naar de inrichtingsvariant(en) uit de handreiking logging.

Dat betekent voor de API’s volgens mij dat we moeten zorgen dat met iedere call tenminste de set gegevens wordt meegegeven die minimaal nodig is om een complete audit trail op te kunnen bouwen, en dat in de referentieimplementatie eventueel een of meerdere referentielogregistratie(s) kunnen worden opgenomen om die functionaliteit te demonstreren.

**Comment by sergei-maertens** [comment]
Tijdens sprintplanning besproken:

* APIs moeten logging doen
* Audit trail is een functioneel overzicht op basis van logs
* We eisen dat een user identifier door clients moet meegegeven worden
* Centraal logging component
* Audit trail wordt opgesteld door een client applicatie

**Comment by CMasselink** [comment]
Zoals gisteren besproken volgen we voor de audit trail de implementatierichtlijn van de NORA:
https://www.noraonline.nl/wiki/Inhoud_audit_trail
Vandaag even contact gehad met een privacy en security expert.
Hij gaf aan dat je een handeling uiteindelijk moet kunnen herleiden naar een natuurlijk persoon.
Gegevens die we in ieder geval in de api moeten opslaan om bovenstaande mogelijk te maken:
Applicatie ID
Naam van de gebruiker (Voornaam + achternaam of voorletters + achternaam)
De unieke identifier van de gebruiker in de taakapplicatie waarmee de wijziging is gedaan.
Die laatste is nodig omdat alleen de naam 'Jan Jansen' niet uniek is en daarmee niet herleidbaar naar de persoon.
Vanuit de audit trail zou je er in eerste instantie voor kunnen kiezen om alleen de naam van de persoon te tonen. Op het moment dat voor verder onderzoek details nodig hebt, is dat mogelijk door de applicatie ID en de unieke identifier van de persoon in die taakapplicatie.

**Comment by joeribekker** [comment]
Thanks @CMasselink! Ik maak het nog iets explicieter en neem je feedback mee.

**De NORA definitie**

> De audit trail bevat voldoende gegevens om achteraf te kunnen herleiden (1) welke essentiële handelingen (2) wanneer door (3a) wie of (3b) vanuit welk systeem (4) met welk resultaat zijn uitgevoerd. > Tot essentiële handelingen worden in ieder geval gerekend: opvoeren en afvoeren posten, statusveranderingen met wettelijke, financiële of voor de voortgang van het proces, de zaak of de klant beslissende gevolgen.

[Bron](https://www.noraonline.nl/wiki/Inhoud_audit_trail)

**Architectuur: Logging van verwerking van gegevens**

Aangedragen door @hdksi met zijn kijk op de verhouding. Ivo merkt terecht op dat:

> de hierboven bedoelde Audit trail ≠ het (minimale) register van verwerkingen de handreiking logging.

Het hele AVG verhaal waarbij doelbinding belangrijk is, ontbreekt in deze US, en dus buiten scope valt. Hiervoor ligt wellicht een rol voor taakapplicaties danwel NLx die daar prima functionaliteit voor bieden.

**Besproken**

@sergei-maertens opsomming van wat besproken is in de sprint planning:

> * APIs moeten logging doen
> * Audit trail is een functioneel overzicht op basis van logs
> * We eisen dat een user identifier door clients moet meegegeven worden
> * Centraal logging component
> * Audit trail wordt opgesteld door een client applicatie

Komt neer op (nummers geven volgorde verzoeken aan):

![image](https://user-images.githubusercontent.com/96970/57012528-42a21480-6c07-11e9-90d3-364694152f81.png)

**Wat wil de eindgebruiker (indiener US) zien?**

```
5 mei 2019 11:53 Zaak MOR-000001 is succesvol aangemaakt in ZRC door Joeri Bekker via Demo Applicatie.
5 mei 2019 11:56 Zaak MOR-000001 is succesvol aangepast in ZRC door Joeri Bekker via Demo Applicatie.
5 mei 2019 11:57 Document bijlage-1.jpg is succesvol aangemaakt in DRC door Joeri Bekker via Demo Applicatie.
5 mei 2019 11:58 Document bijlage-1.jpg is succesvol toegevoegd aan Zaak MOR-000001 in ZRC door Joeri Bekker via Demo Applicatie.
```

Dit voldoet tevens aan de NORA definitie.

**Bedenkingen**

Voor de technische implementatie neig ik naar het bijhouden van logregels bij de bron, dus bij het component zelf, zonder een Logging Component (LC):

![image](https://user-images.githubusercontent.com/96970/57012502-269e7300-6c07-11e9-952d-333eeb733c56.png)

Dit heeft enkele voordelen zonder in te boeten op de US:

* Geen nieuw component
* Geen overhead om logs (synchroon) te versturen naar LC
* Geen afhankelijkheid van een LC die up moet zijn om te loggen.
* De componenten zelf kunnen context bieden bij de logs, zodat niet alles over de lijn hoeft naar een LC (een volledige diff bijvoorbeeld van de oude vs nieuwe situatie - valt deels ook onder overhead).
* Er zijn betere manieren om logs te aggregeren (wat de enige meerwaarde is van een LC) dan een synchrone REST API: logstash, fluentd, etc.
* Het aantal requests voor de consumer blijft gelijk, en er hoeft geen aparte LC configuratie plaats te vinden.

**Comment by Hugo-ter-Doest** [comment]
> Er zijn betere manieren om logs te aggregeren (wat de enige meerwaarde is van een LC) dan een synchrone REST API: logstash, fluentd, etc.

Maar dat is dan toch een reden om het in een LC te doen?

**Comment by joeribekker** [comment]
>> Er zijn betere manieren om logs te aggregeren (wat de enige meerwaarde is van een LC) dan een synchrone REST API: logstash, fluentd, etc.

> Maar dat is dan toch een reden om het in een LC te doen? Dan moet het niet bij de voordelen staan.

Wellicht niet lekker verwoord maar een LC is een aggregator van logs. Om die te vullen moeten we een LC opzetten met een REST API en bij de componenten synchroon log entries gaan sturen om deze aggregatie te bereiken. Dit aggregeren kan ook achteraf en zonder het proces in te richten met een LC via een REST API. Dat bedoelde ik met dat er "betere manieren" zijn.

Ik verwoord het even anders.

**Comment by joeribekker** [comment]
Uitwerking is hier weergegeven: https://github.com/VNG-Realisatie/gemma-zaken/pull/958

Dan kan begonnen worden met de OAS en referentie implementatie.
