### ISSUE TITLE
Als leverancier/gemeente wil ik een oplossing voor registraties (endpoints) die  verplaatst worden waardoor objecten waarnaar met URL's wordt verwezen, niet meer op de oude locatie zijn te vinden

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#800]
zodat ik een goede oplossing heb voor migraties, bijv. als ik van leverancier wissel of registraties verplaats.

Wellicht lees ik er overheen in de documentatie maar wat doen we met Objecten die verplaatst zijn? Bijvoorbeeld omdat er van zaaksysteem of endoint wordt gewisseld?

Ik meen ergens te hebben gezien dat er dan een redirect + redirect header wordt gegeven, maar dat zou betekenen dat een oude endpoint tot in het einde der dagen in de lucht moet worden gehouden....

Toelichting: wat het betekent is dat we besluit moeten over werken met absolute URL's of niet.

**Toegevoegd van #931 waar dit probleem iets anders is verwoord:**

3. Moeten we wel met absolute URLs werken als unieke identificatie? We horen soms dat absolute URLs voor problemen gaan zorgen en dat een meer een conceptuele locatie, zoals `ztc-haarlem/zaaktype/xyz`. Wat `ztc-haarlem` gewenst is. Een servicebus kan dit mappen naar een concrete URL.
  a. Zo ja, dan kan het zo zijn dat een absolute URL niet vanaf overal bereikbaar is. Is `http://www.haarlem.nl/ztc/api/v1/zaaktypen/xyz` wel intern binnen het Haarlem intranet bereikbaar? Of andersom zal `intranet.haarlem.nl/ztc/api/v1/zaaktypen/xyz` niet voor buitenaf bereikbaar zijn, maar wellicht wel als deze omgevormd wordt tot een andere URL...
  b. Zo nee, dan MOET er dus ALTIJD een conversie plaatsvinden om een resource te benaderen. Dit geldt voor iedereen die de resource wil benaderen en maakt het opvragen minder makkelijk ECHTER moet je waarschijnlijk toch iets hebben geconfigureerd omdat een resource authenticatie/autorisatie headers nodig heeft. Overigens lost dit wellicht ook het NLx proxy probleem op...

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [x] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [x] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by sergei-maertens** [comment]
Is inderdaad nog niet gespecifieerd, maar m.i. moet de 'oude' locatie een HTTP Permanent Redirect geven naar de nieuwe locatie en moeten consumers referenties updaten.

Dat zou inderdaad betekenen dat een oude endpoint tot het einde der dagen in de lucht moet worden gehouden. Waarom zou dat problematisch zijn?

**Comment by rubenvdlinde** [comment]
Omdat de beschikbaarheid van endpoint niet tot in het einde der dagen te generen is?

Heel specifiek zou een mogelijke implementatie van de huidige norm zijn dat een endpoint op een leveranciers domein zou kunnen staan nlx.leverancier.nl/utrecht/vi1 etc. Maar wat als de gemeente overstap van leverancier? Moet er dan tot het einde der dagen een follow  op contract zijn?

Of wat als de leverancier omvalt, en de domein namen door een curator door worden verkocht? of iemand vergeet een domein naam te verlengen, en die wordt overgenomen? 

Ook gemeentes zelf zijn in het verleden niet super consistent geweest in het beheer van domeinnamen. 

Er zijn dus nogal wat senario's mogelijk waarin de endpoint verdwijnt, gegeven het aantal gemeenten in Nederland, de diversiteit aan pakket en leverancier mogen we wel aannemen dat dit probleem zich gaat voordoen.

**Comment by sergei-maertens** [comment]
Goed om dit perspectief te bieden!

Zou het gebruik van notifications hier soelaas kunnen bieden? Als je een topic `relocation` hebt met als informatie `oud -> nieuw`, dan zouden clients daarop referenties kunnen aanpassen.

Echter dat vereist dus wel dat:

1. iedere consumer daarop geabonneerd is
2. er geen messages verloren gaan
3. alle ontvangers altijd online zijn

Ik zie veel risico.

Andere gedachte: een simpele key-value store die een log bevat van alle 'verplaatsingen'. Dit maakt het voor clients natuurlijk een stuk complexer omdat die dan bij een 404 die keuze hebben om deze log wel/niet te consulteren.

To be continued...

**Comment by Hugo-ter-Doest** [comment]
Zie #931 voor een uitgebreidere user story over het gebruik van URL's. Deze discussie moet beslecht worden voor de RC.

**Comment by joeribekker** [comment]
Uit backlog refinement: Design decision documenteren.

We gaan toch absolute URLs gebruiken (in de API responses) ipv een custom oplossing bedenken met de mogelijkheid pandora's box te openen. Hoe dit intern wordt opgeslagen laten we aan implementatie partijen.

We zien DNS als prima methode om e.e.a. op te lossen. Bijvoorbeeld door altijd het gemeente domein te gebruiken: zrc.api.haarlem.nl verwijst naar een SaaS oplossing van leverancier X, en als er wordt geschakeld naar een andere oplossing kan je gewoon de DNS aanpassen om te wijzen naar die partij. Ook kan DNS binnen een organisatie overruled worden, om bijvoorbeeld naar interne IPs te wijzen.

**Comment by rubenvdlinde** [comment]
Hmmm hier zit wel dus nog steeds de denkfout in dat domeinen consistent vast staan en voor eeuwig behouden blijven, maar goed. Het verliezen van een domein is dan ook nogal een egde case.

Ik zie nog wel een uitdaging met fusie gemeenten en het samenvoegen van datasets, maar das op zich nog wel te ondervangen met DNS zolang de UUID's maar hetzelfde blijven.

**Comment by joeribekker** [comment]
@rubenvdlinde Is geen denkfout maar we accepteren dit risico ten faveure van risico's met andere nog onbekende oplossingen.

**Comment by rubenvdlinde** [comment]
Fair enough

**Comment by joeribekker** [comment]
Braindump tussendoor:

De API's geven wel absolute URLs terug, maar dit zegt niet dat je ook absolute URLs opslaat.

Ik kan me voorstellen dat je een ZRC hebt waarin het DRC root endpoint geconfigureerd is. In de database slaan we de relatieve URL naar de DRC op, en plakken daar de DRC root endpoint voor om de absolute URL weer te geven in API-responses.

Mocht het DRC een keer veranderen, dan worden (neem ik aan) alle documenten gemigreerd naar het nieuwe DRC met hetzelfde UUID (immers zelfde bestand, andere locatie). Het enige dat we dan aan hoeven te passen in ons ZRC is het geconfigureerde DRC root endpoint.

**Comment by rubenvdlinde** [comment]
Oeh I like.

Het betekend wel een extra config laag, die ook enigszins abstract moet zijn (kan me voorstellen dat je vanuit één applicatie met meerdere DRC's) maar dat is zeker te doen. Vraagt wel om e.a. handmatig aanpassen bij migraties maar goed, dat hou je zowiezo wel.

Dus, I like. Goed werkbare oplossing!

**Comment by joeribekker** [comment]
Dit staat verder beschreven in https://github.com/VNG-Realisatie/gemma-zaken/pull/1137/files?short_path=fc0253a#diff-fc0253a1eba1d33a2c926f27afcc1e88
