### ISSUE TITLE
Als ontwikkelaar wil ik een API om notificaties naar toe te sturen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#804]
...zodat deze notificaties doorgestuurd worden naar alle "geabonneerden" teneinde notificaties rond te sturen.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [x] Er is een OAS 3.0 specificatie
- [x] Er is een referentieimplementatie
- [x] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Basis opzet hier uitgewerkt: https://github.com/VNG-Realisatie/gemma-zaken/blob/7297ddfd6caa6db497a113eba7251ffe18f09b80/docs/_content/ontwikkelaars/algemeen/notificaties.md#api-specificatie-concept

**Comment by joeribekker** [comment]
Definitieve opzet: https://github.com/VNG-Realisatie/gemma-zaken/blob/3557f1285592f59ecde14fd90c608f359e0f02cf/docs/_content/ontwikkelaars/algemeen/notificaties.md#api-specificatie

**Comment by joeribekker** [comment]
API specificatie: https://ref.tst.vng.cloud/nc/api/v1/schema/

**Comment by sergei-maertens** [comment]
Gedaan in notificaties sprint
