### ISSUE TITLE
Als ontwikkelaar wil ik een API-specificatie die ik moet implementeren in mijn component om notificaties op te ontvangen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#806]
...zodat notificaties die ik wil ontvangen ook daadwerkelijk naar mijn component verstuurd kunnen worden.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [x] Er is een referentieimplementatie
- [x] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Basis opzet hier uitgewerkt: https://github.com/VNG-Realisatie/gemma-zaken/blob/7297ddfd6caa6db497a113eba7251ffe18f09b80/docs/_content/ontwikkelaars/algemeen/notificaties.md#notificatie-ontvanger-push-api-specificatie

**Comment by joeribekker** [comment]
Definitieve opzet: https://github.com/VNG-Realisatie/gemma-zaken/blob/3557f1285592f59ecde14fd90c608f359e0f02cf/docs/_content/ontwikkelaars/algemeen/notificaties.md#notificatie-bericht-specificatie

Attribuut | Omschrijving
--- | ---
kanaal | De naam van het kanaal (Exchange in AMQP) behorend bij de bron. (bijv. `zaken`, `documenten`, `besluiten`, etc.)
hoofdObject | De URL van de resource behorend bij het kanaal (bijv. `Zaak`) van de actuele resource (omdat we nog geen historie hebben)
resource | Naam van de daadwerkelijk resource die is gewijzigd (bijv. `Status`)
resourceUrl | De URL van de daadwerkelijk resource (optioneel)
actie | De actie die de gebeurtenis op abstract niveau omschrijft. Dit is een vaste lijst bestaande uit `gewijzigd`, `verwijderd`, `aangemaakt` eventueel aangevuld met additionele waarden, die per bron zijn vastgelegd in de standaard.
aanmaakdatum | Datum en tijd van gebeurtenis
kenmerken | Een lijst van objecten die de kenmerken van het bericht vormen. De mogelijke kenmerken worden vastgelegd per bron in de standaard.

**Voorbeeld bericht**

Zoals abonnees deze ontvangen:

```json
{
    "kanaal": "zaken",
    "hoofdObject": "https://ref.tst.vng.cloud/zrc/api/v1/zaken/d7a22",
    "resource": "status",
    "resourceUrl": "https://ref.tst.vng.cloud/zrc/api/v1/statussen/d7a22/721c9",
    "actie": "create",
    "aanmaakdatum": "2018-01-01T17:00:00Z",
    "kenmerken": [
        {"bron": "082096752011"},
        {"zaaktype": "https://example.com/api/v1/zaaktypen/5aa5c"},
        {"vertrouwelijkheidaanduiding": "openbaar"}
    ]
}
```
