### ISSUE TITLE
Als Product Owner wil ik graag de gerealiseerde notificatie functionaliteit tonen in de demo applicatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#808]
...zodat deze helder gepresenteerd kunnen worden bij de demo.

**Concreet**

Een kleine Mijn MOR-meldingen omgeving waar een notificatie binnenkomt als je MOR-melding ZAAK van status veranderd.

(met goedkeuring van PO en Scrummaster direct in sprint geplaatst)

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [x] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [x] Er is een implementatie

**Taken**
- [x] Implementeren [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Artis impression ;-)

![image](https://user-images.githubusercontent.com/96970/53967569-c8b54980-40f5-11e9-8976-1e4240bc3967.png)

**Comment by TCIMEddy** [comment]
@joeribekker fraai! dat gaat aanspreken tijdens demo, mooi als je nog iets kan verzinnen mbt document...

**Comment by joeribekker** [comment]
Je moet me helpen @TCIMEddy . Bedoel je een notificatie als een document is toegevoegd aan een zaak?

**Comment by TCIMEddy** [comment]
@joeribekker Ja iets in die trant maar zie je donderdag. Burger voegt bijvoorbeeld foto toe (kan zelfs na verzoek door ambtenaar) aan een MOR-melding die is ingediend met als status in behandeling (of informatie opgevraagd). Op het moment dat er een foto is bijgevoegd gaat er een notificatie naar de behandelaar om eea af te handelen
