### ISSUE TITLE
Als gemeente wil ik voor elke taakapplicatie per zaaktype kunnen aangeven welke rechten daar bij horen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/gemma-zaken#838]
zodat een taakapplicatie nooit te veel rechten heeft. 
Past binnen het privacy by design principe waarbij er nooit meer informatie uit een bronapplicatie komt dan zou mogen. We passen dus filtering bij de bron toe.

Concreet willen we kunnen:
Je wilt kunnen aangeven dat een taakapplicatie lees en schrijfrechten heeft op zaaktype A, B en C en alleen leesrechten op zaaktypes XYC. Ook wil je op vertrouwelijkheidsaanduiding toegang tot zaaktypes kunnen beperken.
We lossen dit op met nesting van scopes en zaaktypes:
Scope: 
+ Zaken schrijven
   + Zaaktype melding openbare ruimte
    + Zaaktype aanvraag subsidie behandelen
+ Zaken lezen
  + Aanvraag parkeervergunning behandelen

ZGW api's moeten validatie doen van scopes en claims die door de taakapplicatie naar ZGW api's gestuurd worden.

Als een taakapplicatie geen rechten heeft om te schrijven op een zaaktype, mag de taakapplicatie ook geen documenten of andere objecten aan de zaak kunnen koppelen.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by joeribekker** [comment]
Voorbeeld (van Constantijn):

Neem een taakapplicatie voor vergunningen: Deze moet een Vergunningsaanvraag (zaaktype V) kunnen **aanmaken als Zaak** die wellicht een gerelateerde Bezwaarzaak (zaaktype B) heeft, en deze moet kunnen **lezen**. Scopes zijn hier dus gekoppeld aan Zaaktypes.

**Comment by joeribekker** [comment]
Oplossingsrichting is nog niet helemaal helder:

Globaal is gaat het om: Limiteren van rechten (scopes, zaaktypes, etc. in de JWT) aan de kant van de provider

De huidige JWT heeft losse scopes en zaaktypes erin. Het is dus niet mogelijk om genestheid toe te voegen zoals in comment hierboven. Limiteren kan dus nu niet op dat niveau in de JWT. Het zou kunnen aan de provider kant. Echter, dan krijg je dus scopes die niet persé overeenkomen met de configuratie aan de kant van de provider wat tot onduidelijkheid leidt.

**Comment by TCIMEddy** [comment]
@CMasselink Is nu niet ready maar de sprint begint over 2 weken....Indien ready wordt hij gerealiseerd indien niet dan blijft hij op de backlog. Als team willen we dit wel dus wil jij organiseren dat deze wel ready wordt (op maandagmiddag voor bord o.i.d.)

**Comment by CMasselink** [comment]
@joeribekker @sergei-maertens @Hugo-ter-Doest : komende maandag middag dan naar bovenstaande kijken?

**Comment by hdksi** [comment]
Uit te zoeken: hoe werkt dit als gegevens uitgewisseld worden tussen organisaties? Moeten we dan ook configureren voor clients buiten de organisatie? En hoe verhoudt zich dat eventueel tot het principe dat we organisaties vertrouwen en op dat niveau autoriseren bij uitwisseling tussen organisaties?

**Comment by TCIMEddy** [comment]
ik heb deze geclosed omdat deze in de kolom done stond....
