### ISSUE TITLE
Als API-ontwikkelaar wil ik dat autorisaties in het meest logische component beheerd kunnen worden

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#844]
...zodat ik de verschillende componenten binnen de standaard niet onnodig met elkaar hoef te verknopen.

Gerelateerd aan: #838.

Oplossing autorisatie: mag ik een relatie tussen zaak en document aanleggen als ik alleen rechten heb om documenten te creëren of te updaten en niet om zaken te creëren of te updaten? NEE.

Om het bovenstaande mogelijk te maken is het nodig dat het Koppelen van Zaak en Document wordt geïnitieerd vanuit het ZRC, en niet het niet DRC zoals nu het geval is. Immers, de autorisatie voor het koppelen van een Document aan een Zaak moet gekoppeld zijn aan de autorisatie voor het aanmaken of te muteren van Zaken, en de autorisatie voor het aanmaken en muteren van Documenten.

**Bepaling prioriteit door PO**

- [x] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden of afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by hdksi** [comment]
Ik had beloofd hier na overleg met @jeffreygortmaker1 op terug te komen. Was een kort gesprek; volgens Jeffrey waren er 50 redenen vóór en 50 tegen het (primair) leggen van de koppeling tussen zaak en document bij het DRC. Belangrijkste reden voor de gekozen oplossing: als het ZRC wegvalt, dan gaat de betekenis van de documenten in het DRC niet verloren. Dat is iets waar we over na moeten denken, maar volgens mij zijn er dus geen zwaarwegende redenen om niet de koppeling primair bij het ZRC te leggen nu dit voor autorisatie (grote) voordelen biedt.

**Comment by Hugo-ter-Doest** [comment]
En redundantie is ook te regelen als de relatie primair bij de zaak komt te liggen.

**Comment by hdksi** [comment]
Precies, goed dat je dat nog even expliciet benoemt. Initiatief en betekenisbehoud zijn inderdaad niet noodzakelijkerwijs aan elkaar geklonken. Vandaar mijns inziens dus wel nog even nadenken over hoe we dit oplossen, maar geen bezwaar tegen de voorgestelde aanpassing.

**Comment by hdksi** [comment]
@Hugo-ter-Doest: gerealiseerd, mag wat mij betreft gesloten worden.
