### ISSUE TITLE
Als burger wil ik een niet-verwarrende notificatie ontvangen als de status van mijn zaak wordt gewijzigd als gevolg van een correctieve aanpasing daarvan

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/gemma-zaken#859]
...zodat ik duidelijk het verschil kan zien tussen 'reguliere' (bijvoorbeeld het bereiken van een volgende status tijdens het afhandelingsproces) en 'correctieve' (bijvoorbeeld herstel van verkeerd gezette status) updates.

Hiervoor is het dus nodig dat op basis de informatie in de notificatie het onderscheid tussen 'reguliere' en 'correctieve' updates gemaakt kan worden.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest graag bevestiging van prio

**Comment by Hugo-ter-Doest** [comment]
Wat is een correctieve update? En wat is een reguliere update?

**Comment by hdksi** [comment]
Uitstekende vraag. Ik heb de US wat geprobeerd te verduidelijken. Helpt dat?

**Comment by Hugo-ter-Doest** [comment]
Ja, is duidelijk zo. Ik denk dat de registratiecomponenten geen onderscheid kan maken tussen een reguliere wijziging en een correctieve. Derhalve moet de filtering aan de kant van de consumer worden gedaan.
