### ISSUE TITLE
Als PO wil ik dat er op het API-lab een korte tutorial wordt gegeven over het onderwerp autorisatie

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#865]
...zodat developers in een korte tijd kennis kunnen opdoen over dit onderwerp, en dit zonder al te veel leeswerk en studie kunnen gebruiken in hun applicaties.

Toelichting:

- Te geven tijdens dag 1 van het API-lab
- Max 15 min.
- Hands-on, dus met codevoorbeelden en voorbeeldberichten.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [x] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [x] Er is een tutorial

**Acceptatiecriteria**
- [ ] De tutorial is begrijpelijk voor beginners
- [ ] De tutorial is vindbaar

**Taken**
- [x] Opstellen presentatie
- [ ] Publiceren PDF van PPT

**Comment by sergei-maertens** [comment]
Presentatie voor tutorial staat op Slack ter review. Deze wil ik uiteraard ook publiceren op Github als PDF.
