### ISSUE TITLE
Als teamlid wil ik inzicht in kaders, standaarden en oplossing(srichting)en voor formele en materiele historie

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#868]
zodat historie aan de ZGW API's kan worden toegevoegd conform geldende standaarden, en zodat we het wiel niet opnieuw hoeven uit te vinden.

Toelichting: 
Bedoeling van deze user story is de state of the art over materiele/formele historie te verkennen om randvoorwaarden en mogelijke oplossingen te verkrijgen. Zie onder taken voor de documenten die we bekijken.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
Volgende documenten over historie doornemen:
- [ ] Programma aan de slag met de Omgevingswet - Kaderstellende notitie Tijdreizen wie?
- [ ] [DeelprogrammaDigitaal Stelsel Omgevingswet, Kaderstellende notitiesURI-strategie, Par. 2.9, p. 17](https://aandeslagmetdeomgevingswet.nl/publish/pages/143597/uri-strategie_-_12_maart_2018.pdf) wie?
- [ ] [Representatie materiële en formele historie](https://www.gemmaonline.nl/images/gemmaonline/f/fc/TheorieHistorie5.pdf) @HenriKorver 
- [ ] [Standaard Uitwisseling Formaat, StUF 03.01: In Gebruik](https://www.gemmaonline.nl/images/gemmaonline/f/fa/Stuf0301.pdf) @HenriKorver 
- [ ] BRP, Aspectbeschrijving–Historiefilter @hdksi 
- [ ] [Historiemodel BAG2018](https://zakelijk.kadaster.nl/documents/20838/87954/Specificatie+BAG+historiemodel/7f6d5baf-1e0f-ec57-d121-fee337ee6b92) @Hugo-ter-Doest
