### ISSUE TITLE
Als ontwikkelaar wil ik weten waar ik de producten uit user stories beschikbaar kan maken...

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#87]
...zodat andere mensen deze kunnen benaderen.

**Definition of done**

- [ ] Toegang tot domein
- [ ] Toegang tot server

**Acceptatiecriteria**

Uit de algemene uitgangspunten:

- [ ] Genoeg ruimte om alles te hosten
- [ ] Python 3 ondersteuning op de server

**Taken**
- [ ] Server/toegang regelen [@ehotting]
- [ ] Domein/toegang regelen [@ehotting]
- [ ] Verifiëren toegang [@joeribekker]

**Comment by joeribekker** [comment]
Ik sluit deze User Story i.v.m. #93
