### ISSUE TITLE
API-lab 17/18 april 2019

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/gemma-zaken#884]
API-lab

- [ ] Programma en inleiding (@Hugo-ter-Doest)
- [x] tutorials (aparte user stories) #862 #863 #865 #866
- [ ] kookwekker (@TCIMEddy)
- [ ] Mentimeter (@TCIMEddy) #888
- [x] lokatie en voorzieningen (@wishalg)

**Comment by Hugo-ter-Doest** [comment]
Voor de tutorials op het API-lab user stories: #862 #863 #865 #866

Voor de enquete op het API-lab zie #888
