### ISSUE TITLE
Als medewerker wil ik een informatieobject status definitief kunnen geven

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#905]
...zodat er geen wijzigingen kunnen worden aangebracht (lees: nieuwe versies kunnen worden toegevoegd).

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Heeft al prio...

**Comment by sergei-maertens** [comment]
TODO: valideren bij het bijwerken van een IO dat de status niet definitief is

**Comment by joeribekker** [comment]
Waarde voor leveranciers: Minder fouten door consumers; voor gemeenten: Kwaliteit van data.

**Comment by joeribekker** [comment]
hierna wordt ie dus readonly.

**Comment by sergei-maertens** [comment]
Fixed in https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/commit/6609a0db1ae0918ce8ccc542fd65ce1faa0fc934

**Comment by PDG65** [comment]
Aantal punten gecorrigeerd van 5 naar 1 omdat 5 punten van vorige sprint is en hier alleen nog review voor nodig was
