### ISSUE TITLE
Linked data probleem

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#931]
Ik kon hier geen US voor bedenken omdat ik veel mensen hierover hoor maar niet echt goede scenario's krijg voorgeschoteld. Wel zie ik in dat er onduidelijkheid en onzekerheid is over linked data.

Ik denk dat we toch een uitspraak moeten doen hierover en niet wachten op de API strategie of aan de markt overlaten.

**Probleem beschrijving**

De URL `/api/v1/zaaktype/xyz` representeert Zaaktype `xyz` volgens versie 1 van de API. Als we een Zaak aanmaken met een verwijzing naar Zaaktype `/api/v1/zaaktype/xyz` en er wordt een nieuwe versie van de API gereleased, is hetzelfde Zaaktype opeens beschikbaar als `/api/v2/zaaktype/xyz` 

**Wat kunnen we hier allemaal over gaan zeggen?**

1. Moeten oude versies (zoals v1 in het voorbeeld) van de URLs altijd blijven bestaan?
  a. Zo ja, doen we dan een redirect naar v2? Of niet?
  b. Zo nee, dan moet er een migratie gemaakt worden.

  *Belangrijk sidenote is dat het dus niet versie 1 of 2 van het Zaaktype zelf betekent (maar dit wel toevallig kan zijn). Het gaat puur om de representatie van het Zaaktype.*

2. Moeten URLs wel een versie hebben? Waarom gebruiken we niet `/api/zaaktype/xyz` en redirect deze gewoon naar de meest recente versie (of geeft deze versie direct weer zonder redirect)?
  a. Zo ja, dan moeten we naar 1 kijken.
  b. Zo nee, dan lossen we het probleem in 1 op maar het wordt onduidelijker welke versie een client nu precies terug krijgt. Dat kan dus zomaar van versie 1 naar versie 2 veranderen waardoor dingen stuk gaan.
    * Eventuele oplossing voor dat probleem is weer om via de header een bepaalde versie af te dwingen.

Onderstaand punt wordt in #800 beslecht:

~~3. Moeten we wel met absolute URLs werken als unieke identificatie? We horen soms dat absolute URLs voor problemen gaan zorgen en dat een meer een conceptuele locatie, zoals `ztc-haarlem/zaaktype/xyz`. Wat `ztc-haarlem` gewenst is. Een servicebus kan dit mappen naar een concrete URL.
  a. Zo ja, dan kan het zo zijn dat een absolute URL niet vanaf overal bereikbaar is. Is `http://www.haarlem.nl/ztc/api/v1/zaaktypen/xyz` wel intern binnen het Haarlem intranet bereikbaar? Of andersom zal `intranet.haarlem.nl/ztc/api/v1/zaaktypen/xyz` niet voor buitenaf bereikbaar zijn, maar wellicht wel als deze omgevormd wordt tot een andere URL...
  b. Zo nee, dan MOET er dus ALTIJD een conversie plaatsvinden om een resource te benaderen. Dit geldt voor iedereen die de resource wil benaderen en maakt het opvragen minder makkelijk ECHTER moet je waarschijnlijk toch iets hebben geconfigureerd omdat een resource authenticatie/autorisatie headers nodig heeft. Overigens lost dit wellicht ook het NLx proxy probleem op...~~

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [x] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [x] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by Hugo-ter-Doest** [comment]
Lopen meerdere zaken door elkaar. Graag overleg.

**Comment by joeribekker** [comment]
Design decision is genomen: We volgende weg van de API strategie alsmede wat alle grote bedrijven doen: versie nummer in de URL. Wel gaan we een uitspraak doen over hoe om te gaan met nieuwe versies (redirects? en verwijzingen).

**Comment by joeribekker** [comment]
https://github.com/Geonovum/KP-APIs/issues/7
