### ISSUE TITLE
Als ZTC beheerder wil ik alle resources van de ZTC kunnen aanmaken, bijwerken of verwijderen

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [VNG-Realisatie/gemma-zaken#938]
...zodat ik vanuit een ZTC beheerapplicatie alle content van ZTC's kan beheren.

Opmerking:
Verwijderen is niet triviaal omdat het alleen mag als er nog geen instanties van het betreffende type zijn gecreeerd.

We introduceren een vlag die een zaaktype (of gelijkaardig) markeert als 'draft', deze worden niet ontsloten via de API voor ZRCs. Zolang draft status van toepassing is, kan bewerkt en verwijderd worden. Eenmaal draft uit gaat, kan deze niet meer aan, en kan je niet meer verwijderen. Bewerken betekent een nieuwe versie.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] _Globale_ oplossingsrichting bekend
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by erenes** [comment]
Alhoewel het voor de hand ligt dat dit in de standaard zit, en dat een ZTC beheerder zaaktypen wil beheren, vraag ik me af in hoeverre ZTC providers (waaronder ikzelf) wijzigingen willen toestaan in catalogussen in hun beheer. 

We zijn niet alleen een database met zaaktypen, maar hebben daar bovenop ook een zaaktypenbeheer tool gebouwd. Je kunt dus eigenlijk al alle resources aanmaken en bijwerken vanuit onze eigen user interface. Ik kan me niet voorstellen dat andere ZTC providers niet hun eigen User Interface bieden voor het beheren van zaaktypen (in het referentiecomponent is het de admin pagina). 

Met dat in het achterhoofd denk ik niet dat eerder een nice-to-have is, dan een must-have voor de RC. Ik vraag me af hoe andere implementatiepartijen hierover denken?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest zie opmerking Erenes

**Comment by Hugo-ter-Doest** [comment]
Het is niet de bedoeling om een user interface te maken, alleen de operaties die je in de API nodig hebt om zaaktypen te kunnen creeren, aanpassen en verwijderen. Op dit moment is alleen GET voor de verschillende resources beschikbaar in de API. Daar moeten PUT, PATCH, DELETE aan toe worden gevoegd.

**Comment by erenes** [comment]
> Het is niet de bedoeling om een user interface te maken, alleen de operaties die je in de API nodig hebt om zaaktypen te kunnen creeren, aanpassen en verwijderen. Op dit moment is alleen GET voor de verschillende resources beschikbaar in de API. Daar moeten PUT, PATCH, DELETE aan toe worden gevoegd.

Ik begrijp technisch `wat` gevraagd wordt, maar ben op zoek naar de target audience voor deze api-wijziging. 

Naast de extra ontwikkelinspanning die nodig is om dit te gaan ondersteunen, verwacht ik niet dat wij snel onze zaaktype-data in een andere ZTC zullen opslaan. Vice-versa verwacht ik ook niet dat iemand anders snel hun zaaktypen bij ons zal opslaan. De user story "Als ZTC beheerder wil ik alle resources van de ZTC kunnen beheren" wordt volgens mij al vervuld door de user interfaces van alle zaaktypencatalogus-pakketten die nu op de markt zijn. 

Real-world toepassingen die ik hiervoor zie: 
* 3rd party User Interface bouwen op een bestaande ZTC van een andere partij. 
* Het publiceren van zaaktypen uit onze catalogus naar een andere partij. Ik zou liever zelf de zaaktypen ophalen (pull) bij een derde partij dan dat ze bij ons door een derde partij gepubliceerd worden (push), omdat er dan een beheerder van onze catalogus naar kan kijken en nog instellingen kan maken die wij hebben bovenop de standaard (denk aan gebruikersrechten etc) voordat het zaaktype beschikbaar is in het zaaksysteem. 

Het is een logische stap om de standaard meer 'compleet' te maken, maar ik zie het niet zo zitten om externe partijen schrijftoegang te geven op onze zaaktypen-database. Vandaar dus deze feedback en mijn eerdere vraag naar hoe andere implementatiepartijen hier naar kijken?

**Comment by CMasselink** [comment]
Ik vind het nog belangrijker hoe gemeenten hier naar kijken. Als gemeenten biedt een ZTC api die over de volledige operaties beschikt om een ZTC te beheren, flexibiliteit. Zoals we het registeren van zaken (middels de ZRC) scheiden van de applicatie die een zaak afhandelt (een taakapplicatie in de rol van ZAC of een generiek ZAC), wil je dat ook kunnen doen voor het ZTC.
Ik ben het dus helemaal eens met @Hugo-ter-Doest dat de ZTC api's uitgebreid moeten worden met de genoemde operaties.

**Comment by erenes** [comment]
> Ik vind het nog belangrijker hoe gemeenten hier naar kijken. Voor gemeenten biedt een ZTC api die over de volledige operaties beschikt om een ZTC te beheren, flexibiliteit. Zoals we het registeren van zaken (middels de ZRC) scheiden van de applicatie die een zaak afhandelt (een taakapplicatie in de rol van ZAC of een generiek ZAC), wil je dat ook kunnen doen voor het ZTC.
> Ik ben het dus helemaal eens met @Hugo-ter-Doest dat de ZTC api uitgebreid moeten worden met de genoemde operaties.

Bedankt voor de feedback.
Dus de nieuwe user story is: “Als gemeente wil ik flexibel zijn in het beheer van mijn ZTC”.

Je maakt hier een vergelijking met het ZRC waar het afhandelen van zaken gescheiden is van het registreren van zaken. Dat wil je voor een ZTC ook, bedoel je dan bijvoorbeeld dat het mogelijk moet zijn een applicatie te hebben die specifiek extra informatie voor één objecttype (zoals besluiten) heeft? Moet die applicatie die extra informatie dan terugschrijven naar een centrale ZTC? Moet het centrale ZTC de informatie publiceren naar third parties?

Omdat ik mijn bedenkingen heb bij de praktische toepassing, probeer ik helder te krijgen wat de echte verwachting voor een scheiding binnen ZTC nu is. Een discussie als deze helpt daarbij en maakt het voor eventuele latere lezers ook duidelijk waarom een bepaalde beslissing is genomen.

**Comment by Hugo-ter-Doest** [comment]
Nee, de user story is prima geformuleerd. Er geldt vanuit de visie van Common Ground dat er een knip wordt gemaakt tussen gegevens (in registraties) en logica en presentatie. Derhalve zijn naast GET ook de andere operaties nodig om zaaktypen etc. te kunnen beheren. Uiteindelijk zullen alle applicaties volgens de indeling van vijf lagen van Common Ground moeten gaan werken.

**Comment by erenes** [comment]
Ok, wat mij betreft duidelijk dan. Het is dus een common ground principekwestie dat we deze operaties nodig hebben.  

Ik had nog nooit van het 5 lagen model gehoord, dus voor andere mensen die hier uitkomen, [een linkje naar (een korte) uitleg hierover](https://www.gemmaonline.nl/index.php/GEMMA_en_Common_Ground)

**Comment by joeribekker** [comment]
Het ZTC is nu schrijfbaar (zolang een object in concept is).
