### ISSUE TITLE
Unieke constraint op ZTC-resources moet inclusief "versie" en begin/eindGeldigheid toevoegen aan API

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#982]
...zodat workaround van #887 kan.

Versies komen dus expliciet **niet** in de URL of in het ZTC, er komen voor 2 zaaktypes 2 unieke URLs (met eigen UUIDs) maar we dwingen af dat de "code" of "omschrijving" wel uniek is in combi met begin/eind geldigheid en dat er geen nieuwe "versie" mag komen met overlappende begin/eind geldigheid.

Er komt maar 1 begin/eind van de root-resources, sub resources (conceptueel of niet) krijgen dit niet.

Onderstaande "vink-lijst" is voor het team zelf om in te vullen en hoeft niet door de indiender te worden ingevuld.

**Bepaling prioriteit door PO**

- [ ] verbreding of verdieping API's
- [ ] stimuleert gebruik door gemeenten
- [ ] stimuleert gebruik door leveranciers

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] de gewenste (aanvulling op de) functionaliteit van de API's duidelijk en beschreven is.
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _Globale_ oplossingsrichting bekend
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Er is een OAS 3.0 specificatie
- [ ] Er is een referentieimplementatie
- [ ] Er zijn tests(cases) aanwezig die de wijziging aantonen en waarmee de user story getest kan worden.
- [ ] De technische specificatie (standaard.md) is gepubliceerd leesbaar
- [ ] Gebruikte gegevensmodel is na **iedere iedere sprint** bijgewerkt.

**Acceptatiecriteria**
- [ ] De DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] Er zijn geen bekende GEMMA tegenstrijdigheden **of** afwijkingen zijn vastgelegd.

**Taken**
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]
- [ ] Documentatie bijwerken
- [ ] Gegevensmodel bijwerken

**Comment by sergei-maertens** [comment]
Geen begin/eindGeldigheid voor statustype/resultaattype/andere direct geneste resources

**Comment by CMasselink** [comment]
Opmerking vanuit onze beheerders:
Als deze work around toegepast wordt, dan is het wel heel prettig als vanuit de zaaktype beheercomponent ook de autorisaties gekopieerd kunnen worden naar het nieuwe zaaktype. Anders wordt het beheer op autorisaties heel lastig.

**Comment by TCIMEddy** [comment]
Opmerking Constantijn buiten scope

**Comment by sergei-maertens** [comment]
Needs to pass more review w/r to API spec
